### ISSUE TITLE
VMs don't get cleaned up properly when compilation fails

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1011]
We've recently seen this situation a few times:
* start a deployment
* when the deployment fails after compilation, the compilation VM is still there (in this case something failed during template rendering, afaik)
* If this is relevant: `reuse_compilation_vms` is set to `true`

Why is this relevant?
* we let bosh choose the IPs for compilation VMs (manual networking, but no static IPs of course)
* in the next deployment, bosh tries to bring up a compilation VM with the IP of the left-over compilation VM from the previous, failed run
* seems like bosh has 'forgotten' this VM even exists (probably because the previous deployment failed)

So what should happen?
* probably bosh should either clean up the compilation VM after a failed run or have its IP address in the director db. Manual interaction should not be necessary.

I think I've seen the same thing for errands as well: Errand VMs are still there when a previous run failed and didn't get cleaned up properly.

**Comment by cppforlife** [comment]
Please include `bosh deploy` output when this happens. Compilation VMs typically get deleted before other parts of the deploy starts.

**Comment by voelzmo** [comment]
While looking more thorough through the logs I found the issue in this case:
* The previous deploy failed because the compilation VM with that specific IP couldn't be brought up (IaaS timed out)
* In the next deployment that IP was already taken. So it seems the IaaS brought up the VM after all.

I'll re-open this when I encounter it again and have made sure that it is not an IaaS issue.

**Comment by bosh-ci-push-pull** [comment]
do you have more details how cpi failed (stacktrace) and lost track of the vm?

**Comment by voelzmo** [comment]
This is the run where the VM didn't come up. Some timeout, but seems like the VM did come up after all:

```
D, [2015-11-05T16:45:41.854837 #6623] DEBUG -- : excon.request {:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1", "Content-Type"=>"application/json", "Accept"=>"application/json", "X-Auth-Token"=>"bfc3ebe3500f4612ae55f735cc1d59c9", "Host"=>"<redacted>:<redacted>"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>false, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/2.1.7", :write_timeout=>60, :host=>"<redacted>", :hostname=>"<redacted>", :path=>"/v2/p-b1bd5299d/servers.json", :port=><redacted>, :query=>nil, :scheme=>"https", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor, :body=>"{\"server\":{\"flavorRef\":\"4\",\"imageRef\":\"03efa09d-7ab5-40e7-835c-278efbebbd38\",\"name\":\"vm-31448e72-1abd-41f3-9b2e-c00cb6d3c721\",\"availability_zone\":\"<redacted>\",\"user_data\":\"<redacted>\",\"key_name\":\"master\",\"security_groups\":[<redacted>],\"networks\":[{\"uuid\":\"c65e3621-26a4-4ecf-a7b7-9b626e2fcdc3\",\"fixed_ip\":\"10.3.4.42\"}]}}", :expects=>[200, 202], :method=>"POST", :retries_remaining=>4, :connection=>#<Excon::Connection:7fb9740a0f70 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>false, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/2.1.7", :write_timeout=>60, :host=>"<redacted>", :hostname=>"<redacted>", :path=>"", :port=><redacted>, :query=>nil, :scheme=>"https", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="https://<redacted>:<redacted>">, :stack=>#<Excon::Middleware::ResponseParser:0x007fb9735bb6f0 @stack=#<Excon::Middleware::Expects:0x007fb9735bb718 @stack=#<Excon::Middleware::Idempotent:0x007fb9735bb7b8 @stack=#<Excon::Middleware::Instrumentor:0x007fb9735bb7e0 @stack=#<Excon::Middleware::Mock:0x007fb9735bb858 @stack=#<Excon::Connection:7fb9740a0f70 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>false, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/2.1.7", :write_timeout=>60, :host=>"<redacted>", :hostname=>"<redacted>", :path=>"", :port=><redacted>, :query=>nil, :scheme=>"https", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="https://<redacted>:<redacted>">>>>>>}
D, [2015-11-05T16:46:41.924745 #6623] DEBUG -- : excon.error {:error=>#<Excon::Errors::Timeout: read timeout reached>}
, exit_status: pid 6614 exit 0
E, [2015-11-05 16:46:41 #6591] [compile_package(ruby_2.1.5/a8612d8ed0e33940e9ae04dffd94edcbaa3de527, bosh-openstack-kvm-ubuntu-trusty-go_agent/3115)] ERROR -- DirectorJobRunner: error creating vm: Unknown CPI error 'Unknown' with message 'read timeout reached'
D, [2015-11-05 16:46:41 #6591] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2015-11-05 16:46:41 #6591] [compile_package(ruby_2.1.5/a8612d8ed0e33940e9ae04dffd94edcbaa3de527, bosh-openstack-kvm-ubuntu-trusty-go_agent/3115)] DEBUG -- DirectorJobRunner: Deleting lock: lock:compile:90:1
D, [2015-11-05 16:46:41 #6591] [compile_package(ruby_2.1.5/a8612d8ed0e33940e9ae04dffd94edcbaa3de527, bosh-openstack-kvm-ubuntu-trusty-go_agent/3115)] DEBUG -- DirectorJobRunner: Deleted lock: lock:compile:90:1
D, [2015-11-05 16:46:41 #6591] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: Unknown CPI error 'Unknown' with message 'read timeout reached' - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3123.0/lib/cloud/external_cpi.rb:108:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3123.0/lib/cloud/external_cpi.rb:89:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3123.0/lib/cloud/external_cpi.rb:51:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/vm_creator.rb:41:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/vm_creator.rb:9:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:153:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:80:in `block in compile_package'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:73:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:302:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:300:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:296:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:256:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2015-11-05 16:46:41 #6591] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: Waiting for tasks to complete
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2015-11-05 16:46:41 #6591] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:logsearch-apps
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:logsearch-apps
I, [2015-11-05 16:46:41 #6591] [task:24]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"8b596f8b-4648-45ac-8118-d372aa7bd389","severity":3,"title":"director - error during update deployment","summary":"Error during update deployment for 'logsearch-apps' against Director '188bab23-4c96-4800-977e-8cafb93b2926': #<Bosh::Clouds::ExternalCpi::UnknownError: Unknown CPI error 'Unknown' with message 'read timeout reached'>","created_at":1446742001}
E, [2015-11-05 16:46:41 #6591] [task:24] ERROR -- DirectorJobRunner: Unknown CPI error 'Unknown' with message 'read timeout reached'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3123.0/lib/cloud/external_cpi.rb:108:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3123.0/lib/cloud/external_cpi.rb:89:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3123.0/lib/cloud/external_cpi.rb:51:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/vm_creator.rb:41:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/vm_creator.rb:9:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:153:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:80:in `block in compile_package'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:73:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:302:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:300:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:296:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3123.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:256:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3123.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: (0.000477s) SELECT NULL
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: (0.000136s) BEGIN
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: (0.000700s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2015-11-05 16:46:41.981592+0000', "description" = 'create deployment', "result" = 'Unknown CPI error ''Unknown'' with message ''read timeout reached''', "output" = '/var/vcap/store/director/tasks/24', "checkpoint_time" = '2015-11-05 16:46:30.638838+0000', "type" = 'update_deployment', "username" = 'admin' WHERE ("id" = 24)
D, [2015-11-05 16:46:41 #6591] [task:24] DEBUG -- DirectorJobRunner: (0.001995s) COMMIT
I, [2015-11-05 16:46:41 #6591] []  INFO -- DirectorJobRunner: Task took 1 minute 11.362545248999993 seconds to process.

Task 24 error
```
