### ISSUE TITLE
bosh micro deploy problem

### ISSUE THREAD

**Issue by mahsa-frj** [cloudfoundry/bosh#1013]
Hi, I'm using the instruction in below link:
http://bosh.io/docs/deploy-microbosh-to-openstack.html
and I downloaded bosh-stemcell-3115-openstack-kvm-centos-7-go_agent.tgz, but when i execute this command :  bosh micro deploy bosh-stemcell-3115-openstack-kvm-centos-7-go_agent.tgz
I get this output:

    Conventionally, `bosh-deployments.yml` should be saved in /root.
    Is /root/my-micro-deployment a directory where you can save state? (type 'yes' to continue): yes
    Deploying new micro BOSH instance `manifest.yml' to `https://x.x.x.x:25555' (type 'yes' to   continue): yes

    Verifying stemcell...
    File exists and readable                                     OK
    Verifying tarball...
    Read tarball                                                       OK
    Manifest exists                                                   OK
    Stemcell image file                                             OK
    Stemcell properties                                             OK

    Stemcell info
     -------------
    Name:    bosh-openstack-kvm-centos-7-go_agent
    Version: 3115
    /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- fog (LoadError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
    from /usr/local/share/gems/gems/bosh-registry-1.3126.0/lib/bosh/registry.rb:10:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/local/share/gems/gems/bosh-registry-1.3126.0/bin/bosh-registry:3:in `<top (required)>'
    from /usr/local/bin/bosh-registry:23:in `load'
    from /usr/local/bin/bosh-registry:23:in `<main>'
    `bosh-registry -c /tmp/d20151107-3117-scmzcw/bosh_registry_yml20151107-3117-r6nn32` failed, exit status=1

thanks for your help.

**Comment by guoger** [comment]
Hi there, I'm not very familiar with BOSH micro plug-in but you probably could use bosh-init instead. http://bosh.io/docs/using-bosh-init.html That's how we do it in our OpenStack envrionment.

Cheers,
/Jay

**Comment by cppforlife** [comment]
Closing. no activity. As suggested please try using bosh-init.
