### ISSUE TITLE
bosh_cli won't run if BOSH_USE_BUNDLER is true and bundler is not installed 

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh#1063]
bosh_cli has a dependency on the bundler gem if this environment variable is set, but the gemspec does not declare this dependency. bosh_cli should either declare the dependency, or provide a more graceful error message.

```
→ gem install bosh_cli
Fetching: little-plugger-1.1.4.gem (100%)
Successfully installed little-plugger-1.1.4
Fetching: logging-1.8.2.gem (100%)
Successfully installed logging-1.8.2
Fetching: semi_semantic-1.1.0.gem (100%)
Successfully installed semi_semantic-1.1.0
Fetching: bosh_common-1.3149.0.gem (100%)
Successfully installed bosh_common-1.3149.0
Fetching: bosh-template-1.3149.0.gem (100%)
Successfully installed bosh-template-1.3149.0
Fetching: cf-uaa-lib-3.2.5.gem (100%)
Successfully installed cf-uaa-lib-3.2.5
Fetching: json_pure-1.8.3.gem (100%)
Successfully installed json_pure-1.8.3
Fetching: highline-1.6.21.gem (100%)
Successfully installed highline-1.6.21
Fetching: progressbar-0.9.2.gem (100%)
Successfully installed progressbar-0.9.2
Fetching: httpclient-2.4.0.gem (100%)
Successfully installed httpclient-2.4.0
Fetching: terminal-table-1.4.5.gem (100%)
Successfully installed terminal-table-1.4.5
Fetching: aws-sdk-v1-1.60.2.gem (100%)
Successfully installed aws-sdk-v1-1.60.2
Fetching: aws-sdk-1.60.2.gem (100%)
Successfully installed aws-sdk-1.60.2
Fetching: blobstore_client-1.3149.0.gem (100%)
Successfully installed blobstore_client-1.3149.0
Fetching: net-scp-1.1.2.gem (100%)
Successfully installed net-scp-1.1.2
Fetching: netaddr-1.5.0.gem (100%)
Successfully installed netaddr-1.5.0
Fetching: sshkey-1.7.0.gem (100%)
Successfully installed sshkey-1.7.0
Fetching: bosh_cli-1.3149.0.gem (100%)
Successfully installed bosh_cli-1.3149.0
18 gems installed

→ bosh target

Optimizing gem configuration...

/Users/pivotal/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
    from /Users/pivotal/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3149.0/bin/optionally_run_with_bundler.rb:28:in `run'
    from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3149.0/bin/bosh:3:in `<top (required)>'
    from /Users/pivotal/.gem/ruby/2.1.6/bin/bosh:23:in `load'
    from /Users/pivotal/.gem/ruby/2.1.6/bin/bosh:23:in `<main>'
```

**Comment by charliewang0104** [comment]
I met a similar issue when running "generate-bosh-lite-dev-manifest" script to deploy CF. In the script, there is a line "export BOSH_USE_BUNDLER=true", bosh_cli can not be run after executing this line. The error on OSX 10.11.3 is -
WangYudeMacBook-Pro:scripts wangyu$ ./generate-bosh-lite-dev-manifest.test 
/Users/wangyu/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/wangyu/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by dpb587-pivotal** [comment]
Closing - we're not planning on making any further changes to the ruby CLI in favor of focusing development on [bosh-cli](https://github.com/cloudfoundry/bosh-cli). Please give that a try and feel free to open issues or feedback in that repo.
