### ISSUE TITLE
BOSH gets confused with Instances with multiple manual networks

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1129]
## Steps to reproduce
- Create two internal networks, in my case their names are `default` and `compilation`
- Configure the networks as `manual`. Here my snippet from the deployment manifest

```
networks:
    - name: default
      type: manual
      subnets:
        - range: 10.231.18.0/26
          gateway: 10.231.18.1
          reserved: [10.231.18.40,10.231.18.10]
          static: [10.231.18.11-10.231.18.29]
          cloud_properties: {net_id: d4e4416b-9163-4bc2-a9ae-5c722343acf2}
    - name: compilation
      type: manual
      subnets:
        - range: 10.1.1.0/29
          gateway: 10.1.1.1
          reserved: [10.1.1.2]
          cloud_properties: {net_id: 7e6a802a-0755-4f98-ae81-cfe664bef51f}
```
- Deploy a VM in both of these networks

```
  - name: dummy_with_properties_z1
     template: dummy_with_properties
     instances: 1
     resource_pool: small_pool
     networks:
       - name: default
         default: [dns, gateway]
       - name: compilation
```

That actually works. However, `bosh instances` shows the same IP twice for that instance, in this case `10.231.18.3`.

If you then e.g. scale up from `1` to `2` instances and deploy again, the deployment fails: `Failed to reserve IP '10.231.18.3' for 'default': already reserved`
## Stacktrace and Logs

IP configuration on the machine is actually correct

``` bash
root@0a660247-d5c3-4aef-9916-eb3221ce9015:/var/vcap/bosh# ip address show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:54:98:f5 brd ff:ff:ff:ff:ff:ff
    inet 10.231.18.3/26 brd 10.231.18.63 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe54:98f5/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:92:53:11 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.3/29 brd 10.1.1.7 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe92:5311/64 scope link
       valid_lft forever preferred_lft forever
```

Agent settings.json. Here, the network configuration is _correct_:

```
root@0a660247-d5c3-4aef-9916-eb3221ce9015:/var/vcap/bosh# cat settings.json | jq .
{
  "trusted_certs": "",
  "agent_id": "0a660247-d5c3-4aef-9916-eb3221ce9015",
  "blobstore": {
   <redacted>
    },
    "provider": "s3"
  },
  "disks": {
    "raw_ephemeral": null,
    "persistent": {},
    "ephemeral": null,
    "system": "/dev/sda"
  },
  "env": {
    "persistent_disk_fs": "",
    "bosh": {
      "keep_root_password": false,
      "password": ""
    }
  },
  "networks": {
    "public": {
      "preconfigured": false,
      "mac": "",
      "type": "vip",
      "ip": <redacted>,
      "netmask": "",
      "gateway": "",
      "resolved": false,
      "use_dhcp": true,
      "default": null,
      "dns": null
    },
    "default": {
      "preconfigured": false,
      "mac": "",
      "type": "",
      "ip": "10.231.18.3",
      "netmask": "255.255.255.192",
      "gateway": "10.231.18.1",
      "resolved": false,
      "use_dhcp": true,
      "default": [
        "dns",
        "gateway"
      ],
      "dns": null
    },
    "compilation": {
      "preconfigured": false,
      "mac": "",
      "type": "",
      "ip": "10.1.1.3",
      "netmask": "255.255.255.248",
      "gateway": "10.1.1.1",
      "resolved": false,
      "use_dhcp": true,
      "default": null,
      "dns": null
    }
  },
  "ntp": [
    "0.pool.ntp.org",
    "1.pool.ntp.org"
  ],
  "mbus": "nats://<redacted>@10.231.18.10:4222",
  "vm": {
    "name": "vm-7f17bd6c-a464-4cf8-a356-84b654a28bea"
  }
}
```

Agent settings.json on the VM. Here, the network configuration is _wrong_. The same IP is shown for both networks:

```
root@0a660247-d5c3-4aef-9916-eb3221ce9015:/var/vcap/bosh# cat spec.json | jq .
{
  "rendered_templates_archive": {
    "blobstore_id": "7f1cdd04-43ad-42d2-9cfe-6b70dd100cae",
    "sha1": "a8ba0641dc77af9df486ba639d5effb2ac8ad282"
  },
  "persistent_disk": 0,
  "id": "297abc9a-c569-475c-a956-8ee2710df56d",
  "properties": {
    "logging": {
      "max_log_file_size": ""
    }
  },
  "job": {
    "templates": [
      {
        "blobstore_id": "a6e6c55d-2a0b-404e-a4d7-dcac12267575",
        "sha1": "4a54785e7ba1c6707d9400322dbeb5a1b9215d28",
        "version": "4130de1cabfe9c169f0209c195ce7533fb5e5e7f",
        "name": "dummy_with_properties"
      }
    ],
    "blobstore_id": "a6e6c55d-2a0b-404e-a4d7-dcac12267575",
    "sha1": "4a54785e7ba1c6707d9400322dbeb5a1b9215d28",
    "version": "4130de1cabfe9c169f0209c195ce7533fb5e5e7f",
    "template": "dummy_with_properties",
    "release": "",
    "name": "dummy_with_properties_z1"
  },
  "packages": {},
  "configuration_hash": "ec8ed1cd7afe6f502a540c63dbea83951891b318",
  "networks": {
    "public": {
      "type": "vip",
      "ip": <redacted>,
      "cloud_properties": {}
    },
    "default": {
      "netmask": "255.255.255.192",
      "ip": "10.231.18.3",
      "gateway": "10.231.18.1",
      "default": [
        "dns",
        "gateway"
      ],
      "cloud_properties": {
        "net_id": "d4e4416b-9163-4bc2-a9ae-5c722343acf2"
      }
    },
    "compilation": {
      "netmask": "255.255.255.192",
      "ip": "10.231.18.3",
      "gateway": "10.231.18.1",
      "cloud_properties": {
        "net_id": "7e6a802a-0755-4f98-ae81-cfe664bef51f"
      }
    }
  },
  "resource_pool": null,
  "deployment": "dummy",
  "index": 0
}
```

On the second deployment, Director gives you the following stacktrace

```
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: Job instance states: {}, found: , state: started
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: (0.000125s) SELECT NULL
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: (0.000162s) SELECT * FROM "ip_addresses" WHERE ("ip_addresses"."instance_id" = 19)
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Creating instance network reservations from agent state for instance 'dummy_with_properties_z1/0 (297abc9a-c569-475c-a956-8ee2710df56d)'
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Registering existing reservation with  IP '10.231.18.3' for instance 'dummy_with_properties_z1/0 (297abc9a-c569-475c-a956-8ee2710df56d)' on network 'compilation'
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Reserving existing ips
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Marking existing IP 10.231.18.3 as reserved
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Reserving ip '10.231.18.3' for default
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Found subnet with azs '' for 10.231.18.3. Reserved as dynamic network reservation.
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Registering existing reservation with  IP '10.231.18.3' for instance 'dummy_with_properties_z1/0 (297abc9a-c569-475c-a956-8ee2710df56d)' on network 'default'
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Reserving existing ips
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: [network-configuration] Marking existing IP 10.231.18.3 as reserved
E, [2016-02-09 14:42:04 #8516] [task:51] ERROR -- DirectorJobRunner: [network-configuration] Failed to reserve IP '10.231.18.3' for 'default': already reserved
D, [2016-02-09 14:42:04 #8516] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:dummy
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:dummy
I, [2016-02-09 14:42:04 #8516] [task:51]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2016-02-09 14:42:04 #8516] [task:51] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"22853f19-4b01-4680-a9ba-125a25b8df38","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'dummy' against Director '111ba3fb-23e0-4307-836c-db01a340ffec': #<Bosh::Director::NetworkReservationAlreadyInUse: Failed to reserve IP '10.231.18.3' for 'default': already reserved>","created_at":1455028924}
E, [2016-02-09 14:42:04 #8516] [task:51] ERROR -- DirectorJobRunner: Failed to reserve IP '10.231.18.3' for 'default': already reserved
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/ip_provider/in_memory_ip_repo.rb:61:in `add_ip'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/ip_provider/in_memory_ip_repo.rb:27:in `block in add'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/ip_provider/in_memory_ip_repo.rb:26:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/ip_provider/in_memory_ip_repo.rb:26:in `add'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/ip_provider/ip_provider.rb:106:in `reserve_manual'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/ip_provider/ip_provider.rb:99:in `reserve_existing_ips'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/instance_network_reservations.rb:66:in `add_existing'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/instance_network_reservations.rb:12:in `block in create_from_state'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/instance_network_reservations.rb:11:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/instance_network_reservations.rb:11:in `create_from_state'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/network_reservation_repository.rb:14:in `fetch_network_reservations'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/instance_repository.rb:17:in `fetch_existing'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/instance_plan_factory.rb:30:in `desired_existing_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/placement_planner/availability_zone_picker.rb:64:in `block in desired_existing_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/placement_planner/availability_zone_picker.rb:63:in `map'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/placement_planner/availability_zone_picker.rb:63:in `desired_existing_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/placement_planner/availability_zone_picker.rb:24:in `place_and_match_in'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/placement_planner/plan.rb:31:in `assign_zones'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/placement_planner/plan.rb:14:in `create_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/instance_planner.rb:14:in `plan_job_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/assembler.rb:34:in `block in bind_models'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/assembler.rb:31:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/assembler.rb:31:in `bind_models'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/deployment_plan/planner.rb:112:in `bind_models'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3191.0/lib/bosh/director/jobs/update_deployment.rb:43:in `block (2 levels) in perform'
```

**Comment by ronakbanka** [comment]
@voelzmo we are facing similar issue , agent spec on director inside director db is correct but bosh agent confuses while reporting back to the director . 

If you restart the agent on vm itself , ip out of 2 nics it randomly reports duplicated ip.

For now we are using kind of old version of stemcell 2978 (works fine ),but when tried with version 3033 we saw this thing. trying to narrow down what can be the issue.

**Comment by voelzmo** [comment]
One more piece of information: The settings in the registry actually look good, the IP is only set for one of the networks: (note that I recreated the deployment in the meanwhile with one network DHCP and one network static IP, but the effect is the same)

```
"settings": "{\"vm\":{\"name\":\"vm-b343b63d-cfba-4926-a112-ade6bd5b8681\"},\"agent_id\":\"3fadcdd9-7cd6-4c49-b710-31a82d8377db\",\"networks\":{\"default\":{\"ip\":\"10.231.18.11\",\"netmask\":\"255.255.255.192\",\"cloud_properties\":{\"net_id\":\"d4e4416b-9163-4bc2-a9ae-5c722343acf2\"},\"default\":[\"dns\",\"gateway\"],\"gateway\":\"10.231.18.1\",\"use_dhcp\":true},\"compilation\":{\"type\":\"dynamic\",\"cloud_properties\":{\"net_id\":\"7e6a802a-0755-4f98-ae81-cfe664bef51f\"},\"use_dhcp\":true}},\"disks\":{\"system\":\"/dev/sda\",\"persistent\":{},\"ephemeral\":null},\"env\":{},\"ntp\":[\"0.pool.ntp.org\",\"1.pool.ntp.org\"],\"blobstore\":{\"provider\":\"s3\",\"options\":{<redacted>}},\"mbus\":\"nats://nats:nats-password@10.231.18.40:4222\"}",
  "status": "ok"
}
```

**Comment by tylerschultz** [comment]
Hallo Marco, Wie geht’s?,

I think I've found the issue. It looks like the PopulateDHCPNetworks function is very stompy: https://github.com/cloudfoundry/bosh-agent/blob/master/agent/applier/applyspec/concrete_v1_service.go

The challenge is mapping the given ip address back to the correct bosh network hash. We'll have to think about this one.

**Comment by tylerschultz** [comment]
No, that was not the problem. The problem is in settings/service.go. GetSettings() overwrites each network to the resolved network, which is always the DefaultNetwork *if* the network is DHCP.

**Comment by voelzmo** [comment]
Hallo Tyler, mir geht es gut, danke. Wie geht es dir? Ich hoffe, du übst fleißig dein Deutsch?

I guess we can adapt the CPI to put MACs in the agent settings. However, I still have the feeling that your description of `GetSettings()` seems a little weird. Having two networks using DHCP without defining a MAC address works (because the agent doesn't have to configure them) on the VM, as the output of `ip address show` shows. The agent is just confused what to report, which seems weird.

So are you looking into fixing what the agent reports? I can take care of the OpenStack CPI network side of things.

**Comment by tylerschultz** [comment]
You're absolutely right, the agent will need work as well. It'd need a coordinated fix. I'm going to leave it up to DK as to how this gets prioritized. A PR would probably work too. :-)

**Comment by voelzmo** [comment]
I guess the problem in the agent is right here https://github.com/cloudfoundry/bosh-agent/blob/1dca3244702c18bf2c36483c529d4e7b3fb92b2e/settings/service.go#L107
I'll have a look and figure out what we can do.

**Comment by ronakbanka** [comment]
@cppforlife @voelzmo Any update when development on above added story will start or is it already under development?

**Comment by voelzmo** [comment]
@ronakbanka We have released v24 of the OpenStack CPI which enables you to [use multiple networks](http://bosh.io/docs/openstack-multiple-networks.html). However, there are a few limitations to this, meaning that you can only use this with `use_dhcp: false` for now.

This will change, once we make the necessary agent chages in https://www.pivotaltracker.com/story/show/114099719 but I don't think we'll come to that very soon.

**Comment by poblin-orange** [comment]
@voelzmo 
Im using multiple static NIC with the following combo:
stemcell-version: 3363.14
bosh-version: 260.4
bosh-openstack-cpi-release-version: 31

Im experiencing the same type of issue mentioned here. Despite setting the default gateway on private network, seems bosh ssh randomly chooses the secondary NIC ip and fails.

```
+-------------------------------------------------------+---------+----+---------+----------------+
| Instance                                              | State   | AZ | VM Type | IPs            |
+-------------------------------------------------------+---------+----+---------+----------------+
| to-intranet/0 (335de3c9-9c77-427b-bf39-c7ffaaa7273a)* | running | z1 | small   | 192.168.99.34  |
|                                                       |         |    |         | 10.228.175.126 |
+-------------------------------------------------------+---------+----+---------+----------------+

```

I see this issue is still opened. Is there a stemcell correction or workaround we could apply ?
thks

**Comment by voelzmo** [comment]
@poblin-orange there is no fix available. On OpenStack, your only options to use multiple NICs is the way described here: http://bosh.io/docs/openstack-multiple-networks.html
