### ISSUE TITLE
scan_and_fix in state `done` although resurrection unsuccessful

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1135]
**Using BOSH v243**

Seems like an error during resurrection is not properly reflected in the Director task. We had the resurrector kick in because of a missing VM, the Director started a `scan_and_fix` that ended with this stacktrace, because the IP was already taken:

```
E, [2016-02-16 12:31:03 #625] [task:5871] ERROR -- DirectorJobRunner: error creating vm: OpenStack API Bad Request (Fixed IP address 10.1.1.70 is already in use on instance f87a5081-673a-4dd7-a909-d33cb51396f7.). Check task debug log for details.
E, [2016-02-16 12:31:03 #625] [task:5871] ERROR -- DirectorJobRunner: Error resolving problem `1798': OpenStack API Bad Request (Fixed IP address 10.1.1.70 is already in use on instance f87a5081-673a-4dd7-a909-d33cb51396f7.). Check task debug log for details.
E, [2016-02-16 12:31:03 #625] [task:5871] ERROR -- DirectorJobRunner: /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:118:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:88:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:51:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:119:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:50:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/cloudcheck_helper.rb:80:in `recreate_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_handlers/missing_vm.rb:22:in `block (2 levels) in <class:MissingVM>'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_handlers/base.rb:83:in `instance_eval'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_handlers/base.rb:83:in `apply_resolution'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_resolver.rb:61:in `block in apply_resolution'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_resolver.rb:23:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_resolver.rb:21:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_resolver.rb:60:in `apply_resolution'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_resolver.rb:42:in `block in apply_resolutions'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:152:in `block in each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:525:in `block (2 levels) in fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:720:in `block in yield_hash_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:714:in `times'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:714:in `yield_hash_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:525:in `block in fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:134:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:413:in `_execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:425:in `check_database_errors'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:801:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:525:in `fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:152:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/problem_resolver.rb:33:in `apply_resolutions'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/jobs/cloud_check/scan_and_fix.rb:37:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/jobs/cloud_check/scan_and_fix.rb:30:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/bin/bosh-director-worker:75:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
D, [2016-02-16 12:31:03 #625] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-02-16 12:31:03 #625] [task:5871] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:cf
D, [2016-02-16 12:31:03 #625] [task:5871] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:cf
I, [2016-02-16 12:31:03 #625] [task:5871]  INFO -- DirectorJobRunner: Done
D, [2016-02-16 12:31:03 #625] [task:5871] DEBUG -- DirectorJobRunner: (0.000505s) SELECT NULL
D, [2016-02-16 12:31:03 #625] [task:5871] DEBUG -- DirectorJobRunner: (0.000074s) BEGIN
D, [2016-02-16 12:31:03 #625] [task:5871] DEBUG -- DirectorJobRunner: (0.000308s) UPDATE "tasks" SET "state" = 'done', "timestamp" = '2016-02-16 12:31:03.177979+0000', "description" = 'scan and fix', "result" = 'scan and fix complete', "output" = '/var/vcap/store/director/tasks/5871', "checkpoint_time" = '2016-02-16 12:30:30.398472+0000', "type" = 'cck_scan_and_fix', "username" = 'admin' WHERE ("id" = 5871)
D, [2016-02-16 12:31:03 #625] [task:5871] DEBUG -- DirectorJobRunner: (0.001551s) COMMIT
I, [2016-02-16 12:31:03 #625] []  INFO -- DirectorJobRunner: Task took 32.790867576 seconds to process.

Task 5871 done
```

However, the task is in state `done`, not `error`. The Health Monitor didn't log anything about a failed `scan_and_fix` and happily removed the VM from the DB.

What I would have expected is an error just like if you deploy the release again:
```
D, [2016-02-16 12:45:48 #855] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: OpenStack API Bad Request (Fixed IP address 10.1.1.70 is already in use on instance f87a5081-673a-4dd7-a909-d33cb51396f7.). Check task debug log for details. - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:118:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:88:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:51:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:119:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:50:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:30:in `block (5 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:27:in `block (4 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:26:in `block (3 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-02-16 12:45:48 #855] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: (0.000356s) SELECT NULL
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: (0.000785s) SELECT "stemcells".* FROM "stemcells" INNER JOIN "deployments_stemcells" ON (("deployments_stemcells"."stemcell_id" = "stemcells"."id") AND ("deployments_stemcells"."deployment_id" = 2))
D, [2016-02-16 12:45:48 #855] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:cf
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:cf
I, [2016-02-16 12:45:48 #855] [task:5877]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"6a44f36b-2586-4cea-bd48-a780ce288e38","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'cf' against Director 'b320ad7d-16d8-41b5-8dbf-420ef81820c2': #<Bosh::Clouds::CloudError: OpenStack API Bad Request (Fixed IP address 10.1.1.70 is already in use on instance f87a5081-673a-4dd7-a909-d33cb51396f7.). Check task debug log for details.>","created_at":1455626748}
E, [2016-02-16 12:45:48 #855] [task:5877] ERROR -- DirectorJobRunner: OpenStack API Bad Request (Fixed IP address 10.1.1.70 is already in use on instance f87a5081-673a-4dd7-a909-d33cb51396f7.). Check task debug log for details.
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:118:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:88:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3167.0/lib/cloud/external_cpi.rb:51:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:119:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:50:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:30:in `block (5 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:27:in `block (4 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3167.0/lib/bosh/director/vm_creator.rb:26:in `block (3 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3167.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: (0.000122s) SELECT NULL
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: (0.000093s) BEGIN
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: (0.000415s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2016-02-16 12:45:48.393953+0000', "description" = 'create deployment', "result" = 'OpenStack API Bad Request (Fixed IP address 10.1.1.70 is already in use on instance f87a5081-673a-4dd7-a909-d33cb51396f7.)....', "output" = '/var/vcap/store/director/tasks/5877', "checkpoint_time" = '2016-02-16 12:35:47.407852+0000', "type" = 'update_deployment', "username" = 'admin' WHERE ("id" = 5877)
D, [2016-02-16 12:45:48 #855] [task:5877] DEBUG -- DirectorJobRunner: (0.001179s) COMMIT
I, [2016-02-16 12:45:48 #855] []  INFO -- DirectorJobRunner: Task took 10 minutes 0.993022791000044 seconds to process.

Task 5877 error
```

Which ends in state `error` and I also get logs in the Health Monitor quoting the above `"result" = 'OpenStack API Bad Request (Fixed IP address 10.1.1.70 is already in use on instance f87a5081-673a-4dd7-a909-d33cb51396f7.)`

**Comment by voelzmo** [comment]
Alright, I added a story for this: https://www.pivotaltracker.com/story/show/114092983
We'll probably start it next week.

**Comment by beyhan** [comment]
Pull request #1147 fixes this issue.

**Comment by tomoe** [comment]
I found that this has been merged and included in the release:
https://github.com/cloudfoundry/bosh/releases/tag/stable-3213

What is the policy for closing an issue?

**Comment by voelzmo** [comment]
Thanks for the reminder @tomoe. Change has been merged, closing the issue.
