### ISSUE TITLE
Bosh logs and bosh errrands should not write in the blobstore to upload logs

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/bosh#1150]
## Context

We have setup S3 blobstore backend. 

For security, we consider that only bosh director should write in the blobstore, meanwhile the bosh agents should only be able to fetch objects.

We run bosh 255.8
### Error

But we found out that the agents try to write to the blob store:
- when running an errand with the option of download logs (see below for details)
- when running `bosh logs <job>`

and the operation fails due lack of permissions of the agent to upload to the blob store.
### Expected behaviour

It does not seem safe that the agent write the logs in the same store than we keep all the packages and binaries. 

If this pattern is required, I suggest these alternatives:
- allow define an optional alternate blobstores for the logs and other uploads from the agents.
- add a prefix to all the logs uploaded from the agents, so that we can define a policy allowing that prefix.
- more complex: Stream the logs binaries to the client from the agent.

I consider the easiest and more sensible approach is the first option
### Error downloading errand logs

```
Logged in as `admin'
Target set to `my-bosh'
Deployment set to `/tmp/build/d2211d8c-b8d5-4dba-5e14-f1c249a42952/cf-manifest/cf-manifest.yml'
Acting as user 'admin' on deployment 'hector' on 'my-bosh'

Director task 18
  Started preparing deployment > Preparing deployment. Done (00:00:02)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started creating missing vms > smoke_tests/0 (1a48481c-a0fe-4b87-9ddb-3d4f8c133468). Done (00:02:03)

  Started updating job smoke_tests > smoke_tests/0 (1a48481c-a0fe-4b87-9ddb-3d4f8c133468). Done (00:00:25)

  Started running errand > smoke_tests/0. Done (00:03:06)

  Started fetching logs for smoke_tests/1a48481c-a0fe-4b87-9ddb-3d4f8c133468 (0) > Finding and packing log files. Failed: Action Failed get_task: Task 02da6898-b12e-43cd-7fdc-a9d8acb2c14e result: Create file on blobstore: Creating blob in inner blobstore: Making put command: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json put /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir097292564 e8078dfe-fda2-4e0a-49ad-fe69b0374b09', stdout: '', stderr: '2016/02/25 17:22:43 performing operation put: AccessDenied: Access Denied
    status code: 403, request id: 
': exit status 1 (00:00:01)

  Started deleting errand instances smoke_tests > smoke_tests/0 (1a48481c-a0fe-4b87-9ddb-3d4f8c133468). Done (00:01:09)

Error 450001: Action Failed get_task: Task 02da6898-b12e-43cd-7fdc-a9d8acb2c14e result: Create file on blobstore: Creating blob in inner blobstore: Making put command: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json put /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir097292564 e8078dfe-fda2-4e0a-49ad-fe69b0374b09', stdout: '', stderr: '2016/02/25 17:22:43 performing operation put: AccessDenied: Access Denied
    status code: 403, request id: 
': exit status 1

Task 18 error

Errand `smoke_tests' did not complete

For a more detailed error report, run: bosh task 18 --debug
```

And the stacktrace:

```
E, [2016-02-25 17:23:53 #15097] [task:18] ERROR -- DirectorJobRunner: Action Failed get_task: Task 02da6898-b12e-43cd-7fdc-a9d8acb2c14e result: Create file on blobstore: Creating blob in inner blobstore: Making put command: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json put /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir097292564 e8078dfe-fda2-4e0a-49ad-fe69b0374b09', stdout: '', stderr: '2016/02/25 17:22:43 performing operation put: AccessDenied: Access Denied
    status code: 403, request id: 
': exit status 1
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/agent_client.rb:217:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/agent_client.rb:272:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/agent_client.rb:52:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/agent_client.rb:311:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/agent_client.rb:141:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/agent_client.rb:285:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/agent_client.rb:88:in `fetch_logs'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/logs_fetcher.rb:26:in `block in fetch'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/logs_fetcher.rb:25:in `fetch'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/errand/runner.rb:41:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/jobs/run_errand.rb:74:in `block (2 levels) in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/jobs/run_errand.rb:90:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/jobs/run_errand.rb:90:in `with_updated_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/jobs/run_errand.rb:72:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/jobs/run_errand.rb:28:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3192.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/bin/bosh-director-worker:75:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
```
### Error running `bosh logs`

```
/tmp/build/e55deab7 # bosh logs consul_z1 0
Acting as user 'admin' on deployment 'graham-apr' on 'my-bosh'
​
Director task 69
  Started fetching logs for consul_z1/2a98060c-252e-4431-8ac4-53037df4f2ac (0) > Finding and packing log files. Failed: Action Failed get_task: Task 7862e40c-3d9a-4215-5fad-d976cfcd6044 result: Create file on blobstore: Creating blob in inner blobstore: Making put command: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json put /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir231183136 9213dd58-f042-498f-4327-b6e41d7c8368', stdout: '', stderr: '2016/05/05 07:50:36 performing operation put: AccessDenied: Access Denied
    status code: 403, request id: 
': exit status 1 (00:00:04)
​
Error 450001: Action Failed get_task: Task 7862e40c-3d9a-4215-5fad-d976cfcd6044 result: Create file on blobstore: Creating blob in inner blobstore: Making put command: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json put /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir231183136 9213dd58-f042-498f-4327-b6e41d7c8368', stdout: '', stderr: '2016/05/05 07:50:36 performing operation put: AccessDenied: Access Denied
    status code: 403, request id: 
': exit status 1
​
Task 69 error
Error retrieving logs
```

Stack trace:

```
D, [2016-05-05 07:50:37 #19276] [] DEBUG -- DirectorJobRunner: RECEIVED: director.e3d51cc0-baa6-4ce5-b794-5d9cc3fbfbd4.e4ede96c-7b77-455b-ba2b-29432646fe38 {"exception":{"message":"Action Failed get_task: Task 7862e40c-3d9a-4215-5fad-d976cfcd6044 result: Create file on blobstore: Creating blob in inner blobstore: Making put command: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json put /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir231183136 9213dd58-f042-498f-4327-b6e41d7c8368', stdout: '', stderr: '2016/05/05 07:50:36 performing operation put: AccessDenied: Access Denied\n\tstatus code: 403, request id: \n': exit status 1"}}
E, [2016-05-05 07:50:37 #19276] [task:69] ERROR -- DirectorJobRunner: Action Failed get_task: Task 7862e40c-3d9a-4215-5fad-d976cfcd6044 result: Create file on blobstore: Creating blob in inner blobstore: Making put command: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json put /var/vcap/data/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir231183136 9213dd58-f042-498f-4327-b6e41d7c8368', stdout: '', stderr: '2016/05/05 07:50:36 performing operation put: AccessDenied: Access Denied
    status code: 403, request id: 
': exit status 1
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/agent_client.rb:217:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/agent_client.rb:272:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/agent_client.rb:52:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/agent_client.rb:311:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/agent_client.rb:141:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/agent_client.rb:285:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/agent_client.rb:88:in `fetch_logs'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/logs_fetcher.rb:26:in `block in fetch'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/logs_fetcher.rb:25:in `fetch'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/jobs/fetch_logs.rb:26:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/bin/bosh-director-worker:75:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
D, [2016-05-05 07:50:37 #19276] [task:69] DEBUG -- DirectorJobRunner: (0.001095s) SELECT NULL
D, [2016-05-05 07:50:37 #19276] [task:69] DEBUG -- DirectorJobRunner: (0.000769s) BEGIN
```

**Comment by keymon** [comment]
I updated this issue, with a better description and stating the fact that it also affects `bosh logs`. 

Please update your stories if required.

**Comment by aeijdenberg** [comment]
I'll 3rd it. We're also fairly keen to not let all agents have permission to write to the blobstore...
