### ISSUE TITLE
bosh scp error message should reveal the root cause for an error

### ISSUE THREAD

**Issue by suhlig** [cloudfoundry/bosh#1171]
A rather confusing error message similar to #885 comes up when the file to be `bosh scp --download`-ed doesn't exist.

Maybe the error message could reveal what the actual cause is?

With a typo in the file name:

```
$ bosh scp bits_service_z1/0 --download /var/vcap/data/sys/log/bits-service/bits-service.lo /tmp
Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'
Executing file operations on job bits_service_z1
Target deployment is `cf-warden'
...
Task 78 queued
/Users/cf/.gem/ruby/2.2.4/gems/net-scp-1.1.2/lib/net/scp.rb:359:in `block (3 levels) in start_command': SCP did not finish successfully (1) (Net::SCP::Error)
        from /Users/cf/.gem/ruby/2.2.4/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:591:in `call'
        ...
        from /Users/cf/.gem/ruby/2.2.4/gems/net-scp-1.1.2/lib/net/scp.rb:316:in `download!'
        from /Users/cf/.gem/ruby/2.2.4/gems/bosh_cli-1.3215.0/lib/cli/commands/ssh.rb:220:in `block (3 levels) in perform_operation'
        from /Users/cf/.gem/ruby/2.2.4/gems/bosh_cli-1.3215.0/lib/cli/commands/ssh.rb:247:in `block in with_ssh'
        from /Users/cf/.gem/ruby/2.2.4/gems/net-ssh-2.9.2/lib/net/ssh.rb:215:in `start'
        from /Users/cf/.gem/ruby/2.2.4/gems/bosh_cli-1.3215.0/lib/cli/commands/ssh.rb:247:in `with_ssh'
        ...
        from /Users/cf/.gem/ruby/2.2.4/gems/bosh_cli-1.3215.0/lib/cli/commands/ssh.rb:65:in `scp'
        from /Users/cf/.gem/ruby/2.2.4/gems/bosh_cli-1.3215.0/lib/cli/command_handler.rb:57:in `run'
        from /Users/cf/.gem/ruby/2.2.4/gems/bosh_cli-1.3215.0/lib/cli/runner.rb:59:in `run'
        from /Users/cf/.gem/ruby/2.2.4/gems/bosh_cli-1.3215.0/bin/bosh:19:in `<top (required)>'
        from /Users/cf/.gem/ruby/2.2.4/bin/bosh:22:in `load'
        from /Users/cf/.gem/ruby/2.2.4/bin/bosh:22:in `<main>'
```

Without the correct file name:

```
$ bosh scp bits_service_z1/0 --download /var/vcap/data/sys/log/bits-service/bits-service.log /tmp
Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'
Executing file operations on job bits_service_z1
Target deployment is `cf-warden'
...
Downloaded file to /tmp/bits-service.log.bits_service_z1.
...
$ bosh -v
BOSH 1.3215.0
$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin14]
```

**Comment by tjvman** [comment]
Closing - Ruby CLI has been frozen in favor of the [new go CLI](https://github.com/cloudfoundry/bosh-cli). If this issue crops up when using the new CLI, feel free to open an issue in that repo.
