### ISSUE TITLE
Problem with deploying bosh director to OpenStack

### ISSUE THREAD

**Issue by Infra-Red** [cloudfoundry/bosh#1218]
Hello!

I was trying to update my BOSH director to latest 255.9 version.
`bosh-init deploy` command fails during update process:

```
Compiling package 'bosh_openstack_cpi/3a41d45536a57cea65bf8a114cfcd1f0a035639e'... Finished (00:01:33)
  Updating instance 'bosh-dev/0'... Finished (00:00:30)
  Waiting for instance 'bosh-dev/0' to be running... Failed (00:05:03)
Failed deploying (00:27:23)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Received non-running job state: 'failing'
```

Here some error messages from director logs:

```
/var/vcap/data/sys/log/director$ tail -f error.log
2016/04/16 09:13:51 [error] 8199#0: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /info HTTP/1.1", upstream: "http://127.0.0.1:25556/info", host: "127.0.0.1:25555"
```

```
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/extensions/migration.rb:674:in `get_applied_migrations': Applied migration files not in file system: 20160329201256_set_instances_with_nil_serial_to_false.rb, 20160331225404_backfill_stemcell_os.rb (Sequel::Migrator::Error)
        from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/extensions/migration.rb:630:in `initialize'
        from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.4.0/bin/bosh-director-migrate:36:in `new'
        from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.4.0/bin/bosh-director-migrate:36:in `migrate'
        from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.4.0/bin/bosh-director-migrate:41:in `<top (required)>'
        from /var/vcap/packages/director/bin/bosh-director-migrate:16:in `load'
        from /var/vcap/packages/director/bin/bosh-director-migrate:16:in `<main>'
```

I believe that this is some issue with database migrations in BOSH 255.9 release.

**Comment by allomov** [comment]
Hey.

I've reproduced this error on my environment. The interesting thing is that postgres database already has registered migration from `20160329201256_set_instances_with_nil_serial_to_false.rb` file that doesn't exist in `stable-3125.4`:
```
root@b2485b68-2948-4565-5b8e-5aaeaebc2c4c:~# /var/vcap/packages/postgres/bin/psql -U postgres -d bosh -c "select * from schema_migrations;" | grep 20160329201256
 20160329201256_set_instances_with_nil_serial_to_false.rb
```

**Comment by allomov** [comment]
I've migrated back to `255.8` (must be tag `stable-3125.3`) and it appeared that it contains missing migrations:
```
root@b881c74d-78d2-43c9-5b3d-5cc9a7eabf5c:/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/db/migrations/director# ls -al | grep 20160329201256
-rw-r--r-- 1 root root  446 Apr 16 14:31 20160329201256_set_instances_with_nil_serial_to_false.rb
```

**Comment by Infra-Red** [comment]
Git diff between 255.8 and 255.9:
`git diff 8f47e6a7 47cafe56 ` :

```
diff --git a/bosh-director/db/migrations/director/20160329201256_set_instances_with_nil_serial_to_false.rb b/bosh-director/db/migrations/director/20160329201256_set_instances_with_nil_serial_to_false.rb
deleted file mode 100644
index 4d2aa2d..0000000
--- a/bosh-director/db/migrations/director/20160329201256_set_instances_with_nil_serial_to_false.rb
+++ /dev/null
@@ -1,15 +0,0 @@
-require 'json'
-
-Sequel.migration do
-  up do
-    self[:instances].all do |instance|
-      unless instance[:spec_json].nil?
-        spec = JSON.parse(instance[:spec_json])
-        if !spec['update'].nil? && spec['update'].has_key?('serial') && spec['update']['serial'].nil?
-          spec['update']['serial'] = false
-          self[:instances].where(id: instance[:id]).update(spec_json: JSON.generate(spec))
-        end
-      end
-    end
-  end
-end
```

```
diff --git a/bosh-director/db/migrations/director/20160331225404_backfill_stemcell_os.rb b/bosh-director/db/migrations/director/20160331225404_backfill_stemcell_os.rb
deleted file mode 100644
index 2e7dd8f..0000000
--- a/bosh-director/db/migrations/director/20160331225404_backfill_stemcell_os.rb
+++ /dev/null
@@ -1,9 +0,0 @@
-Sequel.migration do
-  up do
-    self[:stemcells].all do |stemcell|
-      if stemcell[:operating_system].nil? || stemcell[:operating_system] == ''
-        self[:stemcells].where(id: stemcell[:id]).update(operating_system: stemcell[:name])
-      end
-    end
-  end
-end
```

**Comment by allomov** [comment]
Looks like `bosh.io` points to commit [8f47e6a7](https://github.com/cloudfoundry/bosh/tree/8f47e6a744df9310c793efdbe6c51811a11b44ff) for bosh version `255.8`, this commit contains missing [migration files](https://github.com/cloudfoundry/bosh/blob/8f47e6a744df9310c793efdbe6c51811a11b44ff/bosh-director/db/migrations/director/20160329201256_set_instances_with_nil_serial_to_false.rb).

At the same time bosh release version 255.9 in bosh.io points to [47cafe56](https://github.com/cloudfoundry/bosh/tree/47cafe56/), which doesn't have this files.

**Comment by cppforlife** [comment]
yup when stemcell was cut from master to update packages, it picked up older revision of bosh release since we have been producing bosh release from 255.x branch most recently. 255.9 bosh release should ve considered yanked and we will release 255.10 from 255.x branch.

**Comment by allomov** [comment]
@cppforlife thank you for quick update, it worked nicely for me.

@Infra-Red I think this issue can be closed.

**Comment by Infra-Red** [comment]
255.10 works fine for me too. @cppforlife @allomov thx for quick response.
