### ISSUE TITLE
DB inconsistency and Nil dereference 

### ISSUE THREAD

**Issue by tomoe** [cloudfoundry/bosh#1224]
This is caused by #1223
### bosh task  --debug log

```
Acting as user 'director' on 'p-bosh-f3b1fb3436882cdaa51b'

Director task 483
I, [2016-04-17T22:01:09.769108 #2545] [0x2b1a692e5334]  INFO -- TaskHelper: Director Version: 1.3146.10.0
I, [2016-04-17T22:01:09.769161 #2545] [0x2b1a692e5334]  INFO -- TaskHelper: Enqueuing task: 483
I, [2016-04-17 22:01:10 #10857] []  INFO -- DirectorJobRunner: Looking for task with task id 483
D, [2016-04-17 22:01:10 #10857] [] DEBUG -- DirectorJobRunner: (0.000630s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [] DEBUG -- DirectorJobRunner: (0.000621s) SELECT * FROM "tasks" WHERE "id" = 483
I, [2016-04-17 22:01:10 #10857] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>483, :state=>"queued", :timestamp=>2016-04-17 22:01:09 +0000, :description=>"scan and fix", :result=>nil, :output=>"/var/vcap/store/director/tasks/483", :checkpoint_time=>2016-04-17 22:01:09 +0000, :type=>"cck_scan_and_fix", :username=>"director"}>
I, [2016-04-17 22:01:10 #10857] []  INFO -- DirectorJobRunner: Starting task: 483
I, [2016-04-17 22:01:10 #10857] [task:483]  INFO -- DirectorJobRunner: Creating job
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000279s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000195s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.004402s) SELECT * FROM "deployments" WHERE ("name" = 'cf-88d0a479447294d3465e') LIMIT 1
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000213s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000375s) SELECT * FROM "tasks" WHERE "id" = 483
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000204s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000359s) SELECT * FROM "tasks" WHERE "id" = 483
I, [2016-04-17 22:01:10 #10857] [task:483]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>483, :state=>"queued", :timestamp=>2016-04-17 22:01:09 +0000, :description=>"scan and fix", :result=>nil, :output=>"/var/vcap/store/director/tasks/483", :checkpoint_time=>2016-04-17 22:01:09 +0000, :type=>"cck_scan_and_fix", :username=>"director"}>
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000302s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000143s) BEGIN
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000510s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2016-04-17 22:01:10.552908+0000', "description" = 'scan and fix', "result" = NULL, "output" = '/var/vcap/store/director/tasks/483', "checkpoint_time" = '2016-04-17 22:01:10.554094+0000', "type" = 'cck_scan_and_fix', "username" = 'director' WHERE ("id" = 483)
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.002576s) COMMIT
I, [2016-04-17 22:01:10 #10857] [task:483]  INFO -- DirectorJobRunner: Acquiring deployment lock on cf-88d0a479447294d3465e
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: Acquiring lock: lock:deployment:cf-88d0a479447294d3465e
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: Acquired lock: lock:deployment:cf-88d0a479447294d3465e
D, [2016-04-17 22:01:10 #10857] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf-88d0a479447294d3465e
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000731s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000451s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.003543s) SELECT * FROM "deployments" WHERE ("name" = 'cf-88d0a479447294d3465e') LIMIT 1
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.001602s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000230s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000474s) SELECT * FROM "instances" WHERE (("deployment_id" = 1) AND ("job" = 'diego_cell-partition-2a76849bdc38728d413f') AND ("index" = 2)) LIMIT 1
D, [2016-04-17 22:01:10 #10857] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:cf-88d0a479447294d3465e
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:cf-88d0a479447294d3465e
E, [2016-04-17 22:01:10 #10857] [task:483] ERROR -- DirectorJobRunner: undefined method `id' for nil:NilClass
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/problem_scanner/scanner.rb:27:in `block in reset'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/problem_scanner/scanner.rb:22:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/problem_scanner/scanner.rb:22:in `reset'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/jobs/cloud_check/scan_and_fix.rb:33:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/jobs/cloud_check/scan_and_fix.rb:30:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/job_runner.rb:102:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3146.10.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3146.10.0/bin/bosh-director-worker:76:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000204s) SELECT NULL
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000134s) BEGIN
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.000544s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2016-04-17 22:01:10.579340+0000', "description" = 'scan and fix', "result" = 'undefined method `id'' for nil:NilClass', "output" = '/var/vcap/store/director/tasks/483', "checkpoint_time" = '2016-04-17 22:01:10.554094+0000', "type" = 'cck_scan_and_fix', "username" = 'director' WHERE ("id" = 483)
D, [2016-04-17 22:01:10 #10857] [task:483] DEBUG -- DirectorJobRunner: (0.002158s) COMMIT
I, [2016-04-17 22:01:10 #10857] []  INFO -- DirectorJobRunner: Task took 0.045048555 seconds to process.

Task 483 error
```
### Relevant code snippet.

Because a VM got deleted due to #1223, instance was nil. There's no check for nil:

lib/bosh/director/problem_scanner/scanner.rb: 

```
      def reset(vms=nil)
        if vms
          vms.each do |job, index|
            instance = @instance_manager.find_by_name(@deployment.name, job, index)

            Models::DeploymentProblem.where(
              deployment: @deployment,
              resource_id: instance.vm.id,
              state: 'open'
            ).update(state: 'closed')

          end
        else
          Models::DeploymentProblem.where(
            state: 'open',
            deployment: @deployment
          ).update(state: 'closed')
        end
      end
```
### bosh tasks recent

This error is shown in the Result column. See task 483 and 498. 

```
ubuntu@ops-manager:~$ bosh tasks recent 40 --no-filter
Acting as user 'director' on 'p-bosh-f3b1fb3436882cdaa51b'

+-----+-------+-------------------------+-----------+-------------------------------+--------------------------------------------------------------------------------+
| #   | State | Timestamp               | User      | Description                   | Result                                                                         |
+-----+-------+-------------------------+-----------+-------------------------------+--------------------------------------------------------------------------------+
| 510 | done  | 2016-04-19 02:39:57 UTC | director  | scan cloud                    | scan complete                                                                  |
| 509 | done  | 2016-04-19 02:39:39 UTC | director  | retrieve vm-stats             |                                                                                |
| 508 | done  | 2016-04-19 02:39:31 UTC | director  | retrieve vm-stats             |                                                                                |
| 507 | done  | 2016-04-19 02:39:24 UTC | director  | retrieve vm-stats             |                                                                                |
| 506 | done  | 2016-04-19 02:38:56 UTC | director  | retrieve vm-stats             |                                                                                |
| 505 | done  | 2016-04-19 02:38:48 UTC | director  | retrieve vm-stats             |                                                                                |
| 504 | done  | 2016-04-19 02:11:18 UTC | director  | retrieve vm-stats             |                                                                                |
| 503 | done  | 2016-04-19 02:11:10 UTC | director  | retrieve vm-stats             |                                                                                |
| 502 | done  | 2016-04-18 07:00:02 UTC | scheduler | snapshot deployment           | snapshots of deployment 'p-redis-7610e87c76d5313640d8' created                 |
| 501 | done  | 2016-04-18 07:00:02 UTC | scheduler | snapshot deployment           | snapshots of deployment 'p-spring-cloud-services-b6214d29c5c183e56831' created |
| 500 | done  | 2016-04-18 07:00:02 UTC | scheduler | snapshot deployment           | snapshots of deployment 'p-rabbitmq-fe14dc176302b15a1999' created              |
| 499 | done  | 2016-04-18 07:00:02 UTC | scheduler | snapshot deployment           | snapshots of deployment 'p-mysql-fe95de2f4dadf3d2142c' created                 |
| 498 | error | 2016-04-18 07:00:02 UTC | scheduler | snapshot deployment           | undefined method `cid' for nil:NilClass                                        |
| 497 | done  | 2016-04-18 07:00:02 UTC | scheduler | scheduled SnapshotDeployments | Enqueued snapshot tasks [498, 499, 500, 501, 502]                              |
| 496 | done  | 2016-04-18 06:57:42 UTC | director  | retrieve vm-stats             |                                                                                |
| 495 | done  | 2016-04-18 06:00:03 UTC | scheduler | scheduled SnapshotSelf        |                                                                                |
| 494 | done  | 2016-04-18 05:25:59 UTC | director  | retrieve vm-stats             |                                                                                |
| 493 | done  | 2016-04-18 05:25:54 UTC | director  | retrieve vm-stats             |                                                                                |
| 492 | done  | 2016-04-18 05:25:49 UTC | director  | retrieve vm-stats             |                                                                                |
| 491 | done  | 2016-04-18 05:25:39 UTC | director  | retrieve vm-stats             |                                                                                |
| 490 | done  | 2016-04-18 05:25:34 UTC | director  | retrieve vm-stats             |                                                                                |
| 489 | done  | 2016-04-18 05:24:44 UTC | director  | retrieve vm-stats             |                                                                                |
| 488 | done  | 2016-04-18 05:24:34 UTC | director  | retrieve vm-stats             |                                                                                |
| 487 | done  | 2016-04-18 05:24:24 UTC | director  | retrieve vm-stats             |                                                                                |
| 486 | done  | 2016-04-18 05:24:14 UTC | director  | retrieve vm-stats             |                                                                                |
| 485 | done  | 2016-04-18 05:24:09 UTC | director  | retrieve vm-stats             |                                                                                |
| 484 | done  | 2016-04-18 05:08:43 UTC | director  | retrieve vm-stats             |                                                                                |
| 483 | error | 2016-04-17 22:01:10 UTC | director  | scan and fix                  | undefined method `id' for nil:NilClass                                         |
| 482 | done  | 2016-04-17 22:01:00 UTC | director  | scan and fix                  | scan and fix complete                                                          |
```

**Comment by cppforlife** [comment]
I believe this was fixed in later versions since that code is no longer present.

**Comment by tomoe** [comment]
Thanks @cppforlife 
I wonder if what the branching/release policy is. Do you maintain release branches and backport bug fixes?

**Comment by dpb587-pivotal** [comment]
Generally it's a rolling forward release policy for the open source side of things. The 3146.* series that you're using is a bit of a special case and used by internal products. As of 3177+, the underlying data structures were changed and refactored, dropping the intermediate VM references and may have fixed the issue.

I don't think the branching/release policy is officially documented anywhere. @cppforlife, perhaps that's something we can document, to help both internal and external expectations.

**Comment by tomoe** [comment]
Thanks @dpb587-pivotal for following up. 

> @cppforlife, perhaps that's something we can document, to help both internal and external expectations.

+1

**Comment by cppforlife** [comment]
i'll try to add something to bosh.io/docs.

**Comment by dpb587-pivotal** [comment]
:link: someone also raised the branching strategy question in [cloudfoundry#bosh](https://cloudfoundry.slack.com/messages/bosh/) on [2016-06-17T05:29Z](https://cloudfoundry.slack.com/archives/bosh/p1466054952000466)

**Comment by dpb587-pivotal** [comment]
Closing - should be fixed as of [v258](https://github.com/cloudfoundry/bosh/releases/tag/v258).
