### ISSUE TITLE
Updating director while task is running breaks deployment updates

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1233]
Okay, this is maybe a rare case, but this just happened on BOSH `v255.8`
- The Cloud Foundry `acceptance_tests` errand was running
- We updated the Director using `bosh-init deploy`

These are the last debug log lines from the task that ran the errand

```
D, [2016-04-20 10:57:02 #5650] [create_missing_vm(acceptance_tests/0 (fee1f1c3-62c2-4a42-9c88-2b1a08a458f8)/1)] DEBUG -- DirectorJobRunner: (0.000796s) UPDATE "instances" SET "vm_cid" = '5f6ce9b3-3e48-472f-9545-27fe8e8ae253', "agent_id" = 'af8885b2-cb6e-451d-9014-3bffe8af004c' WHERE ("id" = 1350)
D, [2016-04-20 10:57:02 #5650] [create_missing_vm(acceptance_tests/0 (fee1f1c3-62c2-4a42-9c88-2b1a08a458f8)/1)] DEBUG -- DirectorJobRunner: (0.018422s) COMMIT
D, [2016-04-20 10:57:02 #5650] [create_missing_vm(acceptance_tests/0 (fee1f1c3-62c2-4a42-9c88-2b1a08a458f8)/1)] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"set_vm_metadata","arguments":["5f6ce9b3-3e48-472f-9545-27fe8e8ae253",{"director":"bosh","deployment":"cf","job":"acceptance_tests","index":"0"}],"context":{"director_uuid":"3353a43b-ed61-413e-8332-4c59c82f681e"}} with command: /var/vcap/jobs/openstack_cpi/bin/cpi
```

Which lead to a very unfortunate situation:
- The `instances` table for the job `acceptance_tests` had a `vm_cid`
- The `instances` table for the job `acceptance_tests` did _not_ have a `spec_json`

Which after the successful Director updated proved to be a problem when trying to update the Cloud Foundry deployment. `bosh deploy` for cf failed with this stacktrace

```

I, [2016-04-20 15:51:00 #2265] [task:24765]  INFO -- DirectorJobRunner: Updating job: acceptance_tests
I, [2016-04-20 15:51:00 #2265] [task:24765]  INFO -- DirectorJobRunner: Deleting no longer needed instances
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: cloud_properties_changed? changed FROM: {} TO: {"availability_zone"=>"rot_1", "instance_type"=>"small_1_2"}
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: (0.000243s) SELECT NULL
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: (0.000395s) SELECT "stemcells".* FROM "stemcells" INNER JOIN "deployments_stemcells" ON (("deployments_stemcells"."stemcell_id" = "stemcells"."id") AND ("deployments_stemcells"."deployment_id" = 52))
D, [2016-04-20 15:51:00 #2265] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:cf
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:cf
I, [2016-04-20 15:51:00 #2265] [task:24765]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"9900f630-437b-453d-980f-15550adf297e","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'cf' against Director '3353a43b-ed61-413e-8332-4c59c82f681e': #<NoMethodError: undefined method '[]' for nil:NilClass>","created_at":1461167460}
E, [2016-04-20 15:51:00 #2265] [task:24765] ERROR -- DirectorJobRunner: undefined method '[]' for nil:NilClass
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/instance_plan.rb:282:in 'stemcell_changed?'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/instance_plan.rb:37:in 'changes'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/instance_plan.rb:24:in 'changed?'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:21:in 'block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:20:in 'select'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:20:in 'update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/multi_job_updater.rb:15:in 'block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/multi_job_updater.rb:11:in 'each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/multi_job_updater.rb:11:in 'run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/multi_job_updater.rb:52:in 'block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/multi_job_updater.rb:50:in 'each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/multi_job_updater.rb:50:in 'run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/steps/update_step.rb:46:in 'update_jobs'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/deployment_plan/steps/update_step.rb:22:in 'perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/jobs/update_deployment.rb:58:in 'block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/lock_helper.rb:13:in 'block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/lock.rb:56:in 'lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/lock_helper.rb:13:in 'with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/jobs/update_deployment.rb:42:in 'perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_runner.rb:99:in 'perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_runner.rb:32:in 'block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_formatter.rb:49:in 'with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_runner.rb:32:in 'run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/jobs/base_job.rb:10:in 'perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in 'perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in 'perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in 'block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in 'loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in 'work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/bin/bosh-director-worker:75:in '<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in 'load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in '<main>'
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: (0.000458s) SELECT NULL
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: (0.000063s) BEGIN
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: (0.000364s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2016-04-20 15:51:00.782510+0000', "description" = 'create deployment', "result" = 'undefined method '[]'' for nil:NilClass', "output" = '/var/vcap/store/director/tasks/24765', "checkpoint_time" = '2016-04-20 15:50:52.215602+0000', "type" = 'update_deployment', "username" = 'concourse', "deployment_name" = 'cf' WHERE ("id" = 24765)
D, [2016-04-20 15:51:00 #2265] [task:24765] DEBUG -- DirectorJobRunner: (0.001539s) COMMIT
I, [2016-04-20 15:51:00 #2265] []  INFO -- DirectorJobRunner: Task took 8.574909587 seconds to process.
```

So what happened was that the check if the stemcell changed in the new deployment failed for the `acceptance_tests` instance, because `spec_json` was null.

On a side note: This will most likely not occur on older Directors. The code determining which instances to update includes now all instances which have a `vm_cid` instead of previously excluding specifically errands. This was changed recently with https://github.com/cloudfoundry/bosh/commit/5f14043478534051550e9a49dd70916614cdf3ce 

Suggestion: the Director should execute a drain script, which
- makes it stop accepting tasks such as `create_deployment` or `run_errand`
- waits until the currently queued tasks are done

and `bosh-init` should call the drain script when stopping the processes on the Director. 
Wdyt?

**Comment by cppforlife** [comment]
That seems reasonable to make bosh-init run drain script if agent is accessible.

**Comment by voelzmo** [comment]
On a side note: this might get more and more relevant when service brokers deploy automatically without a human interacting. Right now, we work around this with a manual script checking running tasks before updating, but this is far from optimal.

**Comment by tyyko** [comment]
Hello @cppforlife 

I would like to contribute on this topic allowing bosh-init to call a drain script and put bosh in a state where it does not accept new deployments.

This would make bosh update more safe, as we can stop concourse pipelines but we cannot stop service brokers to request new services (creating new deployments) while the bosh update is ongoing.

What do you think? Is there something I should keep in mind? 

Thanks a lot,
Michael

**Comment by jfmyers9** [comment]
As `bosh-init` is not longer supported and `bosh create-env` exists in the [cli repository](https://github.com/cloudfoundry/bosh-cli), I have made another issue to properly track this. I'm going to close this issue as a result.
