### ISSUE TITLE
Reference error when deleting deployment with VMs which were deleted from IaaS

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/bosh#1247]
I got into this situation:
- The VMs of a CF deployment was manually deleted on the IaaS console (AWS)
- I tried to do other deployment, but if failed because the VMs were missing
- I run `bosh cck` and deleted all the vms reference
- Then run `bosh delete deployment --force ...`  to get rid of the deployment

But I got this error:

```
Error 100: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "rendered_templates_archives_instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(158) is still referenced from table "rendered_templates_archives".`
```

Run `bosh cck` again did not fix it.

But then, I run `bosh deploy`, it deployed everything, and I could delete the deployment with `bosh delete deployment`

**Comment by cppforlife** [comment]
@keymon looking at the code, looks like some blobstore error is happening preventing to continue deletion. even when we do -f we still do not let you ignore undeleted blobstore records. do you see any blobstore errors in the debug log?

cc @voelzmo

**Comment by keymon** [comment]
I am sorry but I lost the output of those task because I wiped that bosh installation.
I will report it back if it happens again.

**Comment by saliceti** [comment]
I have the same issue. Bosh uses S3 for blobstore and RDS for postgres DB.
This happens when I delete my CF deployment.
bosh version is 255.8 and the aws CPI is 44
I've sent you (@cppforlife) an email with the full debug log.

**Comment by combor** [comment]
It's still a problem on bosh `255.8` version and CPI `52`

Part of the debug log:
```
I, [2016-06-09 12:58:23 #23532] []  INFO -- DirectorJobRunner: Force deleting is set, ignoring exception
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.004431s) SELECT NULL
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.004455s) BEGIN
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.005101s) SELECT NULL
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.003337s) BEGIN
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.002227s) SELECT * FROM "ip_addresses" WHERE ("ip_addresses"."instance_id" = 59)
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.006268s) SELECT * FROM "ip_addresses" WHERE ("ip_addresses"."instance_id" = 43)
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.004181s) DELETE FROM "ip_addresses" WHERE "id" = 4
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.004003s) DELETE FROM "ip_addresses" WHERE "id" = 20
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.001525s) DELETE FROM "instances_templates" WHERE ("instance_id" = 59)
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.004728s) DELETE FROM "instances_templates" WHERE ("instance_id" = 43)
E, [2016-06-09 12:58:23 #23532] [] ERROR -- DirectorJobRunner: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "rendered_templates_archives_
instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(59) is still referenced from table "rendered_templates_archives".: DELETE FROM "instances" WHERE "id" = 59
E, [2016-06-09 12:58:23 #23532] [] ERROR -- DirectorJobRunner: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "rendered_templates_archives_
instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(43) is still referenced from table "rendered_templates_archives".: DELETE FROM "instances" WHERE "id" = 43
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.005789s) ROLLBACK
D, [2016-06-09 12:58:23 #23532] [] DEBUG -- DirectorJobRunner: (0.006121s) ROLLBACK
E, [2016-06-09 12:58:23 #23532] [] ERROR -- DirectorJobRunner: Worker thread raised exception: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constrai
nt "rendered_templates_archives_instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(59) is still referenced from table "rendered_templates_archives".
``` 

And stack trace:

```
E, [2016-06-09 12:58:23 #23532] [] ERROR -- DirectorJobRunner: Worker thread raised exception: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constrai
nt "rendered_templates_archives_instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(59) is still referenced from table "rendered_templates_archives".
 - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:145:in `exec'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/logging.rb:37:in `log_yield'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:132:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:413:in `_execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:425:in `check_database_errors'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/query.rb:79:in `execute_dui'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:812:in `execute_dui'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:733:in `with_sql_delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1485:in `_delete_without_checking'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1468:in `_delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1468:in `_delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1000:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1513:in `_destroy_delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1500:in `block in _destroy'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:865:in `around_destroy'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1497:in `_destroy'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1015:in `block (2 levels) in destroy'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1720:in `block in checked_transaction'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/query.rb:338:in `_transaction'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/query.rb:300:in `block in transaction'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/query.rb:293:in `transaction'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1720:in `checked_transaction'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1015:in `block in destroy'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1708:in `checked_save_failure'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:1015:in `destroy'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_deleter.rb:47:in `block in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_deleter.rb:19:in `delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_deleter.rb:55:in `block (3 levels) in delete_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by combor** [comment]
This is still happening:

```
 Failed deleting instances > cc_bridge/0 (818ba950-db80-4afc-9707-416d646204f1): PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "rendered_templates_archives_instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(406) is still referenced from table "rendered_templates_archives".
 (00:01:52)
   Failed deleting instances > api_worker/0 (ba4bbf72-51ef-4abc-97b9-fd4407821a44): PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "rendered_templates_archives_instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(394) is still referenced from table "rendered_templates_archives".
 (00:01:52)
   Failed deleting instances > router/1 (e9a04847-e44d-4f11-871f-58f033a022e7): PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "rendered_templates_archives_instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(401) is still referenced from table "rendered_templates_archives".
 (00:01:52)
```

**Comment by bitops** [comment]
Running into this issue as well. 

```
Director task 6271
  Started removing deployment artifacts
  Started removing deployment artifacts > Detaching stemcells. Done (00:00:00)
  Started removing deployment artifacts > Detaching releases. Done (00:00:00)

  Started deleting properties
  Started deleting properties > Destroying deployment. Failed: PG::Error: ERROR:  update or delete on table "deployments" violates foreign key constraint "placeholder_mappings_deployment_id_fkey" on table "placeholder_mappings"
DETAIL:  Key (id)=(34) is still referenced from table "placeholder_mappings".
 (00:00:00)

Error 100: PG::Error: ERROR:  update or delete on table "deployments" violates foreign key constraint "placeholder_mappings_deployment_id_fkey" on table "placeholder_mappings"
DETAIL:  Key (id)=(34) is still referenced from table "placeholder_mappings".
```

**Comment by gerhard** [comment]
Just ran into this today:

```
11:31:51 | Error: PG::Error: ERROR:  update or delete on table "variable_sets" violates foreign key constraint "instance_table_variable_set_fkey" on table "instances"
DETAIL:  Key (id)=(527) is still referenced from table "instances".
```

And again:

```
11:32:17 | Deleting jobs: rabbitmq-server/0a9605e8cfb147bf9d3e135484f923c8994b1164 (00:00:00)
            L Error: PG::Error: ERROR:  update or delete on table "templates" violates foreign key constraint "instances_templates_template_id_fkey" on table "instances_templates"
DETAIL:  Key (id)=(377) is still referenced from table "instances_templates".

11:32:17 | Deleting releases: rabbitmq-server/0.11.0+dev.1509711606 (00:00:00)
            L Error: PG::Error: ERROR:  update or delete on table "templates" violates foreign key constraint "instances_templates_template_id_fkey" on table "instances_templates"
DETAIL:  Key (id)=(377) is still referenced from table "instances_templates".


11:32:17 | Error: PG::Error: ERROR:  update or delete on table "templates" violates foreign key constraint "instances_templates_template_id_fkey" on table "instances_templates"
DETAIL:  Key (id)=(377) is still referenced from table "instances_templates".
```

Director is fairly recent:

```sh
Name      bosh-director-20170606
UUID      6767783b-4ca4-4e33-90e5-cbf8c6a7bfd0
Version   262.0.0 (00000000)
CPI       google_cpi
Features  compiled_package_cache: disabled
          config_server: disabled
          dns: disabled
          snapshots: disabled
User      admin
```

**Comment by jfmyers9** [comment]
Hey all,

I'm gonna go ahead an close this issue due to inactivity. If you run into this issue on the latest director version, please feel free to reopen / create a new issue.

@gerhard You issue seems to be slightly different than the originally reported issue. If you are still running into this problem on the latest version of the director, could you create a new issue with updated recreation steps?

Best,

@jfmyers9
