### ISSUE TITLE
undefined method for nil:NilClass not enough disk space could be located vsphere cpi

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry/bosh#1261]
Trying to deploy to vsphere returned:
```
Started updating job bosh > bosh/0 (d402205c-3de2-49ce-8764-21a937394aac) (canary). Failed: undefined method `disk_cid' for nil:NilClass (00:00:04)
```

When looking at the logs from `bosh task 3822 --debug` it shows that the cpi is returning null when no disk space could be located:
```
D, [2016-05-11 10:08:06 #1310] [canary_update(bosh/0 (d402205c-3de2-49ce-8764-21a937394aac))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Bosh::Clouds::NoDiskSpace","message":"Couldn't find a 'persistent' datastore with 100000MB
of free space. Found:\n vol310 (32136MB free of 286811MB capacity)\n vol309 (27959MB free of 162648MB capacity)\n","ok_to_retry":true}, "log": "..."}"
```

**Comment by cppforlife** [comment]
there should be a stacktrace in the ruby debug log. could you please include it?

**Comment by bodymindarts** [comment]
```
E, [2016-05-11 14:30:59 #15499] [] ERROR -- DirectorJobRunner: Worker thread raised exception: undefined method `disk_cid' for nil:NilClass - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/disk_manager.rb:256:in `rescue in
create_and_attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/disk_manager.rb:247:in `create_and_attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/disk_manager.rb:21:in `update_persistent_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_updater.rb:84:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_updater.rb:46:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:111:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:109:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:108:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:103:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-05-11 14:30:59 #15499] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2016-05-11 14:30:59 #15499] [task:3897] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2016-05-11 14:30:59 #15499] [task:3897] DEBUG -- DirectorJobRunner: (0.000384s) SELECT NULL
D, [2016-05-11 14:30:59 #15499] [task:3897] DEBUG -- DirectorJobRunner: (0.000378s) SELECT "stemcells".* FROM "stemcells" INNER JOIN "deployments_stemcells" ON (("deployments_stemcells"."stemcell_id" = "stemcells"."id") AND ("deployments_stemcells"."deployment_id" = 66))
D, [2016-05-11 14:30:59 #15499] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-05-11 14:30:59 #15499] [task:3897] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:play-cf-bosh-lite-47
D, [2016-05-11 14:30:59 #15499] [task:3897] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:play-cf-bosh-lite-47
I, [2016-05-11 14:30:59 #15499] [task:3897]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2016-05-11 14:30:59 #15499] [task:3897] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"98f7a54a-47d6-47e0-8d87-8f7e351002b7","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for
'play-cf-bosh-lite-47' against Director 'f635b1ba-5000-48e1-92c8-19471d20e0e4': #<NoMethodError: undefined method `disk_cid' for nil:NilClass>","created_at":1462977059}
E, [2016-05-11 14:30:59 #15499] [task:3897] ERROR -- DirectorJobRunner: undefined method `disk_cid' for nil:NilClass
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/disk_manager.rb:256:in `rescue in create_and_attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/disk_manager.rb:247:in `create_and_attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/disk_manager.rb:21:in `update_persistent_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_updater.rb:84:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_updater.rb:46:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:111:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:109:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:108:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/job_updater.rb:103:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by cppforlife** [comment]
Seems like we already fixed this issue in https://github.com/cloudfoundry/bosh/commit/7d6a19b9696e7534046c249028f7d01249ce6ba2. Please update to 256.x Director.
