### ISSUE TITLE
Deployment hangs & bosh in weird state after worker disconnected from NATS

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1263]
### Description

In BOSH during deployment, during VM creation or deletion phase, when worker is disconnected from NATS, BOSH gets into weird state.

* BOSH version 256.2
* AWS CPI version 44
* BOSH CLI version 1.3232

The deployment is microbosh, meaning all components run on the same server. Workers connect to NATS on localhost. NATS keeps running all the time. Other workers and bosh agents from deployed VMs are able to connect to it. There are no errors or any other log messages in NATS logs. The disconnection of worker seems to happen randomly, but quite often (66% of deploys/deletions). Worker/BOSH doesn't handle the resulting situation well (see the issues below). BOSH cli gets stuck in the task forever and keeps thinking the task still runs. This, for example, makes your CI jobs stuck.

### Issues
* the deployment stops where it was, no further changes are applied
* in `bosh tasks recent --no-filter` you can see the task status as timed out
* however when you connect with BOSH CLI (latest 1.3232 version), it thinks that task is still running:
```
  Started creating missing vms > parser_z1/0 (b38c0f85-aac4-449a-b41f-ef585c74731f)
  Started creating missing vms > parser_z2/0 (3704755e-a887-4537-a76e-8227f2085d53)
     Done creating missing vms > queue_z2/0 (03b8ebde-cb29-4f1a-ba07-bb9fa3e81221) (00:04:26)
  Started creating missing vms > elasticsearch_master_z1/0 (7d05a98b-7402-48c0-98e7-ed1f0484194c)^C
Do you want to cancel task 23? [yN] (^C again to detach): ^C
Task 23 is still running
/tmp/build/e55deab7 # bosh tasks
Acting as user 'admin' on 'my-bosh'
No running tasks
```
* further re-deployment fails on IP conflicts, as VMs have been created in AWS, but BOSH doesn't know about that (as the task died in the middle of deployment. Perhaps BOSH should remember that VM exists immediately after CPI call succeeds? Not only after it boots up & agent connects to NATS).
* if you accidentally delete a VM that has no "bosh IDs" (name and other settings) in AWS, but BOSH somehow remembered it had already existed, then you can't retry deployment, as BOSH will try to `get_state` from that VM. Interestingly, when you do `bosh vms`, that VM is not even present there
* `bosh cck` also fails in that case with `Unable to look up VM apply spec`:
```
Director task 36
  Started applying problem resolutions
  Started applying problem resolutions > missing_vm 68: Recreate VM for 'ingestor_z2/0 (ed75af55-da43-4d58-8f45-eb4d3d59b966)'. Failed: Unable to look up VM apply spec (00:00:00)
  Started applying problem resolutions > missing_vm 63: Recreate VM for 'cell_z1/0 (a8cb0c9d-cada-4c93-92f8-dedfdfb16f39)'. Failed: Unable to look up VM apply spec (00:00:00)
   Failed applying problem resolutions (00:00:00)

Error 100: Error resolving problem '3': Unable to look up VM apply spec
Error resolving problem '4': Unable to look up VM apply spec

Task 36 error
```
* if you then attempt to restart BOSH components (`monit restart all`) then all will restart fine, except registry, which will consume 100% cpu constantly trying to `Bosh::Registry::InstanceNotFound - Can't find instance 'i-214ccaad'`
* to fix that, you not only need to delete deployment, but also do `bosh cleanup --all` & restart registry

### Possible fixes
* I think worker should be able to reconnect to NATS and continue deployment
* Also, BOSH should not get into weird state and handle errors better
* And the bosh cli should be able to figure out that the task has timed out and return with error instead of getting stuck forever thinking the task still runs.

### Logs
Error stacktrace from worker error log:
```
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/nats-0.5.0.beta.12/lib/nats/client.rb:618:in `block in connection_completed': 'Unresponsive client detected, connection dropped' (NATS::ServerError)
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/nats-0.5.0.beta.12/lib/nats/client.rb:539:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/nats-0.5.0.beta.12/lib/nats/client.rb:539:in `receive_data'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/db_job.rb:72:in `block in run'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/db_job.rb:71:in `fork'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/db_job.rb:71:in `run'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/db_job.rb:23:in `perform'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
    from /var/vcap/packages/ruby/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
    from /var/vcap/packages/ruby/lib/ruby/2.1.0/timeout.rb:100:in `call'
    from /var/vcap/packages/ruby/lib/ruby/2.1.0/timeout.rb:100:in `timeout'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
    from /var/vcap/packages/ruby/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
    from /var/vcap/packages/ruby/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/worker.rb:35:in `start'
    from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/bin/bosh-director-worker:55:in `<top (required)>'
    from /var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
    from /var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
```

Registry log:
```
2016-05-11 13:12:38 - Bosh::Registry::InstanceNotFound - Can't find instance 'i-964dcb1a':
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.3232.2.0/lib/bosh/registry/instance_manager.rb:66:in `get_instance'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.3232.2.0/lib/bosh/registry/instance_manager.rb:31:in `read_settings'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.3232.2.0/lib/bosh/registry/api_controller.rb:22:in `block in <class:ApiController>'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.3232.2.0/lib/bosh/registry/runner.rb:34:in `start_http_server'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.3232.2.0/lib/bosh/registry/runner.rb:18:in `run'
    /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.3232.2.0/bin/bosh-registry:28:in `<top (required)>'
    /var/vcap/packages/registry/bin/bosh-registry:16:in `load'
    /var/vcap/packages/registry/bin/bosh-registry:16:in `<main>'
```

**Comment by cppforlife** [comment]
Interesting I dont think we've seen that error ever in any of our environments.

- What kind instance size are you using for the Director?
- Have you seen this error before this version?

Re `Unable to look up VM apply spec` error: We are adding 'Delete VM' option to cck to cover othe edge cases.

**Comment by mtekel** [comment]
Our microbosh is T2.medium (2 cores, 2.5GHz) with full CPU credits. CPU load on the VM is quite low. Only components that use CPU (from time to time) are AWS CPI (limited to a single core) and registry (again limited to single core) when it is broken. We have not seen anything similar prior to this version.

Nevertheless, I think even if the VM was a bit slow, things should only get slower and not fail (perhaps only on timeouts if it's really too slow).

**Comment by cppforlife** [comment]
Did you previously run 255.x? I wonder if this is related to bumping eventmachine to 1.0.4 from 1.0.3.

Also how big if your deployment size. I'm gonna try to reproduce the problem in my account.

**Comment by mtekel** [comment]
We run 255.8 previously. But this also happens on clean deploy (from scratch - all new, including BOSH). We are currently deploying 32 VMs in 1 deployment.

**Comment by cppforlife** [comment]
do you mind sharing your sanitized director manifest?

**Comment by mtekel** [comment]
This is the [sanitized manifest we use for tests](https://github.com/alphagov/paas-cf/blob/17a454ebeb9e52df6edbecd24059b15b430108e3/manifests/bosh-manifest/reference-bosh-manifest.yml) (it's the same as real except missing credentials and real IPs).

**Comment by cppforlife** [comment]
awesome. one more question which db are you using? how many connections does it allow?

**Comment by mtekel** [comment]
we're using AWS RDS. db.T2.medium instance which allows up to 136 connections. We're seeing around 17 max. At the time of the issue, there were 8 connections.

**Comment by mtekel** [comment]
One correction: CPI version is 44. This removes CPI as potential cause of the issues as we have been running till now with that version...

**Comment by saliceti** [comment]
+1
I'm testing with the same versions as @mtekel and I'm experiencing the same issues.
Create a new CF deployment. Run delete deployment and it hangs. In the bosh logs I get the errors "Unresponsive client detected", Bosh::Registry::InstanceNotFound, etc.
I could delete it with the "--force " option only.

**Comment by voelzmo** [comment]
I've seen that also recently on one of our Directors after upgrading to a new version. Unfortunately not sure about the concrete versions involved, couldn't figure out the root-cause there :(

**Comment by cppforlife** [comment]
@saliceti how big is your director vm?

**Comment by saliceti** [comment]
@cppforlife: t2.medium (same as @mtekel)

**Comment by cppforlife** [comment]
i havent been able to repro this problem so far with a local db and local blobstore. i'm going to switch it over to rds now. 

@voelzmo i know that you are not using rds, are you using external blobstore?

also are you all deploying multiple things to the director in parallel. anyone has some cpu/mem usage from the director around when this problem occurs? also how many vms are managed by the director across all deployments?

**Comment by cppforlife** [comment]
also any other software colocated on that instance like UAA?

**Comment by cppforlife** [comment]
i also see that you have not changed max_threads (default 32). how does your `update` section of cf manifest look like?

**Comment by cppforlife** [comment]
(btw if you anyone is willing to do some screen sharing to debug the environment with the problem, let me know)

**Comment by combor** [comment]
+1 for this. There is no collocated uaa on bosh VM. Update section:
```
update:
  canaries: 0
  max_in_flight: 2
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false
```
If you are interested in other parts of our manifest you can find it here:
https://github.com/alphagov/paas-cf/tree/17a454ebeb9e52df6edbecd24059b15b430108e3/manifests/cf-manifest/deployments

**Comment by mtekel** [comment]
We are using RDS and S3 as blobstore. UAA is _not_ running on this VM or at all. The microbosh is deployed from the manifest I shared above. The issue happens specifically during creation or deletion of VMs. During this time, AWS CPI consumes 100% performance of a single core, the second core is about at around 20% cpu load. The issue happens exactly at the time when the "NATS error" is logged in the worker error log.

We use 32 threads and when we run deploy/delete it starts creating/deleting 32 VMs in parallel. But this was fine with 255.8 BOSH and the only issues we had with that previously was with hitting AWS API throttling, which is now solved.

**Comment by cppforlife** [comment]
ah. my env was not using 32 threads. ill give that a shot in the morning.

**Comment by cppforlife** [comment]
...or rather it did have 32 threads max but it didnt need all of them during my bosh deploy.

**Comment by mtekel** [comment]
Maybe you can try severing the worker connection to NATS or restarting the NATS server during VM creation/deletion...

**Comment by mtekel** [comment]
Ok, so restarting NATS doesn't cause it....

**Comment by cppforlife** [comment]
@mtekel I've not yet reproduced the NATS connectivity issue but I did run into task timeout (35+ threads on the same instance type). I've also seen CPU spike to 100% on both cores and memory is consumed to the fullest and swap is in use.

While I continue investigating I would recommend scaling down to a smaller number of threads.

I'm also thinking about introducing a separate configuration value that would be responsible for concurrency of bulk CPI operations like create/delete VMs.

**Comment by cunnie** [comment]
FYI, I was able to reproduce the problem (not on purpose; I was attempting to benchmark BOSH directors of different sizes). I suspect the problem has to do with the instance size (t2.micro); I plan to re-deploy with a larger instance size &amp; report back with the results:

* t2.micro
* BOSH version 256.10
* AWS CPI version 53
* BOSH CLI version 1.3232.0
* max_threads 10
* [sanitized director manifest](https://gist.github.com/cunnie/1ab9d4c7c477e3c36cdc343e2ff3fb41)
* [dummy deployment manifest](https://gist.github.com/cunnie/e7089711d08181612cf1f32611e3f72f)
* [cloud config](https://gist.github.com/cunnie/3785c3b9f596055258e8ef5a08101141)
* `/var/vcap/sys/log/director/worker_1.stderr.log`
```
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/nats-0.5.0.beta.12/lib/nats/client.rb:618:in `block in connection_completed': 'Unresponsive client detected, connection dropped' (NATS::ServerError)
        from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/nats-0.5.0.beta.12/lib/nats/client.rb:539:in `call'
        from /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/nats-0.5.0.beta.12/lib/nats/client.rb:539:in `receive_data'
```
* I did **not** see any `Bosh::Registry::InstanceNotFound` messages in `/var/vcap/sys/log/registry/*`
* `bosh delete deployment dummy` deleted 5 VMs
* I deleted the remaining VM manually from the AWS console (apparently BOSH lost track of that VM).

**Comment by mtekel** [comment]
We deployed new 3262.14 (or v257.14) on the same VM (t2.medium - 2 cpus, 4G ram) and it works fine. The cpu load is still high (mainly from aws-cpi - which creates 90% of all CPU load during normal deployment), but deployment doesn't break. Before it was very consistent and would break almost every time (say 90% failure rate), now it seems to just work...

I will close this issue and re-open if we have any new problems.
