### ISSUE TITLE
Ambiguous error when using a non-existant VM extension

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh#1267]
If you typo a `vm_extensions` value of an instance group to something which is not defined in cloud config, the deploy task errors with the following ambiguous error after it has finished compiling packages...

```
Error 100: undefined method `cloud_properties' for nil:NilClass
```

And the following backtrace in the task debug...

```
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/instance.rb:288:in `block in cloud_properties'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/instance.rb:287:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/instance.rb:287:in `cloud_properties'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/instance.rb:204:in `cloud_properties_changed?'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/instance_plan.rb:36:in `changes'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/instance_plan.rb:24:in `changed?'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/job_updater.rb:21:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/job_updater.rb:20:in `select'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/job_updater.rb:20:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/multi_job_updater.rb:34:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.2.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.2.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.2.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.2.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

Seems like it could give a much more descriptive error for UX sanity. I had to reference the backtrace and code to see what I needed to change in my manifest.

Encountered while transitioning a deployment to cloud config.

**Comment by cppforlife** [comment]
@dpb587 interesting. sounds like we are not properly searching vm_extensions.

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/119611031
