### ISSUE TITLE
Errors when bosh create release [migrated from cf-release]

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1328]
> Original issue: https://github.com/cloudfoundry/cf-release/issues/998
> Original poster: @YuPengZTE

----

```
root@agent-id-bosh-0:/home/vagrant/contribute/cf-release# bosh create release
Syncing blobs...
debian_nfs_server/nfs-kernel-server_1%3a1... downloaded
uaa/cloudfoundry-identity-varz-1.0.2.war downloaded
nginx/nginx-upload-module-2.2.tar.gz downloaded
uaa/newrelic.jar downloaded
uaa/apache-tomcat-7.0.61.tar.gz downloaded
haproxy/haproxy-1.5.14.tar.gz downloaded
haproxy/pcre-8.37.tar.gz downloaded
uaa/cloudfoundry-identity-statsd-1.0.0.wa... downloaded
ruby-2.1.8/bundler-1.9.4.gem downloaded
ruby-2.1.8/ruby-2.1.8.tar.gz downloaded
ruby-2.1.8/yaml-0.1.6.tar.gz downloaded
postgres/postgresql-9.4.6.tar.gz downloaded
golang/go1.6.1.linux-amd64.tar.gz downloaded
golang/go1.5.4.linux-amd64.tar.gz downloaded
openjdk/openjdk-1.8.0_91-x86_64-trusty.ta... downloaded
openjdk/openjdk-1.8.0_91-x86_64-mountainl... downloaded
libmariadb/libmariadb-5.5.36.tar.xz downloaded
nginx/newrelic_nginx_agent-1.2.1.tar.gz downloaded
ruby-2.2.5/ruby-2.2.5.tar.gz downloaded
ruby-2.2.5/bundler-1.11.2.gem downloaded
ruby-2.2.5/yaml-0.1.6.tar.gz downloaded
ruby-2.3/bundler-1.11.2.gem downloaded
ruby-2.3/ruby-2.3.1.tar.gz downloaded
ruby-2.3/rubygems-2.6.4.tgz downloaded
binary-buildpack/binary_buildpack-cached-... downloaded
go-buildpack/go_buildpack-cached-v1.7.8.z... downloaded
java-buildpack/java-buildpack-v3.7.1.zip downloaded
java-buildpack/java-buildpack-offline-v3.... downloaded
python-buildpack/python_buildpack-cached-... downloading 255.2M (5%)
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/base.rb:63:in `rescue in get': Failed to fetch object, underlying error: #<HTTPClient::ReceiveTimeoutError: execution expired> /usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `sysread' (Bosh::Blobstore::BlobstoreError)
/usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `readpartial'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:364:in `readpartial'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:957:in `block in read_body_length'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:955:in `read_body_length'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:703:in `get_body'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:1092:in `do_get_block'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:891:in `block in do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:985:in `protect_keep_alive_disconnected'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:890:in `do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:778:in `request'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:677:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/simple_blobstore_client.rb:39:in `get_file'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/base.rb:50:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `call'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `block in retryer'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `loop'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `retryer'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:316:in `download_blob'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:242:in `block (3 levels) in process_index'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `call'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `loop'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/base.rb:49:in `get'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `call'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `block in retryer'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `loop'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `retryer'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
        from /var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:316:in `download_blob'
        from /var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:242:in `block (3 levels) in process_index'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `call'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `loop'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `block in create_thread'
        from /var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from /var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

root@agent-id-bosh-0:/home/vagrant/contribute/cf-release# bosh create release
Syncing blobs...
python-buildpack/python_buildpack-cached-... downloading 255.2M (49%)
                                             downloading 255.2M (50%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (110%)
                                             downloading 255.2M (110%)
                                             downloading 255.2M (137%)
                                             downloading 255.2M (137%)
                                             downloading 255.2M (137%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (165%)
                                             downloading 255.2M (307%)
```

**Comment by dpb587-pivotal** [comment]
A similar backtrace was mentioned in [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/bosh/p1467310353001408) today (bosh 3262.1)...

    Started creating new packages > hdp/7a2b9d3e6e2f267763138822d9933ca7cc72b6db. Failed: Failed to create object, underlying error: #<HTTPClient::ReceiveTimeoutError: execution expired> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:792:in `gets'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:792:in `block in parse_header'
    /var/vcap/packages/ruby/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:788:in `parse_header'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:771:in `read_header'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:547:in `get_header'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1294:in `do_get_header'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1241:in `do_get_block'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:858:in `request'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:771:in `put'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/blobstore_client-1.3262.1.0/lib/blobstore_client/dav_blobstore_client.rb:42:in `create_file'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/blobstore_client-1.3262.1.0/lib/blobstore_client/base.rb:27:in `create'
    ....

**Comment by cppforlife** [comment]
> HTTPClient::ReceiveTimeoutError: execution expired

Flaky network. CLI already retries as much as it's reasonable (a few times). Percentage of course is incorrect after a few retries so I've recorded this as a fix to do.
