### ISSUE TITLE
Failed to delete VMs during `bosh delete deployment`: wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/bosh#1396]
While running `bosh delete deployment <id>` I got an error `wrong number of arguments (1 for 0)`. Repeating `bosh delete deployment` several times, works.

```
Director task 834
  Started deleting instances
  Started deleting instances > cell/0 (a40e5398-2815-4a9d-93a4-90f610489114)
  Started deleting instances > cc_bridge/0 (2cea40de-df8b-4cb5-bf37-6db5b5c72a68)
  Started deleting instances > brain/1 (1302a580-a94e-4104-a236-39e4236ecb95)
  Started deleting instances > loggregator_trafficcontroller/0 (4a8b810c-c95c-4c83-843a-cf62a52f357f)
  Started deleting instances > router/1 (20ed0f1d-a431-4dc3-9664-779719299a6f)
  Started deleting instances > api/1 (1e2cc3b7-fcc3-48ea-b28c-4b23a110661f)
  Started deleting instances > nats/1 (de222762-bcf0-4ebf-a29a-fe500a87e532)
  Started deleting instances > database/1 (5b9a39b4-dad8-43c3-91eb-62775602fe94)
  Started deleting instances > consul/2 (11bf949e-5f15-4fe6-b8fd-ffb5fc71ae67)
  Started deleting instances > consul/1 (8df40c59-1a2e-45a6-81a9-cc86c57d9168)
  Started deleting instances > kibana/0 (0a487c60-db49-4488-af8c-d83472d19a4a)
  Started deleting instances > rds_broker/1 (f1b2f7f7-ffc0-43e8-b49c-21fbd8e7670d)
  Started deleting instances > elasticsearch_master/1 (defc3cb6-12fc-40a0-9a91-f90e16d6f48b)
  Started deleting instances > elasticsearch_master/2 (cdeb64b8-ac10-4ab1-914a-a0daf20d95b7)
   Failed deleting instances > router/1 (20ed0f1d-a431-4dc3-9664-779719299a6f): wrong number of arguments (1 for 0) (00:00:00)
   Failed deleting instances > api/1 (1e2cc3b7-fcc3-48ea-b28c-4b23a110661f): wrong number of arguments (1 for 0) (00:00:00)
   Failed deleting instances > rds_broker/1 (f1b2f7f7-ffc0-43e8-b49c-21fbd8e7670d): wrong number of arguments (1 for 0) (00:00:00)
   Failed deleting instances > consul/1 (8df40c59-1a2e-45a6-81a9-cc86c57d9168): wrong number of arguments (1 for 0) (00:00:00)
   Failed deleting instances > nats/1 (de222762-bcf0-4ebf-a29a-fe500a87e532): wrong number of arguments (1 for 0) (00:00:00)
   Failed deleting instances > cell/0 (a40e5398-2815-4a9d-93a4-90f610489114): wrong number of arguments (1 for 0) (00:00:00)
   Failed deleting instances > elasticsearch_master/2 (cdeb64b8-ac10-4ab1-914a-a0daf20d95b7): wrong number of arguments (1 for 0) (00:00:00)
   Failed deleting instances > cc_bridge/0 (2cea40de-df8b-4cb5-bf37-6db5b5c72a68): undefined method `resolve' for Aws::EndpointProvider:Class (00:00:00)
     Done deleting instances > brain/1 (1302a580-a94e-4104-a236-39e4236ecb95) (00:00:00)
     Done deleting instances > database/1 (5b9a39b4-dad8-43c3-91eb-62775602fe94) (00:00:00)
     Done deleting instances > loggregator_trafficcontroller/0 (4a8b810c-c95c-4c83-843a-cf62a52f357f) (00:00:00)
     Done deleting instances > elasticsearch_master/1 (defc3cb6-12fc-40a0-9a91-f90e16d6f48b) (00:00:00)
     Done deleting instances > kibana/0 (0a487c60-db49-4488-af8c-d83472d19a4a) (00:00:00)
     Done deleting instances > consul/2 (11bf949e-5f15-4fe6-b8fd-ffb5fc71ae67) (00:00:00)
   Failed deleting instances (00:00:00)

Error 100: wrong number of arguments (1 for 0)

Task 834 error

```

Fixed with: `while ! bosh -n delete deployment hector; do true; done` :)

The `bosh task --debug ...` shows this stacktrace:

```
E, [2016-08-15 11:17:17 #23579] [] ERROR -- DirectorJobRunner: Worker thread raised exception: wrong number of arguments (1 for 0) - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws
-sdk-core/credential_provider_chain.rb:58:in `initialize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/credential_provider_chain.rb:58:in `new'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/credential_provider_chain.rb:58:in `shared_credentials'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/credential_provider_chain.rb:12:in `block in resolve'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/credential_provider_chain.rb:11:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/credential_provider_chain.rb:11:in `resolve'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/plugins/request_signer.rb:37:in `block in <class:RequestSigner>'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:64:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:64:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:199:in `block in resolve_defaults'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:57:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:57:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:198:in `resolve_defaults'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:194:in `value_at'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:183:in `block in resolve'
/var/vcap/packages/ruby/lib/ruby/2.1.0/set.rb:263:in `each_key'
/var/vcap/packages/ruby/lib/ruby/2.1.0/set.rb:263:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:183:in `resolve'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:171:in `apply_defaults'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/configuration.rb:144:in `build!'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/base.rb:68:in `build_config'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/base.rb:19:in `initialize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/base.rb:105:in `new'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/resource.rb:169:in `extract_client'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/resource.rb:15:in `initialize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.3215.3.0/lib/blobstore_client/s3_blobstore_client.rb:97:in `new'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.3215.3.0/lib/blobstore_client/s3_blobstore_client.rb:97:in `delete_object'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.3215.3.0/lib/blobstore_client/base.rb:69:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/rendered_job_templates_cleaner.rb:24:in `block in clean_all'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/rendered_job_templates_cleaner.rb:22:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/rendered_job_templates_cleaner.rb:22:in `clean_all'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_deleter.rb:37:in `block (2 levels) in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/error_ignorer.rb:9:in `with_force_check'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_deleter.rb:36:in `block in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_deleter.rb:19:in `delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.3.0/lib/bosh/director/instance_deleter.rb:55:in `block (3 levels) in delete_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-08-15 11:17:17 #23579] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
```

It seems some issue deleting the templates in S3. Note that:
- We use S3 for the blobstore
- We use IAM profiles to authenticate to S3 blobstore.

**Comment by keymon** [comment]
Maybe it is related to #1149?

**Comment by keymon** [comment]
```
 # bosh status
Config
             /root/.bosh_config

Director
  Name       my-bosh
  URL        https://bosh.hector.dev.cloudpipeline.digital:25555
  Version    1.3215.3.0 (00000000)
  User       admin
  UUID       9e89d8e8-2516-48c1-8c6d-677249af9141
  CPI        aws_cpi
  dns        disabled
  compiled_package_cache enabled (provider: s3)
  snapshots  disabled

Deployment
  Manifest   /tmp/build/04dcec6b/cf-manifest-with-uuid.yml
```

**Comment by cppforlife** [comment]
@keymon 256+ bosh release switched to using s3cli instead of s3 ruby library (to be more consistent with agent's use of s3). i believe update to the director will resolve this problem.

**Comment by dpb587-pivotal** [comment]
@keymon, do you continue to see this failure on recent versions of director?

**Comment by keymon** [comment]
Tbh I do not work with this at the moment. My ex coworkers do /cc @dcarley @saliceti

**Comment by dpb587-pivotal** [comment]
Closing - sounds like recent director versions have resolved this. Feel free to follow up and add updated details to reopen.
