### ISSUE TITLE
Unable to identify orphaned vm. should add vm id in bosh hm message

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh#1469]
After a Iaas failure, we met an issue with 5 bosh delete vms, still up, contacting bosh director.

Here is the type of message we get in /var/vcap/sys/log/registry/ registry.stderr.log

```
2016-09-30 09:26:37 - Bosh::Registry::InstanceNotFound - Can't find instance 'vm-af7bbb3b-63ab-4ecb-882e-a7b42c349f18':
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/bosh-registry-1.3262.3.0/lib/bosh/registry/instance_manager.rb:66:in `get_instance'
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/bosh-registry-1.3262.3.0/lib/bosh/registry/instance_manager.rb:31:in `read_settings'
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/bosh-registry-1.3262.3.0/lib/bosh/registry/api_controller.rb:22:in `block in <class:ApiController>'
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'

```

As bosh operator, here is type of mail we get from bosh health manager :

```
agent 0e13b909-8493-4371-9743-a3a09af21cce [] 0e13b909-8493-4371-9743-a3a09af21cce is not a part of any deployment Severity: 2 Summary: 0e13b909-8493-4371-9743-a3a09af21cce is not a part of any deployment Time: 2016-10-10 15:23:48 UTC
```

Giving the vm name or ip would be most useful to locate the orphaned vm in a big tenant

**Comment by poblin-orange** [comment]
guess this is fixed by https://www.pivotaltracker.com/n/projects/956238/stories/169682585
