### ISSUE TITLE
Director fails to get compile lock in the middle of compilation

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1511]
*Used Director version*: 257.3
*Infrastructure*: AWS
*Configuration*: Using 18 workers

A recent `bosh deploy` failed, because compilation VMs couldn't be created. The first few compilation VMs were created successfully, then all subsequent VMs fail. Seems like the DB connection pool was exhausted or something?

Note: The VM was actually created correctly from AWS perspective and is hanging around forever since.

Task log
```
Started compiling packages > docker/ecd5b1793ed906fe8b8711edafead29ae65aeed4
  Started compiling packages > bosh-helpers/e1bbff85fa1e4b1d51887ba6ecff6949ca92e8f6
   Failed compiling packages > common/953ccbc1b39fc972d2b4903beb16af7daf78cc85: PG::Error: could not connect to server: Connection refused
       Is the server running on host "127.0.0.1" and accepting
       TCP/IP connections on port 5432?
(00:00:26)
   Failed compiling packages > golang/95c358c1eeabe9495e089de333e0c91eee2fef0c: PG::Error: could not connect to server: Connection refused
       Is the server running on host "127.0.0.1" and accepting
       TCP/IP connections on port 5432?
(00:00:26)
   Failed compiling packages > node/ddc53b67bcaebc0bba3cb3bc11be377b34c5e90a: PG::Error: could not connect to server: Connection refused
       Is the server running on host "127.0.0.1" and accepting
       TCP/IP connections on port 5432?
(00:00:26)
```

Debug log shows that the Director failed to [get the compile lock](https://github.com/cloudfoundry/bosh/blob/stable-3262.3/bosh-director/lib/bosh/director/deployment_plan/steps/package_compile_step.rb#L59). Note that it also puts out `127.0.0.1` as IP, but we use RDS postgres in this configuration.
```
I, [2016-08-05T07:04:28.650323 #10318]  INFO -- : Waiting for instance to be ready...
I, [2016-08-05T07:04:28.820457 #10318]  INFO -- : [AWS EC2 200 0.169336 0 retries] describe_instances(:instance_ids=>["i-04ac85301f4938fec"])  

D, [2016-08-05T07:04:28.821253 #10318] DEBUG -- : Waiting for i-04ac85301f4938fec to be running, retrying in 2 seconds (1/54)
I, [2016-08-05T07:04:30.911959 #10318]  INFO -- : [AWS EC2 200 0.089828 0 retries] describe_instances(:instance_ids=>["i-04ac85301f4938fec"])  

D, [2016-08-05T07:04:30.912698 #10318] DEBUG -- : Waiting for i-04ac85301f4938fec to be running, retrying in 4 seconds (2/54)
I, [2016-08-05T07:04:35.009526 #10318]  INFO -- : [AWS EC2 200 0.095824 0 retries] describe_instances(:instance_ids=>["i-04ac85301f4938fec"])  

D, [2016-08-05T07:04:35.010261 #10318] DEBUG -- : Waiting for i-04ac85301f4938fec to be running, retrying in 8 seconds (3/54)
, exit_status: pid 10312 SIGTERM (signal 15)
E, [2016-08-05 07:04:41 #9979] [compile_package(bosh-helpers/e1bbff85fa1e4b1d51887ba6ecff6949ca92e8f6, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3262.4)] ERROR -- DirectorJobRunner: error creating vm: Unknown CPI error 'Unknown' with message 'SIGTERM'
E, [2016-08-05 07:04:41 #9979] [] ERROR -- DirectorJobRunner: Worker thread raised exception: PG::Error: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
 - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:243:in `initialize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:243:in `new'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:243:in `connect'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool.rb:103:in `make_new'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:224:in `make_new'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:197:in `available'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:133:in `_acquire'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:147:in `block in acquire'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:265:in `block in sync'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:265:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:265:in `sync'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:146:in `acquire'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/extensions/connection_validator.rb:90:in `acquire'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:849:in `literal_string_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:79:in `literal_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:486:in `complex_expression_sql_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/shared/postgres.rb:1272:in `complex_expression_sql_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/associations.rb:2551:in `complex_expression_sql_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/sql.rb:109:in `to_s_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:1214:in `literal_expression_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:86:in `literal_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:494:in `block in complex_expression_sql_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:492:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:492:in `complex_expression_sql_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/shared/postgres.rb:1272:in `complex_expression_sql_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/associations.rb:2551:in `complex_expression_sql_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/sql.rb:109:in `to_s_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:1214:in `literal_expression_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:86:in `literal_append'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:1455:in `select_where_sql'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/sql.rb:231:in `delete_sql'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:120:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock.rb:100:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock.rb:65:in `release'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock.rb:55:in `ensure in lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock.rb:55:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by jfmyers9** [comment]
Closing due to inactivity. Please feel free to reopen if this issue is still occurring.
