### ISSUE TITLE
Unclear error message in health-manager during startup

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry/bosh#1538]
When connecting to director, using a URL that is not reachable, the following error is reported:

```
F, [2016-12-14T14:06:38.276133 #26283] FATAL : double resume
F, [2016-12-14T14:06:38.276261 #26283] FATAL : /var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/mo
nitor/director.rb:71:in `resume'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/director.rb:71:in `block in perform_reque
st'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/em/deferrable.rb:74:in `errback'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/director.rb:71:in `perform_request'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/director.rb:80:in `get_info'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/director.rb:93:in `auth_provider'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/director.rb:65:in `perform_request'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/director.rb:10:in `get_deployments'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/runner.rb:152:in `fetch_deployments'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-260.0.0/lib/bosh/monitor/runner.rb:99:in `block in poll_director'
I, [2016-12-14T14:06:38.276316 #26283]  INFO : HealthMonitor shutting down...
```

A debugging session has showed that the address at which the library tries to reach out to director is inaccessible from that machine. So the `f.resume(http)` in the error callback gets called before the `Fiber.yield` gets called. It would be nice to have an error message saying that the host is unreachable rather than an internal Fiber error.

**Comment by mfine30** [comment]
Closing in favor of #1806 - looks like we've done some refactoring and that issue has an updated stacktrace.
