### ISSUE TITLE
PGError when deleting deployment

### ISSUE THREAD

**Issue by mariash** [cloudfoundry/bosh#1582]
Deleting deployment fails with `PG::Error: ERROR:  invalid escape string`. We've seen this error 3 times so far in past 3 days. We are running a hundreds of deployments per day and most of them succeed. We are using GCP.

It was theorized that maybe this has something to do with IPv6 addresses being returned instead of IPv4 when doing DNS lookup?

deployment logs:
```
18:15:23 | Deleting instances: worker/d33577e9-dfcb-4dd5-84c6-2a3293e386f9 (0) (00:03:01)

18:15:23 | Error: PG::Error: ERROR:  invalid escape string
HINT:  Escape string must be empty or one character.


Deleting deployment 'concourse-topgun-3':
  Expected task '11079' to succeed but was state is 'error'
```

debug logs:
```
E, [2017-02-09 01:50:49 #13911] [task:9669] ERROR -- DirectorJobRunner: PG::Error: ERROR:  invalid escape string
HINT:  Escape string must be empty or one character.
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `exec'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `block in execute_query'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/logging.rb:39:in `log_yield'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `execute_query'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:173:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:149:in `check_disconnect_errors'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:173:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:525:in `_execute'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:952:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:669:in `fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:139:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:47:in `block in all'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:892:in `_all'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:47:in `all'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/dns/powerdns.rb:38:in `find_dns_records_by_pattern'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/dns/powerdns.rb:42:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/dns/dns_manager.rb:107:in `block in delete_dns_for_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/dns/dns_manager.rb:105:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/dns/dns_manager.rb:105:in `delete_dns_for_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/instance_deleter.rb:35:in `block (2 levels) in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/error_ignorer.rb:9:in `with_force_check'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/instance_deleter.rb:34:in `block in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/instance_deleter.rb:22:in `delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/instance_deleter.rb:69:in `block (3 levels) in delete_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by mfine30** [comment]
@mariash is this still an issue? The error sounds similar to other errors we've seen for UTF-8 encoding issues, and I believe there was work done recently to better support that.

**Comment by mariash** [comment]
@anand do you guys still see this issue?

**Comment by mrosecrance** [comment]
I'm going to close this as it seems very stale. If it comes up again, feel free to open the issue again.
