### ISSUE TITLE
BAT test not running with UAA integrated to Director

### ISSUE THREAD

**Issue by michaellihs** [cloudfoundry/bosh#1587]
We are trying to run the BAT testsuite with a Director that uses UAA for user management.

Our Director is running on `10.244.0.5`.

Here are the ENV variables:

```
export BAT_DIRECTOR=10.244.0.5
export BAT_DIRECTOR_USER=admin
export BAT_DIRECTOR_PASSWORD=admin-password
export BAT_STEMCELL=/.../bosh-stemcell-3147-warden-boshlite-ubuntu-trusty-go_agent.tgz
export BAT_DEPLOYMENT_SPEC=/.../bosh/bat/bat.yml
export BAT_VCAP_PASSWORD=c1oudc0w
export BAT_DNS_HOST=10.244.0.5
# actually don't know what to set here...
export BOSH_KEY_PATH=
export BAT_INFRASTRUCTURE=warden
export BAT_NETWORKING=manual
```

Here is our `bat.yml`

```
---
cpi: warden_cpi
properties:
  uuid: OUR-DIRECTOR-UUID
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  pool_size: 1
  instances: 1
  second_static_ip: 10.245.0.5
  networks:
  - name: default
    gateway: 10.245.0.1
    static_ip: 10.245.0.6
    reserved:
    - 10.245.0.1
    - 10.245.0.2
    - 10.245.0.3
    - 10.245.0.4
    static:
    -10.245.0.5 - 10.245.0.50
    cloud_properties:
      name: random
```

When I now run `bundle exec rspec` I get the following output:

```
!!! EXCLUDING SYSTEM SERVICE SPECS !!!
Run options:
  include {:focus=>true}
  exclude {:type=>:os}

All examples were filtered out; ignoring {:focus=>true}
I, [2017-02-15T17:58:36.004956 #27743]  INFO -- : Running bosh command --> bundle exec bosh --non-interactive -P 1 --config /var/folders/5g/19mv6nv972d1dh_6k7gs6k7r0000gp/T/bosh_config20170215-27743-w5gkir --user admin --password admin-password target 10.244.0.5 2>&1
I, [2017-02-15T17:58:37.448158 #27743]  INFO -- : RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Target set to 'bosh_multi_vm'

I, [2017-02-15T17:58:38.624781 #27743]  INFO -- : Requirement bosh-warden-boshlite-ubuntu-trusty-go_agent-3147
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
I, [2017-02-15T17:58:38.651350 #27743]  INFO -- : Starting cleanup bosh-warden-boshlite-ubuntu-trusty-go_agent-3147

Finished in 2.66 seconds (files took 0.40738 seconds to load)
0 examples, 0 failures
bundler: failed to load command: rspec (/.../.rbenv/versions/2.0.0-p451/bin/rspec)
RuntimeError: Director request failed to '/stemcells' with status 401:
BODY:
Not authorized: '/stemcells'

  /.../bosh/bat/lib/bat/bosh_api.rb:42:in `http_get'
  /.../bosh/bat/lib/bat/bosh_api.rb:31:in `stemcells'
  /.../bosh/bat/lib/bat/requirements.rb:54:in `cleanup'
  /.../bosh/bat/spec/system/spec_helper.rb:84:in `block (2 levels) in <top (required)>'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:287:in `instance_exec'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:287:in `instance_exec_with_rescue'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:356:in `run'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `block in run'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `each'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `run'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:114:in `ensure in block in run_specs'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:114:in `block in run_specs'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in `run_specs'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
  /.../.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
  /.../.rbenv/versions/2.0.0-p451/bin/rspec:23:in `load'
  /.../.rbenv/versions/2.0.0-p451/bin/rspec:23:in `<top (required)>'
```

**Comment by mfine30** [comment]
BATS now runs with the golang CLI which has better support for UAA auth through the `BOSH_CLIENT` and `BOSH_CLIENT_SECRET` environment variables. I'd recommend giving that a try and see if you are still having issues. Feel free to start a new issue if new errors are happening with it.
