### ISSUE TITLE
`bosh errands` returns a HTTP 500 error when there're no errands

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/bosh#1598]
BOSH CLI version: BOSH 1.3262.24.0
BOSH Release: 261.2
BOSH Stemcell: 3363.1

If I run the `bosh errands` command and there're no errands on my deployment, bosh returns a `HTTP 500` error.

These are the logs from the BOSH director:

```
E, [2017-02-22 14:58:27 #22779] [] ERROR -- Director: NoMethodError - undefined method `downcase' for nil:NilClass:
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/dns/canonicalizer.rb:6:in `canonicalize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/deployment_repo.rb:31:in `create_for_attributes'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/deployment_repo.rb:25:in `find_or_create_by_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:58:in `parse_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:43:in `create_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:39:in `create_from_model'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/api/controllers/deployments_controller.rb:461:in `load_deployment_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/api/controllers/deployments_controller.rb:444:in `block in <class:DeploymentsController>'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/bin/bosh-director:37:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director:16:in `load'
/var/vcap/packages/director/bin/bosh-director:16:in `<main>'
```

**Comment by cppforlife** [comment]
do you have dns turned on or turned off?

**Comment by frodenas** [comment]
DNS is disabled for this bosh director.

BTW, now the `bosh errands` command is not returning an error, it's returning `Deployment has no available errands`. We didn't add any new deployment/release, the only change was an unfinished deployment that now has finished so might be related to https://github.com/cloudfoundry/bosh/issues/1048.

**Comment by poblin-orange** [comment]
had this issue several times. Uncomplete deployments seem to cause this.

**Comment by mfine30** [comment]
The bosh team has done significant work on the errands implementation since this issue was opened. I don't believe it should still be an issue. If it is, please reopen this github issue.
