### ISSUE TITLE
panic during parsing of sha1 during upload-stemcell

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1607]
uploading 3363.9 with information from http://bosh.io/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent

```
$ bosh us https://s3.amazonaws.com/bosh-core-stemcells/openstack/bosh-stemcell-3363.9-openstack-kvm-ubuntu-trusty-go
_agent.tgz --sha1=1cddb531c96cc4022920b169a37eda71069c87dd                                                                                                                Using environment '192.168.1.12' as client 'admin'

Task 351

08:28:01 | Update stemcell: Downloading remote stemcell (00:00:29)
08:28:30 | Update stemcell: Verifying remote stemcell (00:00:00)
            L Error: panic: Parsing multiple digest: Unable to parse digest string. Digest and algorithm key can only contain alpha-numeric characters.

goroutine 1 [running]:
panic(0x51cc80, 0xc420016580)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cloudfoundry/bosh-utils/crypto.MustParseMultipleDigest(0x7ffc0b44bbee, 0x2a, 0x10000c420039c70, 0x5ed126dd0000005d, 0x2)
        /tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/crypto/multiple_digest.go:29 +0x12e
main.MultiDigestCommand.Execute(0x7ffc0b44bba4, 0x49, 0x7ffc0b44bbee, 0x2a, 0xc42000e570, 0x0, 0x3, 0x488a01, 0x7f5ed7f47000)
        /tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/main/verify_multidigest.go:52 +0x39
main.(*MultiDigestCommand).Execute(0xc420010140, 0xc42000e570, 0x0, 0x3, 0x1, 0x3)
        <autogenerated>:1 +0x8b
github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4200180c0, 0xc42000a190, 0x3, 0x3, 0xc420066000, 0xc4200180c0, 0x7ffc0b44bb7
d, 0x0, 0x0)
        /tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x8e6
github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc4200180c0, 0xc420010140, 0x16, 0xc4200180c0, 0x4a3b01, 0xc420010140)
        /tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x74
github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags.Parse(0x516100, 0xc420010140, 0x54f8bc, 0x28, 0x5dd1a0, 0xc420016360, 0xc4200001a0)
        /tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/vendor/github.com/jessevdk/go-flags/parser.go:133 +0x4c
main.main()
        /tmp/build/020a9e9e/gopath/src/github.com/cloudfoundry/bosh-utils/main/verify_multidigest.go:29 +0x77
```

**Comment by cppforlife** [comment]
is this built from master, not 261.x?

**Comment by voelzmo** [comment]
yup, that's from master. sorry about the missing info there.

**Comment by cppforlife** [comment]
i think this is resolved now on master.
