### ISSUE TITLE
If a compilation VM is deleted, all subsequent deploys fail trying to delete that VM

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh#1631]
## Versions

- Director version 260.5.0
- GCP CPI 25.6.2

## What happened

Our GCP deployment failed when BOSH errored trying to delete a compilation VM:

```
Error: CPI error 'Bosh::Clouds::CloudError' with message 'Deleting vm 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d': Failed to delete Google Instance 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d': Google Operation 'operation-1490141348064-54b4691b76b01-081998a5-f7bf6ff0' finished with an error: Get https://www.googleapis.com/compute/v1/projects/cf-capi-ripley/zones/us-central1-a/operations/operation-1490141348064-54b4691b76b01-081998a5-f7bf6ff0?alt=json: read tcp 10.0.0.6:35018->173.194.196.95:443: read: connection reset by peer' in 'delete_vm' CPI method
```

Although the delete request failed, the VM was deleted from the IaaS a few seconds later. However, all subsequent deploys would fail trying to delete that compilation VM:

```
15:01:27 | Deleting unneeded instances: compilation-5a9659ef-be26-4bf6-8774-66c113f23115/9e07e2eb-21ca-4fc0-9db5-e46c188d407b (0) (00:00:00)
            L Error: CPI error 'Bosh::Clouds::VMNotFound' with message 'VM 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d' not found' in 'delete_vm' CPI method
```

We tried `bosh cck` which did not list the compilation VM. `deploy --fix` hit the same error. `bosh delete-vm` reported `Success` but it didn't actually remove the VM reference. In the end we had to delete the VM reference from the database.

## Logs

External GCP CPI response (didn't see stack trace in response):

```
D, [2017-03-22 00:11:18 #6044] [] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Deleting vm 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d': Failed to delete Google Instance 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d': Google Operation 'operation-1490141348064-54b4691b76b01-081998a5-f7bf6ff0' finished with an error: Get https://www.googleapis.com/compute/v1/projects/cf-capi-ripley/zones/us-central1-a/operations/operation-1490141348064-54b4691b76b01-081998a5-f7bf6ff0?alt=json: read tcp 10.0.0.6:35018-\u003e173.194.196.95:443: read: connection reset by peer","ok_to_retry":false},"log":"[File System] 2017/03/22 00:09:07 DEBUG - Reading file /var/vcap/jobs/google_cpi/config/cpi.json\n[File System] 2017/03/22 00:09:07 DEBUG - Read content<REDACTING CREDS>
```

Director Trace:

```
E, [2017-03-22 00:11:18 #6044] [] ERROR -- DirectorJobRunner: Worker thread raised exception: CPI error 'Bosh::Clouds::CloudError' with message 'Deleting vm 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d': Failed to delete Google Instance 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d': Google Operation 'operation-1490141348064-54b4691b76b01-081998a5-f7bf6ff0' finished with an error: Get https://www.googleapis.com/compute/v1/projects/cf-capi-ripley/zones/us-central1-a/operations/operation-1490141348064-54b4691b76b01-081998a5-f7bf6ff0?alt=json: read tcp 10.0.0.6:35018->173.194.196.95:443: read: connection reset by peer' in 'delete_vm' CPI method - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-260.5.0/lib/cloud/external_cpi.rb:119:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-260.5.0/lib/cloud/external_cpi.rb:88:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-260.5.0/lib/cloud/external_cpi.rb:52:in `delete_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/vm_deleter.rb:29:in `block in delete_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/error_ignorer.rb:9:in `with_force_check'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/vm_deleter.rb:28:in `delete_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/vm_deleter.rb:16:in `delete_for_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/instance_deleter.rb:27:in `block in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/event_log.rb:119:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/instance_deleter.rb:22:in `delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:98:in `destroy_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:58:in `block (3 levels) in delete_instances'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.5.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.5.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.5.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

Director trace on subsequent deployments:

```
E, [2017-03-22 15:01:27 #12146] [] ERROR -- DirectorJobRunner: Worker thread raised exception: CPI error 'Bosh::Clouds::VMNotFound' with message 'VM 'vm-ad4b77b6-a82d-400d-5dac-63ad2a73860d' not found' in 'delete_vm' CPI method - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-260.5.0/lib/cloud/external_cpi.rb:119:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-260.5.0/lib/cloud/external_cpi.rb:88:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_cpi-260.5.0/lib/cloud/external_cpi.rb:52:in `delete_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/vm_deleter.rb:29:in `block in delete_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/error_ignorer.rb:9:in `with_force_check'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/vm_deleter.rb:28:in `delete_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/vm_deleter.rb:16:in `delete_for_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/instance_deleter.rb:27:in `block in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/instance_deleter.rb:22:in `delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.5.0/lib/bosh/director/instance_deleter.rb:69:in `block (3 levels) in delete_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.5.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.5.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.5.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by dpb587-pivotal** [comment]
Thanks for the well-documented bug report! This is [fixed](https://github.com/cloudfoundry/bosh/commit/6f49a757ffe25956e520c15ce7e8b27b5105b325) in director [v261](https://github.com/cloudfoundry/bosh/releases/tag/v261).
