### ISSUE TITLE
BOSH deploy fails to generate diff under certain circumstances

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/bosh#1668]
If I deploy a bosh release that has a manifest snippet like:

```yaml
---
instance_groups:
- instances: 1
  jobs:
  - name: broker
    properties:
      service_catalog:
        plans:
        - name: cache-small
          description: "Blah"
        - name: cache-medium
          description: "Blah"
        - name: cache-large
          description: "Blah"
    release: on-demand-service-broker
```

After a successful deployment - I go and modify the manifest to look like:

```yaml
---
instance_groups:
- instances: 1
  jobs:
  - name: broker
    properties:
      service_catalog:
        plans:
        - nil
        - nil
        - name: cache-large
          description: "Blah"
    release: on-demand-service-broker
```

When I redeploy, I see this following error in the BOSH deployment diff (but deployment continues):

```
Detecting deployment changes
----------------------------
Unable to diff manifest: #<NoMethodError: undefined method `[]' for nil:NilClass>
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:130:in `block (2 levels) in compare_arrays'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:130:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:130:in `all?'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:130:in `block in compare_arrays'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:126:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:126:in `compare_arrays'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:83:in `block in diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `each_pair'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:87:in `block in diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `each_pair'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:87:in `block in diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `each_pair'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:142:in `block in compare_arrays'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:126:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:126:in `compare_arrays'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:83:in `block in diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `each_pair'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:142:in `block in compare_arrays'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:126:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:126:in `compare_arrays'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:83:in `block in diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `each_pair'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/changeset.rb:74:in `diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/manifest/manifest.rb:46:in `diff'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/api/controllers/deployments_controller.rb:400:in `block in <class:DeploymentsController>'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/bin/bosh-director:37:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director:16:in `load'
/var/vcap/packages/director/bin/bosh-director:16:in `<main>'
```

This hides real diff information, making it difficult to have confidence in deployment changes under these circumstances.

We are using bosh `BOSH 1.3262.24.0`

**Comment by h4xnoodle** [comment]
I believe this fixes your issue: https://github.com/cloudfoundry/bosh/commit/5d0e4832cf665c8b2b04996b7f79c8d0bcb0b001

We had the same, and we noticed it wasn't happening anymore. However, having blank plans still feels incorrect!

**Comment by dpb587-pivotal** [comment]
Closing - looks like this was fixed from [v262+](https://github.com/cloudfoundry/bosh/releases/tag/v262).

Thanks @h4xnoodle for finding the related commit!
