### ISSUE TITLE
`bosh upload release <tarball>` fails to upload releases with no packages created by bosh 2 cli

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry/bosh#1721]
Steps to reproduce:
- create a bosh release with no packages
- `bosh-cli create-release --tarball`
- `bosh upload release <tarball>` fails with following message:

```
$ bosh -n upload release my-release.tgz
Acting as client 'client' on 'bosh'
RSA 1024 bit CA certificates are loaded due to old openssl compatibility

Verifying manifest...
Extract manifest                                             OK
Manifest exists                                              OK
Release name/version                                         OK
File exists and readable                                     OK
bundler: failed to load command: bosh (/path/to/bosh)
NoMethodError: undefined method `size' for nil:NilClass
  /path/to/ruby/2.3.0/gems/bosh_cli-1.3262.26.0/lib/cli/release_tarball.rb:272:in `validate_packages'
  /path/to/ruby/2.3.0/gems/bosh_cli-1.3262.26.0/lib/cli/release_tarball.rb:237:in `perform_validation'
  /path/to/ruby/2.3.0/gems/bosh_cli-1.3262.26.0/lib/cli/validation.rb:18:in `validate'
  ...
```

@cppforlife is this an expected incompatibility between the go and ruby CLIs? We are not sure which CLI to fix.

cc: @alamages

**Comment by cppforlife** [comment]
@jamesjoshuahill you may have to update your version of bosh director. it had an unfortunate bug in this scenario.
