### ISSUE TITLE
`bosh clean-up --all` outputs error message when deleting stemcells

### ISSUE THREAD

**Issue by cdutra** [cloudfoundry/bosh#1819]
bosh version: 263.2.0
bosh aws cpi: v67

I have to AZs configures each with an AWS CPI in different region when running the afore mentiones command (after deleting all deployments) the task errors out, however the stemcells were deleted.

Output:
```
Task 169

Task 169 | 21:18:42 | Deleting releases: certification/0+dev.3
Task 169 | 21:18:42 | Deleting releases: os-conf/11
Task 169 | 21:18:42 | Deleting packages: certification/100bedf6f31da1a4693c446f1ea93348ea7a7a9d
Task 169 | 21:18:42 | Deleting jobs: disable_agent/7138085404a3442d3d0b6315287d0d9698ff119a
Task 169 | 21:18:42 | Deleting packages: certification/100bedf6f31da1a4693c446f1ea93348ea7a7a9d (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: simple/b90115bc3ede0f673311071cb997cd57cd6c4e92
Task 169 | 21:18:42 | Deleting jobs: disable_agent/7138085404a3442d3d0b6315287d0d9698ff119a (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: enable_ipv6/05dbeb548579bc5ff9245cbd91e81c740ea3144c
Task 169 | 21:18:42 | Deleting jobs: simple/b90115bc3ede0f673311071cb997cd57cd6c4e92 (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: enable_ipv6/05dbeb548579bc5ff9245cbd91e81c740ea3144c (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: limits_not_recommended/e039b1b7c85c2d9edd13647e405a7ec2ba9b1a66
Task 169 | 21:18:42 | Deleting releases: certification/0+dev.3 (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: limits_not_recommended/e039b1b7c85c2d9edd13647e405a7ec2ba9b1a66 (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: login_banner/83fdcd1fa5df70c0bda867b3b873f6c4fdf64a90 (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: search_domain/e6e8b285838d02c2d9c1b8c5df16d7977b0532e8 (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: tcp_keepalive/f8062f5cb07cb29df43b007948ae05515e69fa2b (00:00:00)
Task 169 | 21:18:42 | Deleting jobs: user_add/ed4bc119ddc3a47f3231c81f7ccb5c2c8d05e9ce (00:00:00)
Task 169 | 21:18:42 | Deleting releases: os-conf/11 (00:00:00)
Task 169 | 21:18:42 | Deleting stemcells: bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3312.18
Task 169 | 21:18:42 | Deleting stemcells: bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3421.11 (00:00:09)
Task 169 | 21:18:51 | Deleting stemcells: bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3312.18 (00:00:09) (00:00:13)
                    L Error: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "stemcells" WHERE ("id" = 3))
Task 169 | 21:18:55 | Deleting stemcells: bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3421.11 (00:00:13)
                    L Error: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "stemcells" WHERE ("id" = 1))
Task 169 | 21:18:55 | Error: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "stemcells" WHERE ("id" = 3))

Task 169 Started  Tue Oct 24 21:18:42 UTC 2017
Task 169 Finished Tue Oct 24 21:18:55 UTC 2017
Task 169 Duration 00:00:13
Task 169 error

Capturing task '169' output:
  Expected task '169' to succeed but state is 'error'

Exit code 1
```

**Comment by FlorianNachtigall** [comment]
We are experiencing a similar issue calling `delete_vm` with bosh 264.7.0 and an aws-cpi. 
```
$ bosh -e bosh -d service delete-vm  i-0789b567f85f575e1
...
Task 1554912 | 16:53:26 | Error: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "vms" WHERE ("id" = 34082))
...
Task 1554912 Duration 00:00:00
Task 1554912 error

Deleting VM 'i-0789b567f85f575e1':
  Expected task '1554912' to succeed but state is 'error'

Exit code 1
```
The cpi successfully deletes the vm, but the bosh director errors out removing the entry from the database as it seems to already have been removed. See the following debug task log for details:

```
I, [2018-02-21T16:53:26.094383 #31747]  INFO -- [req_id cpi-183315]: i-0789b567f85f575e1 is now terminated, took 158.608809655s
I, [2018-02-21T16:53:26.094470 #31747]  INFO -- [req_id cpi-183315]: Finished delete_vm in 163.11 seconds
, exit_status: pid 31747 exit 0
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001489s) SELECT * FROM "vms" WHERE (("instance_id" = 9039) AND ("active" IS TRUE)) LIMIT 1
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001074s) BEGIN
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001056s) COMMIT
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001227s) DELETE FROM "vms" WHERE "id" = 34082
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001119s) BEGIN
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001347s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (24263354, '2018-02-21 16:53:26.143050+0000', 'admin', 'delete', 'vm', 'i-0789b567f85f575e1', 'Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "vms" WHERE ("id" = 34082))', '1554912', 'service', 'docker/bb124fd5-f0eb-49da-aba4-8127374bf018', '{}') RETURNING *
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.002637s) COMMIT
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001087s) BEGIN
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001253s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1519232006,"error":{"code":100,"message":"Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM \"vms\" WHERE (\"id\" = 34082))"}}
') WHERE ("id" = 1554912)
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.002502s) COMMIT
E, [2018-02-21T16:53:26 #31722] [task:1554912] ERROR -- DirectorJobRunner: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "vms" WHERE ("id" = 34082))
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/sequel-4.36.0/lib/sequel/model/base.rb:1922:in `_delete'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/sequel-4.36.0/lib/sequel/model/base.rb:1384:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_deleter.rb:29:in `delete_for_instance'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/delete_vm.rb:25:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001161s) SELECT * FROM "tasks" WHERE ("id" = 1554912) LIMIT 1
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001039s) BEGIN
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.001381s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2018-02-21 16:53:26.160897+0000', "description" = 'delete vm i-0789b567f85f575e1', "result" = 'Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "vms" WHERE ("id" =...', "output" = '/var/vcap/store/director/tasks/1554912', "checkpoint_time" = '2018-02-21 16:53:10.863581+0000', "type" = 'delete_vm', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2018-02-21 16:50:40.589087+0000', "context_id" = '', "event_output" = '{"time":1519232006,"error":{"code":100,"message":"Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM \"vms\" WHERE (\"id\" = 34082))"}}
', "result_output" = '' WHERE ("id" = 1554912)
D, [2018-02-21T16:53:26 #31722] [task:1554912] DEBUG -- DirectorJobRunner: (0.002606s) COMMIT
I, [2018-02-21T16:53:26 #31722] []  INFO -- DirectorJobRunner: Task took 2 minutes 45.584689741000005 seconds to process.
```

**Comment by dpb587-pivotal** [comment]
I vaguely recall us doing some work around this a few months ago, but not seeing a specific story. Has anyone seen this issue recently?

**Comment by mrosecrance** [comment]
Going to close as stale and possibly fixed
