### ISSUE TITLE
`no implicit conversion of nil into String` when Director has no manifest for deployment

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/bosh#1854]
This is the error we were seeing while trying to `bosh recreate` or `bosh stop` an instance within a failed deployment.

```
bosh recreate consul -d cf
Using environment 'https://<ip>:25555' as client 'admin'

Using deployment 'cf'

Continue? [yN]: y

Task 326

Task 326 | 00:23:16 | Error: no implicit conversion of nil into String

Task 326 Started  Tue Dec  5 00:23:16 UTC 2017
Task 326 Finished Tue Dec  5 00:23:16 UTC 2017
Task 326 Duration 00:00:00
Task 326 error
```

Bosh team advised that this was due to it being the first deploy of this deployment and there not being a successful manifest saved for it.

## Steps to Reproduce
1. `bosh deploy` a new deployment with something in it that will fail
1. Try to `bosh recreate` one of the instances in the deployment

Main thing that would be nice would just be a more friendly error message.

## bosh env output
```
Using environment 'https://35.192.147.95:25555' as client 'admin'

Name      bosh-ripley
UUID      c2038875-0a86-40bb-8d25-7c822cf9b340
Version   263.2.0 (00000000)
CPI       google_cpi
Features  compiled_package_cache: disabled
          config_server: disabled
          dns: disabled
          snapshots: disabled
User      admin
```

**Comment by dpb587-pivotal** [comment]
@tcdowney have a director version and just the stacktrace from the end of `bosh task --debug 326`?

**Comment by tcdowney** [comment]
@dpb587-pivotal here's the debug output:
[326_stacktace.txt](https://github.com/cloudfoundry/bosh/files/1532229/326_stacktace.txt)

**Comment by williammartin** [comment]
I am also seeing this on:

```
Using environment '192.168.50.6' as client 'admin'

Name      Bosh Lite Director
UUID      b6b85589-82b8-476d-9341-b51062feb96d
Version   264.1.0 (00000000)
CPI       warden_cpi
Features  compiled_package_cache: disabled
          config_server: disabled
          dns: disabled
          snapshots: disabled
User      admin

Succeeded
```

bosh task --debug output:

```
Using environment '192.168.50.6' as client 'admin'

Task 120

I, [2017-12-14T11:51:23.360134 #2910] [0x2b1ab95d2f4c]  INFO -- TaskHelper: Director Version: 264.1.0
I, [2017-12-14T11:51:23.360178 #2910] [0x2b1ab95d2f4c]  INFO -- TaskHelper: Enqueuing task: 120
I, [2017-12-14T11:51:23 #650271] []  INFO -- DirectorJobRunner: Looking for task with task id 120
D, [2017-12-14T11:51:23 #650271] [] DEBUG -- DirectorJobRunner: (0.000337s) SELECT * FROM "tasks" WHERE "id" = 120
I, [2017-12-14T11:51:23 #650271] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>120, :state=>"processing", :timestamp=>2017-12-14 11:51:23 UTC, :description=>"create deployment", :result=>nil, :output=>"/var/vcap/store/director/tasks/120", :checkpoint_time=>2017-12-14 11:51:23 UTC, :type=>"update_deployment", :username=>"admin", :deployment_name=>"cf", :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
I, [2017-12-14T11:51:23 #650271] []  INFO -- DirectorJobRunner: Running from worker 'worker_3' on director/3cde8d74-66c1-4fdc-5850-0a770078f2e8 (127.0.0.1)
I, [2017-12-14T11:51:23 #650271] []  INFO -- DirectorJobRunner: Starting task: 120
I, [2017-12-14T11:51:23 #650271] [task:120]  INFO -- DirectorJobRunner: Creating job
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000271s) SELECT * FROM "tasks" WHERE "id" = 120
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000269s) SELECT * FROM "tasks" WHERE "id" = 120
I, [2017-12-14T11:51:23 #650271] [task:120]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>120, :state=>"processing", :timestamp=>2017-12-14 11:51:23 UTC, :description=>"create deployment", :result=>nil, :output=>"/var/vcap/store/director/tasks/120", :checkpoint_time=>2017-12-14 11:51:23 UTC, :type=>"update_deployment", :username=>"admin", :deployment_name=>"cf", :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000205s) BEGIN
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000371s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2017-12-14 11:51:23.648408+0000', "description" = 'create deployment', "result" = NULL, "output" = '/var/vcap/store/director/tasks/120', "checkpoint_time" = '2017-12-14 11:51:23.648534+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cf', "started_at" = '2017-12-14 11:51:23.648481+0000', "event_output" = '', "result_output" = '', "context_id" = '' WHERE ("id" = 120)
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000730s) COMMIT
I, [2017-12-14T11:51:23 #650271] [task:120]  INFO -- DirectorJobRunner: Reading deployment manifest
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000676s) SELECT * FROM "tasks" WHERE "id" = 120
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000346s) BEGIN
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000489s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2017-12-14 11:51:23.655477+0000', 'admin', 'update', 'deployment', NULL, 'no implicit conversion of nil into String', '120', NULL, NULL, '{}') RETURNING *
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000713s) COMMIT
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000312s) BEGIN
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000357s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1513252283,"error":{"code":100,"message":"no implicit conversion of nil into String"}}
') WHERE ("id" = 120)
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000593s) COMMIT
E, [2017-12-14T11:51:23 #650271] [task:120] ERROR -- DirectorJobRunner: no implicit conversion of nil into String
/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/psych.rb:377:in `parse'
/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/psych.rb:252:in `load'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:28:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000182s) SELECT * FROM "tasks" WHERE ("id" = 120) LIMIT 1
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000202s) BEGIN
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.000348s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-12-14 11:51:23.662943+0000', "description" = 'create deployment', "result" = 'no implicit conversion of nil into String', "output" = '/var/vcap/store/director/tasks/120', "checkpoint_time" = '2017-12-14 11:51:23.648534+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cf', "started_at" = '2017-12-14 11:51:23.648481+0000', "event_output" = '{"time":1513252283,"error":{"code":100,"message":"no implicit conversion of nil into String"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 120)
D, [2017-12-14T11:51:23 #650271] [task:120] DEBUG -- DirectorJobRunner: (0.001053s) COMMIT
I, [2017-12-14T11:51:23 #650271] []  INFO -- DirectorJobRunner: Task took 0.019790606 seconds to process.
```

When I do `bosh manifest`, the task reports it succeeded but I don't get the manifest back.

**Comment by pivotal-jamil-shamy** [comment]
Did this deployment ever succeed ? When asking for the manifest and it's returns nothing is a symptom for that
________________________________

**Comment by williammartin** [comment]
No, it failed. I'm just reiterating that this issue (the error message returned) is not so good. Thanks.

**Comment by jfmyers9** [comment]
Going to close this issue as we are unlikely to fix this issue in the short term.

We do have long term features on the product roadmap to refactor how we deal with manifests and failed deploys which we are hoping will prevent this occurring in the future.

Please feel free to reopen this issue if you have further questions.
