### ISSUE TITLE
BOSH director passes wrong disk cid to CPI on "attach-disk" on Azure

### ISSUE THREAD

**Issue by gossion** [cloudfoundry/bosh#1857]
This is similar to issue #1841, but since that issue is already closed, I would like to open a new one.

===

I faced an error when calling attach-disk on Azure CF.

command:
```bash
bosh -e azure -d cf attach-disk nats/d4afe240-ec01-4d27-9b9b-aeac38cf64f5 caching:None;disk_name:bosh-disk-data-91bf7a1b-ada2-47d3-80bd-b07696bb60bf;resource_group_name:guwe1205
```

The action failed with error:
```
02:04:00 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'attach_disk - Failed to create the managed disk for caching:None. Error: #<Bosh::Clouds::CloudError: Invalid data disk name (version 1) caching:None>
```

From its debug log I saw that wrong disk CID `caching:None` was passed to CPI, it should be `caching:None;disk_name:bosh-disk-data-91bf7a1b-ada2-47d3-80bd-b07696bb60bf;resource_group_name:guwe1205`
```
D, [2017-12-07T02:03:57 #35848] [task:435] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-436486] request: {"method":"attach_disk","arguments":["agent_id:6f751bbf-dd70-4d23-815d-444e83eee368;resource_group_name:guwe1205","caching:None"],"context":{"director_uuid":"c9a5fa06-3db6-4045-a814-c20241191d72","request_id":"cpi-436486"}} with command: /var/vcap/jobs/azure_cpi/bin/cpi
D, [2017-12-07T02:04:00 #35848] [task:435] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-436486] response: {"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"attach_disk - Failed to create the managed disk for caching:None. Error: #<Bosh::Clouds::CloudError: Invalid data disk name (version 1) caching:None>\n/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/helpers.rb:163:in `cloud_error'\n/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/disk_id.rb:133:in `parse_storage_account_v1'\n/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/disk_id.rb:101:in `storage_account_name'\n/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:388:in `block in attach_disk'\n/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:...
```

my bosh cli version: 2.0.28-cb77557-2017-07-11T23:04:21Z
my bosh director: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-264.1-ubuntu-trusty-3468.1-20171109-004207-628092428-20171109004211.tgz?versionId=46RkXfd52MvTfE_IXpC.P9x1Tfv09qkB

**Comment by sauravmndl** [comment]
Thanks for opening this.

**Comment by gossion** [comment]
It is not a bosh issue. 
`;` is a sh command seperator, I should `'` or `"` to wrap the string. like 
```
bosh -e azure -d cf attach-disk nats/d4afe240-ec01-4d27-9b9b-aeac38cf64f5 'caching:None;disk_name:bosh-disk-data-91bf7a1b-ada2-47d3-80bd-b07696bb60bf;resource_group_name:guwe1205'
```

close this issue.
