### ISSUE TITLE
Multi-layer deployment failing very late because of invalid `cloud-config`

### ISSUE THREAD

**Issue by degaurab** [cloudfoundry/bosh#2001]
Hi BOSH,
When we are uploading partially blank cloud-config, deployment fail with blank information. In case of multi-layer deployment it fails really late.

Ex. cloud-config causing issues:
```
networks:
- name: ""
  type: manual
  subnets:
  - range: ""
    gateway: ""
    dns:
    - 10.193.53.2
    azs:
    - az1
    cloud_properties:
      name: ""
```

### We should perform some basic validation when uploading cloud-config (ex. no blank values). 
Error is also very ambiguous as if you try to get cloud-config will get the default cloud-config which is valid.

Until you check each one of the cloud-config its difficult to trace down. 

stacktrace:
```
[2018-07-04T18:27:51 #12741] [task:1425] ERROR -- DirectorJobRunner: Could not auto-detect IP version for ''.
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/netaddr-1.5.1/lib/ip_math.rb:54:in `detect_ip_version'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/netaddr-1.5.1/lib/cidr.rb:157:in `create'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/manual_network_subnet.rb:15:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/manual_network.rb:18:in `block in parse'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/manual_network.rb:17:in `each'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/manual_network.rb:17:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:62:in `block in parse_networks'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:57:in `map'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:57:in `parse_networks'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:14:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/planner_factory.rb:84:in `parse_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/planner_factory.rb:45:in `create_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:75:in `block (2 levels) in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:73:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock.rb:79:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:59:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

cc @outofmem0ry

**Comment by voelzmo** [comment]
Hey @degaurab, thanks for raising this issue!

For my understanding: When you're talking about "multi-layer" deployment, you're referring to a deployment with multiple, named cloud-configs?

If that is the case, there might be a few different issues hidden in your report, let me try to unpack this:
* There should be validation when uploading a cloud-config (probably runtime- and cpi-config as well, I guess), because any errors currently show only up during deployment when the config is used.
* When you're using multiple cloud-configs, there is some confusion around what `bosh cloud-config` shows: Is it a merged version? Is it just one of them?

Is my understanding of those issues correct?

**Comment by freddesbiens** [comment]
We definitely need to add validations when operators upload a cloud config. 
Closing and re-opening this issue to have a Tracker story created.
