### ISSUE TITLE
As a CPI dev, I want a clear response about registry InstanceNotFound error

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh#2003]
It happened after a director without registry updates to deploy a registry instance.

When director invoked `detach_disk` for update deployments, CPI got a 500 error when fetching agent settings. Because this VM has not existed in registry.

registry logs:
```
I, [2018-07-11T06:45:22.395639 #1]  INFO -- : BOSH Registry starting...
I, [2018-07-11T06:45:22.395762 #1]  INFO -- : HTTP server is starting on port 25777...
E, [2018-07-11T07:51:15.344531 #1] ERROR -- : Can't find instance '57532573' (Bosh::Registry::InstanceNotFound)
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/bosh-registry-0.0.0/lib/bosh/registry/instance_manager.rb:64:in `get_instance'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/bosh-registry-0.0.0/lib/bosh/registry/instance_manager.rb:29:in `read_settings'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/bosh-registry-0.0.0/lib/bosh/registry/api_controller.rb:25:in `block in <class:ApiController>'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/data/packages/registry/e6ee018b838fbc40109d29732025b7e7ca56dec3/gem_home/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
```

But 500 error response with `{"status":"error"}` is not clear from registry side. How about to use 404 and clear status message?

Thanks.

**Comment by freddesbiens** [comment]
We recently merged changes that enable registry-less operation for BOSH. 

The changes can be found in the following versions of our components:
- v268.3.0+ of the director
- v170.6+ of the Xenial stemcells
- v5.4.0+ of the BOSH CLI

You need as well a compatible version of your CPI for this to work. We released the AWS one recently and the OpenStack one is not far behind. Azure will come at a later date.

Closing this for now. Please let us know if you have further problems.

**Comment by edwardstudy** [comment]
@freddesbiens. That's great to remove registry. Can you tell me where bosh-agent to get its settings from without a registry?

Thanks.
