### ISSUE TITLE
Misleading error message when compilation VM cannot be pinged

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2009]
Director version: 266.4.0
CPI: OpenStack CPI

**Problem**
We setup a simple scenario where security groups were configured incorrectly, such that the compilation VM couldn't be successfully pinged by the director.

**Expected**
Our beloved message of "timed out pinging after 600 seconds" which indicates exactly the problem we had

**Actual**
```
E, [2018-07-20T10:49:20.912205 #28964] [task:8] ERROR -- DirectorJobRunner: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "vms" WHERE ("id" = 2))
```
No error regarding 600 second timeout was shown.

For the record: Here's some excerpt from the logs, if you like, you can get the entire debug log.

At first, the error shows up in the debug log as expected:
```
E, [2018-07-20T10:49:18.865715 #28964] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Timed out pinging to 5e2ee160-44e0-4655-841c-6f88dbf29a1a after 600 seconds - /var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:219:in `rescue in wait_until_ready'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:225:in `wait_until_ready'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/steps/create_vm_step.rb:56:in `update_metadata'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/steps/create_vm_step.rb:38:in `perform'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:39:in `block in run_agenda'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:36:in `each'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:36:in `run_agenda'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:24:in `block (4 levels) in run'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:52:in `with_thread_name'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:18:in `block (3 levels) in run'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

It seems, however, this is just logged and not shown to the user. Instead the `create_missing_vm` method tries to clean up and fails while doing this:
```
D, [2018-07-20T10:49:20.843665 #28964] [compile_package(golang/91909d54d203acc915a4392b52c37716e15b5aff, bosh-openstack-kvm-ubuntu-xenial-go_agent/97)] DEBUG -- DirectorJobRunner: (0.000245s) (conn: 47140840322220) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1532083760,"stage":"Compiling packages","tags":[],"total":2,"task":"golang/91909d54d203acc915a4392b52c37716e15b5aff","index":1,"state":"failed","progress":100,"data":{"error":"Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM \"vms\" WHERE (\"id\" = 2))"}}
') WHERE ("id" = 8)
D, [2018-07-20T10:49:20.844483 #28964] [compile_package(golang/91909d54d203acc915a4392b52c37716e15b5aff, bosh-openstack-kvm-ubuntu-xenial-go_agent/97)] DEBUG -- DirectorJobRunner: (0.000718s) (conn: 47140840322220) COMMIT
E, [2018-07-20T10:49:20.844623 #28964] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "vms" WHERE ("id" = 2)) - /var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2076:in `_delete'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:1528:in `delete'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2131:in `_destroy_delete'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2115:in `block in _destroy'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:1382:in `around_destroy'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2109:in `_destroy'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:1543:in `block (2 levels) in destroy'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2372:in `block in checked_transaction'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:224:in `_transaction'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2372:in `checked_transaction'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:1543:in `block in destroy'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2360:in `checked_save_failure'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:1543:in `destroy'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/steps/delete_vm_step.rb:33:in `perform'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_deleter.rb:38:in `block in delete_vms'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_deleter.rb:33:in `each'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_deleter.rb:33:in `delete_vms'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_deleter.rb:15:in `delete_for_instance'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_deleter.rb:29:in `block in delete_instance_plan'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:125:in `advance_and_track'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_deleter.rb:23:in `delete_instance_plan'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:125:in `destroy_instance'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:60:in `rescue in with_reused_vm'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:50:in `with_reused_vm'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:130:in `prepare_vm'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:81:in `block in compile_package'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock.rb:79:in `lock'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:74:in `compile_package'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:233:in `block (2 levels) in process_task'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:231:in `block in process_task'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:52:in `with_thread_name'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:227:in `process_task'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:191:in `block (4 levels) in compile_packages'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/data/packages/director/990209ea040f1d524d77533d89eceb1f5aa6348a/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by dpb587-pivotal** [comment]
I think this was the fixed in [v266.6.0](https://github.com/cloudfoundry/bosh/releases/tag/v266.6.0) via [Story #158130962](https://www.pivotaltracker.com/n/projects/956238/stories/158130962).

 > Fixed double deletion of compilation VMs

**Comment by voelzmo** [comment]
Seems like it, thanks! This was observed on a colleague's installation who just used bosh-deployment to set it up. Can we update bosh-deployment with the latest release?

**Comment by dpb587-pivotal** [comment]
Yeah, we should update bosh-deployment.

cc @mfine30 we may not want to block updating bosh-deployment's `bosh` on some of those other CI-related stories if they'll take a little while. Might see similar future stories reporting bugs that have already been fixed.
