### ISSUE TITLE
Possible race condition when uploading a stemcell in parallel that doesn't exist.

### ISSUE THREAD

**Issue by Changdrew** [cloudfoundry/bosh#2038]
**Describe the bug**
Possible race condition when uploading a stemcell in parallel that doesn't exist.

**To Reproduce**
Targeting a bosh director with no stemcells, run this command:
```
for i in {1..2}; do bosh us https://s3.amazonaws.com/bosh-gce-light-stemcells/light-bosh-stemcell-3586.36-google-kvm-ubuntu-trusty-go_agent.tgz & done
```
The above command results in this error:
```
Task 10532 | 17:17:24 | Update stemcell: Save stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 (stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3) (00:00:00)
                     L Error: name and version and cpi unique
Task 10532 | 17:17:24 | Error: name and version and cpi unique

Task 10532 Started  Wed Aug 22 17:15:56 UTC 2018
Task 10532 Finished Wed Aug 22 17:17:24 UTC 2018
Task 10532 Duration 00:01:28
Task 10532 error

Uploading remote stemcell 'https://s3.amazonaws.com/bosh-gce-light-stemcells/light-bosh-stemcell-3586.36-google-kvm-ubuntu-trusty-go_agent.tgz':
  Expected task '10532' to succeed but state is 'error'

Exit code 1
```

**Expected behavior**
No error.

**Logs**
Logs from `bosh task 10532 --debug`:
```
Task 10532

I, [2018-08-22T17:15:55.922173 #6571] [0x2ac96014cf54]  INFO -- TaskHelper: Director Version: 265.2.0
I, [2018-08-22T17:15:55.922280 #6571] [0x2ac96014cf54]  INFO -- TaskHelper: Enqueuing task: 10532
I, [2018-08-22T17:15:56 #962] []  INFO -- DirectorJobRunner: Looking for task with task id 10532
D, [2018-08-22T17:15:56 #962] [] DEBUG -- DirectorJobRunner: (0.000372s) SELECT * FROM "tasks" WHERE "id" = 10532
I, [2018-08-22T17:15:56 #962] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>10532, :state=>"processing", :timestamp=>2018-08-22 17:15:55 UTC, :description=>"create stemcell", :result=>nil, :output=>"/var/vcap/store/director/tasks/10532", :checkpoint_time=>2018-08-22 17:15:56 UTC, :type=>"update_stemcell", :username=>"admin", :deployment_name=>nil, :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
I, [2018-08-22T17:15:56 #962] []  INFO -- DirectorJobRunner: Running from worker 'worker_10' on director/d69706cc-9f13-480f-41a1-556d86e3fbbe (127.0.0.1)
I, [2018-08-22T17:15:56 #962] []  INFO -- DirectorJobRunner: Starting task: 10532
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Creating job
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000340s) SELECT * FROM "tasks" WHERE "id" = 10532
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000329s) SELECT * FROM "tasks" WHERE "id" = 10532
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>10532, :state=>"processing", :timestamp=>2018-08-22 17:15:55 UTC, :description=>"create stemcell", :result=>nil, :output=>"/var/vcap/store/director/tasks/10532", :checkpoint_time=>2018-08-22 17:15:56 UTC, :type=>"update_stemcell", :username=>"admin", :deployment_name=>nil, :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000203s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000487s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2018-08-22 17:15:56.276220+0000', "description" = 'create stemcell', "result" = NULL, "output" = '/var/vcap/store/director/tasks/10532', "checkpoint_time" = '2018-08-22 17:15:56.276412+0000', "type" = 'update_stemcell', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2018-08-22 17:15:56.276337+0000', "event_output" = '', "result_output" = '', "context_id" = '' WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.017414s) COMMIT
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Processing update stemcell
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001227s) SELECT * FROM "configs" WHERE ("id" IN (SELECT max("id") FROM "configs" WHERE ("type" = 'cpi') GROUP BY "name"))
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Update stemcell
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000117s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000396s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Downloading remote stemcell","index":1,"state":"started","progress":0}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001587s) COMMIT
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Downloading remote stemcell
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Downloading remote stemcell from https://s3.amazonaws.com/bosh-gce-light-stemcells/light-bosh-stemcell-3586.36-google-kvm-ubuntu-trusty-go_agent.tgz
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000158s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000464s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Downloading remote stemcell","index":1,"state":"finished","progress":100}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001644s) COMMIT
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000125s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000283s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Extracting stemcell archive","index":2,"state":"started","progress":0}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001219s) COMMIT
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Extracting stemcell archive
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000150s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000383s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Extracting stemcell archive","index":2,"state":"finished","progress":100}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001648s) COMMIT
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000162s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000342s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Verifying stemcell manifest","index":3,"state":"started","progress":0}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.047990s) COMMIT
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Verifying stemcell manifest
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Found stemcell image 'bosh-google-kvm-ubuntu-trusty-go_agent/3586.36', cloud properties are {"architecture"=>"x86_64", "container_format"=>"bare", "disk"=>3072, "disk_format"=>"rawdisk", "hypervisor"=>"kvm", "infrastructure"=>"google", "name"=>"bosh-google-kvm-ubuntu-trusty-go_agent", "os_distro"=>"ubuntu", "os_type"=>"linux", "raw_disk_sha1"=>"0bd87fc26402617e43a75346b4adb77a6d2fe061", "root_device_name"=>"/dev/sda1", "source_url"=>"https://storage.googleapis.com/bosh-gce-raw-stemcells/bosh-stemcell-3586.36-google-kvm-ubuntu-trusty-go_agent-raw-1534353681.tar.gz", "version"=>"3586.36"}
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Verifying stemcell image
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000151s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000499s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Verifying stemcell manifest","index":3,"state":"finished","progress":100}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001586s) COMMIT
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000481s) SELECT * FROM "configs" WHERE ("id" IN (SELECT max("id") FROM "configs" WHERE ("type" = 'cpi') GROUP BY "name"))
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-383255] request: {"method":"info","arguments":[],"context":{"director_uuid":"ea61d65c-7f85-4148-bcc4-8204bbaf7c29","request_id":"cpi-383255"}} with command: /var/vcap/jobs/google_cpi/bin/cpi
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-383255] response: {"result":{"stemcell_formats":["google-light","google-rawdisk"]},"error":null,"log":""}, err: , exit_status: pid 1017 exit 0
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000151s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000465s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Checking if this stemcell already exists","index":4,"state":"started","progress":0}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001724s) COMMIT
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Checking if this stemcell already exists
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000423s) SELECT * FROM "configs" WHERE ("id" IN (SELECT max("id") FROM "configs" WHERE ("type" = 'cpi') GROUP BY "name"))
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000575s) SELECT * FROM "stemcells" WHERE (("name" = 'bosh-google-kvm-ubuntu-trusty-go_agent') AND ("version" = '3586.36'))
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000121s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000317s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Checking if this stemcell already exists","index":4,"state":"finished","progress":100}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001496s) COMMIT
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000129s) BEGIN
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000337s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 to the cloud","index":5,"state":"started","progress":0}
') WHERE ("id" = 10532)
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001568s) COMMIT
I, [2018-08-22T17:15:56 #962] [task:10532]  INFO -- DirectorJobRunner: Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 to the cloud
D, [2018-08-22T17:15:56 #962] [task:10532] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-548902] request: {"method":"create_stemcell","arguments":["/var/vcap/data/tmp/director/stemcell20180822-962-brklmo/image",{"architecture":"x86_64","container_format":"bare","disk":3072,"disk_format":"rawdisk","hypervisor":"kvm","infrastructure":"google","name":"bosh-google-kvm-ubuntu-trusty-go_agent","os_distro":"ubuntu","os_type":"linux","raw_disk_sha1":"0bd87fc26402617e43a75346b4adb77a6d2fe061","root_device_name":"/dev/sda1","source_url":"https://storage.googleapis.com/bosh-gce-raw-stemcells/bosh-stemcell-3586.36-google-kvm-ubuntu-trusty-go_agent-raw-1534353681.tar.gz","version":"3586.36"}],"context":{"director_uuid":"ea61d65c-7f85-4148-bcc4-8204bbaf7c29","request_id":"cpi-548902"}} with command: /var/vcap/jobs/google_cpi/bin/cpi
D, [2018-08-22T17:16:26 #962] [task:10532-checkpoint] DEBUG -- DirectorJobRunner: (0.000158s) BEGIN
D, [2018-08-22T17:16:26 #962] [task:10532-checkpoint] DEBUG -- DirectorJobRunner: (0.000405s) UPDATE "tasks" SET "checkpoint_time" = '2018-08-22 17:16:26.277390+0000' WHERE ("id" = 10532)
D, [2018-08-22T17:16:26 #962] [task:10532-checkpoint] DEBUG -- DirectorJobRunner: (0.001684s) COMMIT
D, [2018-08-22T17:16:56 #962] [task:10532-checkpoint] DEBUG -- DirectorJobRunner: (0.000125s) BEGIN
D, [2018-08-22T17:16:56 #962] [task:10532-checkpoint] DEBUG -- DirectorJobRunner: (0.000401s) UPDATE "tasks" SET "checkpoint_time" = '2018-08-22 17:16:56.282385+0000' WHERE ("id" = 10532)
D, [2018-08-22T17:16:56 #962] [task:10532-checkpoint] DEBUG -- DirectorJobRunner: (0.001809s) COMMIT
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-548902] response: {"result":"stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3","error":null,"log":""}, err: , exit_status: pid 1027 exit 0
I, [2018-08-22T17:17:24 #962] [task:10532]  INFO -- DirectorJobRunner: Cloud created stemcell: stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000230s) BEGIN
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000703s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958244,"stage":"Update stemcell","tags":[],"total":6,"task":"Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 to the cloud","index":5,"state":"finished","progress":100}
') WHERE ("id" = 10532)
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.031455s) COMMIT
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000240s) BEGIN
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000545s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958244,"stage":"Update stemcell","tags":[],"total":6,"task":"Save stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 (stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3)","index":6,"state":"started","progress":0}
') WHERE ("id" = 10532)
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001847s) COMMIT
I, [2018-08-22T17:17:24 #962] [task:10532]  INFO -- DirectorJobRunner: Save stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 (stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3)
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000668s) SELECT count(*) AS "count" FROM "stemcells" WHERE (("name" = 'bosh-google-kvm-ubuntu-trusty-go_agent') AND ("version" = '3586.36') AND ("cpi" = '')) LIMIT 1
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000205s) BEGIN
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000526s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958244,"stage":"Update stemcell","tags":[],"total":6,"task":"Save stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 (stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3)","index":6,"state":"failed","progress":100,"data":{"error":"name and version and cpi unique"}}
') WHERE ("id" = 10532)
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.002073s) COMMIT
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000446s) BEGIN
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000542s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1534958244,"error":{"code":100,"message":"name and version and cpi unique"}}
') WHERE ("id" = 10532)
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.002007s) COMMIT
E, [2018-08-22T17:17:24 #962] [task:10532] ERROR -- DirectorJobRunner: name and version and cpi unique
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/sequel-4.36.0/lib/sequel/model/base.rb:1680:in `save'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_stemcell.rb:117:in `block (2 levels) in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:56:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:54:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_stemcell.rb:115:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_stemcell.rb:78:in `each'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_stemcell.rb:78:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000537s) SELECT * FROM "tasks" WHERE ("id" = 10532) LIMIT 1
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000187s) BEGIN
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.000607s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2018-08-22 17:17:24.900436+0000', "description" = 'create stemcell', "result" = 'name and version and cpi unique', "output" = '/var/vcap/store/director/tasks/10532', "checkpoint_time" = '2018-08-22 17:16:56.282385+0000', "type" = 'update_stemcell', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2018-08-22 17:15:56.276337+0000', "event_output" = '{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Downloading remote stemcell","index":1,"state":"started","progress":0}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Downloading remote stemcell","index":1,"state":"finished","progress":100}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Extracting stemcell archive","index":2,"state":"started","progress":0}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Extracting stemcell archive","index":2,"state":"finished","progress":100}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Verifying stemcell manifest","index":3,"state":"started","progress":0}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Verifying stemcell manifest","index":3,"state":"finished","progress":100}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Checking if this stemcell already exists","index":4,"state":"started","progress":0}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Checking if this stemcell already exists","index":4,"state":"finished","progress":100}
{"time":1534958156,"stage":"Update stemcell","tags":[],"total":6,"task":"Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 to the cloud","index":5,"state":"started","progress":0}
{"time":1534958244,"stage":"Update stemcell","tags":[],"total":6,"task":"Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 to the cloud","index":5,"state":"finished","progress":100}
{"time":1534958244,"stage":"Update stemcell","tags":[],"total":6,"task":"Save stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 (stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3)","index":6,"state":"started","progress":0}
{"time":1534958244,"stage":"Update stemcell","tags":[],"total":6,"task":"Save stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.36 (stemcell-a3898f40-ee9b-4c52-4e1a-2a0763ac9aa3)","index":6,"state":"failed","progress":100,"data":{"error":"name and version and cpi unique"}}
{"time":1534958244,"error":{"code":100,"message":"name and version and cpi unique"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 10532)
D, [2018-08-22T17:17:24 #962] [task:10532] DEBUG -- DirectorJobRunner: (0.001840s) COMMIT
I, [2018-08-22T17:17:24 #962] []  INFO -- DirectorJobRunner: Task took 1 minute 28.632269167000004 seconds to process.
```

**Versions (please complete the following information):**
 - Infrastructure:  GCP
 - BOSH version: 265.2.0
 - BOSH CLI version: version 4.0.1-a18c7230-2018-05-23T23:11:20Z

**Comment by dpb587-pivotal** [comment]
Thanks for providing all the details here. It looks like #1924 already describes this issue, so I'm going to close this in favor of consolidating discussion and tracking it there. Feel free to track it, or add more details there, if helpful.
