### ISSUE TITLE
`attach_disk` "CPI error 'Bosh::Clouds::VMNotFound' with message" "not found in datacenter"

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh#2117]
**Describe the bug**

In Multi CPI, `attach-disk` mistakenly searches the native (vSphere) CPI for the VM instead of the Google CPI

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on vSphere with [bosh.yml](https://github.com/cunnie/deployments/blob/756a586c436618e2339b80f45a9b9a3a7ca8799c/bosh-vsphere.yml)
1.5 `update-cpi-config` with [cpis.yml](https://github.com/cunnie/deployments/blob/756a586c436618e2339b80f45a9b9a3a7ca8799c/cpis.yml)
2. Upload Xenial 170.21 and [Cloud Config](https://github.com/cunnie/deployments/blob/756a586c436618e2339b80f45a9b9a3a7ca8799c/cloud-config.yml)
3. Deploy [concourse-ntp-pdns-gce.yml](https://github.com/cunnie/deployments/blob/756a586c436618e2339b80f45a9b9a3a7ca8799c/concourse-ntp-pdns-gce.yml)
4. `bosh -e vsphere -d concourse attach-disk concourse/a1f909cb-6c74-46c6-b007-2c8f5e6707f7 disk-c48e4c52-4510-473e-61e0-9c2dbcf9e04f` to attach the Google Disk to the Google VM
5. Run <commands> on the vm to see the behavior

**Expected behavior**
I expected the disk to be attached to the VM, but it isn't. Instead, it errors out saying the VM could not be found in the vSphere datacenter, but it shouldn't be looking in the vSphere datacenter — the VM's in Google, not in vSphere!

**Logs**
Logs are always helpful! Add logs to help explain your problem.

Here are the logs from `bosh task 57 --debug`. Note that the first few requests are correctly sent to the google CPI, but then the Director goes off the rails and sends the subsequent requests to the vSphere CPI.
```
/tmp/debug.log:D, [2019-01-16T03:15:44.655986 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-196891] request: {"method":"info","arguments":[],"context":{"director_uuid":"cb7514a7-1999-4b74-9a1e-f504c4f5ce77","request_id":"cpi-196891","vm":{"stemcell":{"api_version":2}},"json_key":"<redacted>","project":"<redacted>"}} with command: /var/vcap/jobs/google_cpi/bin/cpi
/tmp/debug.log:D, [2019-01-16T03:15:44.689330 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-196891] response: {"result":{"stemcell_formats":["google-light","google-rawdisk"]},"error":null,"log":""}, err: , exit_status: pid 29420 exit 0
/tmp/debug.log:D, [2019-01-16T03:15:44.696402 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-400458] request: {"method":"detach_disk","arguments":["vm-a5a901fd-5049-491b-5f47-3ab7e4d51e09","disk-bb9d72bd-cec0-49ae-5c45-73339547c1c0"],"context":{"director_uuid":"cb7514a7-1999-4b74-9a1e-f504c4f5ce77","request_id":"cpi-400458","vm":{"stemcell":{"api_version":2}},"json_key":"<redacted>","project":"<redacted>"},"api_version":1} with command: /var/vcap/jobs/google_cpi/bin/cpi
/tmp/debug.log:D, [2019-01-16T03:16:15.227786 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-400458] response: {"result":null,"error":null,"log":""}, err: , exit_status: pid 29429 exit 0
/tmp/debug.log:D, [2019-01-16T03:16:15.305761 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-352860] request: {"method":"info","arguments":[],"context":{"director_uuid":"cb7514a7-1999-4b74-9a1e-f504c4f5ce77","request_id":"cpi-352860","vm":{"stemcell":{"api_version":2}}}} with command: /var/vcap/jobs/vsphere_cpi/bin/cpi
/tmp/debug.log:D, [2019-01-16T03:16:33.698242 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-352860] response: {"result":{"stemcell_formats":["vsphere-ovf","vsphere-ova"]},"error":null,"log":""}, err: /var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
/tmp/debug.log:D, [2019-01-16T03:16:33.703752 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-480893] request: {"method":"attach_disk","arguments":["vm-a5a901fd-5049-491b-5f47-3ab7e4d51e09","disk-c48e4c52-4510-473e-61e0-9c2dbcf9e04f"],"context":{"director_uuid":"cb7514a7-1999-4b74-9a1e-f504c4f5ce77","request_id":"cpi-480893","vm":{"stemcell":{"api_version":2}}},"api_version":1} with command: /var/vcap/jobs/vsphere_cpi/bin/cpi
/tmp/debug.log:D, [2019-01-16T03:16:49.009318 #29390] [task:57] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-480893] response: {"result":null,"error":{"type":"Bosh::Clouds::VMNotFound","message":"VM 'vm-a5a901fd-5049-491b-5f47-3ab7e4d51e09' not found in datacenter 'dc'","ok_to_retry":false},"log":"Rescued Bosh::Clouds::VMNotFound: VM 'vm-a5a901fd-5049-491b-5f47-3ab7e4d51e09' not found in datacenter 'dc'. backtrace: /var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/lib/cloud/vsphere/vm_provider.rb:10:in `find'\n/var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/lib/cloud/vsphere/cloud.rb:487:in `block in attach_disk'\n/var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'\n/var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/lib/cloud/vsphere/cloud.rb:485:in `attach_disk'\n/var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `public_send'\n/var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `run'\n/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:43:in `<top (required)>'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'\n/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'\n/var/vcap/data/packages/ruby-2.4-r4/910f222bc81a31e457760bdd6878b0712bee96dd/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'\n/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'"}, err: /var/vcap/data/packages/vsphere_cpi/3845a2afa76d37d8eb6f7d03e7bd7c1ffbe896e2/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
```

**Versions (please complete the following information):**

 - Infrastructure: vSphere+GCP
 - BOSH version 268.4.0
 - BOSH CLI version version 5.4.0-891ff634-2018-11-14T00:21:14Z
 - Stemcell version ubuntu-xenial/170.21
 - ... other versions of releases being used (BOSH DNS, Credhub, UAA, BPM, etc)

**Deployment info:**

Links to manifests in the description above.

bosh-deployment

**Additional context**

Multi CPI

**Comment by Justin-W** [comment]
@cunnie FYI: I believe this issue may also be fixed by #2304, which fixes #2303. You may want to retest this behavior once a new Bosh version is released which includes fix #2304.
