### ISSUE TITLE
recreate fails with "Error: no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/bosh#2179]
Seems to be the same error as #2054 and #1854.

```
$ bosh -v
version 5.1.2-14b04789-2018-08-17T15:15:17Z

$ bosh env
Name      bosh-aws
UUID      d9c0a460-35c8-4e05-a703-e31d2a66d933
Version   268.6.0 (00000000)
CPI       aws_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          local_dns: enabled
          power_dns: disabled
          snapshots: disabled
User      admin
```

```
$ bosh task 1423 --debug
Using environment 'https://10.0.0.6:25555' as client 'admin'

Task 1423

I, [2019-05-13T14:39:51.317987 #19] [0x2afef5a2433c]  INFO -- TaskHelper: Director Version: 268.6.0
I, [2019-05-13T14:39:51.318031 #19] [0x2afef5a2433c]  INFO -- TaskHelper: Enqueuing task: 1423
I, [2019-05-13T14:39:51.722265 #6913] []  INFO -- DirectorJobRunner: Looking for task with task id 1423
D, [2019-05-13T14:39:51.723115 #6913] [] DEBUG -- DirectorJobRunner: (0.000300s) (conn: 47385999349000) SELECT * FROM "tasks" WHERE "id" = 1423
I, [2019-05-13T14:39:51.724033 #6913] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>1423, :state=>"processing", :timestamp=>2019-05-13 14:39:51 UTC, :description=>"create deployment", :result=>nil, :output=>"/var/vcap/store/director/tasks/1423", :checkpoint_time=>2019-05-13 14:39:51 UTC, :type=>"update_deployment", :username=>"admin", :deployment_name=>"cfcr", :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
I, [2019-05-13T14:39:51.724097 #6913] []  INFO -- DirectorJobRunner: Running from worker 'worker_4' on director/0ef37c4d-76f5-4bf0-5036-71a5a9b08284 (127.0.0.1)
I, [2019-05-13T14:39:51.724136 #6913] []  INFO -- DirectorJobRunner: Starting task: 1423
I, [2019-05-13T14:39:51.724197 #6913] [task:1423]  INFO -- DirectorJobRunner: Creating job
D, [2019-05-13T14:39:51.725108 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000208s) (conn: 47385999349000) SELECT * FROM "tasks" WHERE "id" = 1423
D, [2019-05-13T14:39:51.725982 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000203s) (conn: 47385999349000) SELECT * FROM "tasks" WHERE "id" = 1423
I, [2019-05-13T14:39:51.727521 #6913] [task:1423]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>1423, :state=>"processing", :timestamp=>2019-05-13 14:39:51 UTC, :description=>"create deployment", :result=>nil, :output=>"/var/vcap/store/director/tasks/1423", :checkpoint_time=>2019-05-13 14:39:51 UTC, :type=>"update_deployment", :username=>"admin", :deployment_name=>"cfcr", :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
D, [2019-05-13T14:39:51.728396 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000096s) (conn: 47385999349000) BEGIN
D, [2019-05-13T14:39:51.729659 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000361s) (conn: 47385999349000) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2019-05-13 14:39:51.727656+0000', "description" = 'create deployment', "result" = NULL, "output" = '/var/vcap/store/director/tasks/1423', "checkpoint_time" = '2019-05-13 14:39:51.727855+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cfcr', "started_at" = '2019-05-13 14:39:51.727782+0000', "event_output" = '', "result_output" = '', "context_id" = '' WHERE ("id" = 1423)
D, [2019-05-13T14:39:51.730889 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.001106s) (conn: 47385999349000) COMMIT
I, [2019-05-13T14:39:51.731012 #6913] [task:1423]  INFO -- DirectorJobRunner: Reading deployment manifest
D, [2019-05-13T14:39:51.731665 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000224s) (conn: 47385999349000) SELECT * FROM "tasks" WHERE "id" = 1423
I, [2019-05-13T14:39:51.732155 #6913] [task:1423]  INFO -- DirectorJobRunner: Reading deployment manifest
D, [2019-05-13T14:39:51.732815 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000092s) (conn: 47385999349000) BEGIN
D, [2019-05-13T14:39:51.733454 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000287s) (conn: 47385999349000) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1557758391,"error":{"code":100,"message":"no implicit conversion of nil into String"}}
') WHERE ("id" = 1423)
D, [2019-05-13T14:39:51.734432 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000871s) (conn: 47385999349000) COMMIT
E, [2019-05-13T14:39:51.734610 #6913] [task:1423] ERROR -- DirectorJobRunner: no implicit conversion of nil into String
/var/vcap/data/packages/ruby-2.4-r5/127f7ee83cae3364e8895d758a41cf60736e699c/lib/ruby/2.4.0/psych.rb:377:in `parse'
/var/vcap/data/packages/ruby-2.4-r5/127f7ee83cae3364e8895d758a41cf60736e699c/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
/var/vcap/data/packages/ruby-2.4-r5/127f7ee83cae3364e8895d758a41cf60736e699c/lib/ruby/2.4.0/psych.rb:325:in `parse'
/var/vcap/data/packages/ruby-2.4-r5/127f7ee83cae3364e8895d758a41cf60736e699c/lib/ruby/2.4.0/psych.rb:252:in `load'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:321:in `manifest_hash'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:359:in `deployment_name'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:145:in `add_event'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:421:in `parent_id'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:468:in `handle_toplevel_exception'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:50:in `rescue in perform'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:53:in `perform'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:52:in `with_thread_name'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/data/packages/director/b99294ed5b639acac4dbc3338c8373de4b7b7e05/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2019-05-13T14:39:51.735255 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000218s) (conn: 47385999349000) SELECT * FROM "tasks" WHERE "id" = 1423
D, [2019-05-13T14:39:51.736223 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000093s) (conn: 47385999349000) BEGIN
D, [2019-05-13T14:39:51.737025 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000328s) (conn: 47385999349000) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2019-05-13 14:39:51.735797+0000', "description" = 'create deployment', "result" = 'no implicit conversion of nil into String', "output" = '/var/vcap/store/director/tasks/1423', "checkpoint_time" = '2019-05-13 14:39:51.727855+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cfcr', "started_at" = '2019-05-13 14:39:51.727782+0000', "event_output" = '{"time":1557758391,"error":{"code":100,"message":"no implicit conversion of nil into String"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 1423)
D, [2019-05-13T14:39:51.738115 #6913] [task:1423] DEBUG -- DirectorJobRunner: (0.000968s) (conn: 47385999349000) COMMIT
I, [2019-05-13T14:39:51.738273 #6913] []  INFO -- DirectorJobRunner: Task took 0.014044007 seconds to process.

Task 1423 error

Capturing task '1423' output:
  Expected task '1423' to succeed but state is 'error'

Exit code 1
```

I think the issue might be that every deploy I have done to this deployment has failed, and BOSH does this weird thing where it doesn't store the manifest when deploys fail. 

```
$ bosh manifest -d cfcr
Using environment 'https://10.0.0.6:25555' as client 'admin'

Using deployment 'cfcr'


Succeeded
```

**Comment by h4xnoodle** [comment]
Thanks @benmoss 

It looks like a bug where we don't fail gracefully when there isn't a manifest around to recreate from. It's in our tracker now and we'll take a look when we can!

**Comment by belinda-liu** [comment]
Hey @benmoss,

We've updated the error message in this particular case in 110a045. Thanks for pointing this out!

@miguelverissimo && @belinda-liu, CF BOSH Director Team
