### ISSUE TITLE
Add config-server https wire traces to bosh debug logs

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/bosh#2205]
**Is your feature request related to a problem? Please describe.**

As a bosh operator, in order to troubleshoot failing communications with credhub config server, I need to access https wire traces for bosh to credhub communications.

**Describe the solution you'd like**

bosh debug logs to include config server api calls wire traces when [director.log_level](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=270.5.0#p%3ddirector.log_level) is set to debug or more verbose (trace?) level

**Describe alternatives you've considered**

Manually patching the bosh director package ruby calls to turn on http client verbose logging.

Caveats:
- ephemeral: the patch may not survive bosh director stemcell upgrades
- no clear whether logs will end up in `bosh logs --debug` output or stdout and require sshing into director box, and be rotated soon by log rotation (whereas `bosh logs --debug` might be more durable in director db?)

**Additional context**

Some bugs such as 
https://github.com/orange-cloudfoundry/paas-templates/issues/46#issuecomment-518579916

produce the following stack trace. Credhub HTTPS response seem useful to troubleshoot the root cause

```
, [2019-08-05T20:07:28.364052 #23511] [task:1882836] DEBUG -- DirectorJobRunner: (0.000930s) (conn: 47020238158520) COMMIT
E, [2019-08-05T20:07:28.364170 #23511] [task:1882836] ERROR -- DirectorJobRunner: wrong chunk size line:
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:317:in `read_chunked'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:285:in `block in read_body_0'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:278:in `inflater'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:283:in `read_body_0'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:204:in `read_body'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1229:in `block in get'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1518:in `block in transport_request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:165:in `reading_body'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1517:in `transport_request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1479:in `request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:920:in `start'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1470:in `request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1228:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/auth_http_client.rb:24:in `block in get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/auth_http_client.rb:21:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/retryable_http_client.rb:9:in `block in get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/retryable_http_client.rb:8:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/config_server_http_client.rb:20:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:358:in `get_variable_id_and_value_by_name'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:238:in `block in fetch_values_with_deployment'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:223:in `each'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:223:in `fetch_values_with_deployment'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:55:in `interpolate_with_versioning'
```

**Comment by gberche-orange** [comment]
@bosh-admin-bot please reopen this issue open as I believe it is still relevant
