### ISSUE TITLE
Accessing Credhub hash values in bosh links fails

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#2250]
**Describe the bug**
Accessing Credhub hash values in bosh links fails with `Error: undefined method `key?'`

**To Reproduce**
1. Deploy a bosh director with Credhub
2. Set the Credhub value `credhub set -t json -v '{ "key": "test" }' -n /test/bosh/link/json`
3. Build a zookeeper release from https://github.com/beyhan/zookeeper-release/commit/f90a58630ff774c72911486316c89a4477599601
 and deploy it

**Expected behavior**
You can deploy the zookeeper release

**Logs**

Task logs:
```
Task 24
Task 24 | 13:54:19 | Error: undefined method `key?' for "((/test/bosh/link/json))":String
Task 24 Started  Thu Mar 12 13:54:19 UTC 2020
```
The tasks debug logs:
```
D, [2020-03-12T13:54:19.279009 #74240] [task:24] DEBUG -- DirectorJobRunner: (0.000185s) (conn: 47001576433980) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1584021259,"error":{"code":100,"message":"undefined method `key?'' for \"((/test/bosh/link/json))\":String"}}
') WHERE ("id" = 24)
D, [2020-03-12T13:54:19.279436 #74240] [task:24] DEBUG -- DirectorJobRunner: (0.000360s) (conn: 47001576433980) COMMIT
E, [2020-03-12T13:54:19.279550 #74240] [task:24] ERROR -- DirectorJobRunner: undefined method `key?' for "((/test/bosh/link/json))":String
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_helpers.rb:112:in `block in find_property'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_helpers.rb:111:in `each'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_helpers.rb:111:in `find_property'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_helpers.rb:14:in `block in process_link_properties'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_helpers.rb:12:in `each'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_helpers.rb:12:in `process_link_properties'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_providers_parser.rb:169:in `block in process_provider_definitions'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_providers_parser.rb:148:in `each'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_providers_parser.rb:148:in `process_provider_definitions'
```

**Versions (please complete the following information):**
 - Infrastructure: all
 - BOSH version: 270.12.0

**Deployment info:**
https://github.com/beyhan/zookeeper-release/commit/f90a58630ff774c72911486316c89a4477599601

**Additional context**
Links are resolved when the manifest is parsed:  https://github.com/cloudfoundry/bosh/blob/35bc60c6ddfda6fc67ba14d897dbd4cdc37684dd/src/bosh-director/lib/bosh/director/jobs/update_deployment.rb#L39
The interpolation of variables happens a bit later: https://github.com/cloudfoundry/bosh/blob/35bc60c6ddfda6fc67ba14d897dbd4cdc37684dd/src/bosh-director/lib/bosh/director/jobs/update_deployment.rb#L50
So we don’t have the Credhub value at the time, when links are built. Looking at the director code to support this will be quite an effort, but at least this could be documented in the bosh links section on bosh.io

**Comment by beyhan** [comment]
A work around for this issue is to reference the Credhub hash key in the bosh manifest. E.g. the property definition from https://github.com/beyhan/zookeeper-release/commit/f90a58630ff774c72911486316c89a4477599601#diff-03676a7c3beb058a994e8550fe21cc07R30 could be changed to:
```
properties:
  test: 
    key: ((/test/bosh/link/json.key))
```

I have created a [pr](https://github.com/cloudfoundry/docs-bosh/pull/720) in `bosh-docs` to document this issue.
