### ISSUE TITLE
`bosh stop` tries to resolve links

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2252]
**Describe the bug**
When trying to `bosh stop` a deployment which instances consume a link from another deployment, BOSH tries to resolve these links and fails if it cannot do so. This is true, even if `--no-converge` is used.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director
2. Upload a stemcell and cloud-config
3. Deploy `A` providing a link
4. Deploy `B` consuming the link
5. Delete deployment `A`
6. Run `bosh stop -d B [--no-converge]` and watch it fail

**Expected behavior**
`bosh stop` doesn't care about links being provided, especially when told to not converge

**Logs**
```
✗ bosh stop -d ping-app ping-app-back/06cb25cc-477e-4927-be6a-da67386b341e --no-converge
Using environment '192.168.50.6' as client 'admin'

Using deployment 'ping-app'

Continue? [yN]: y

Task 354

Task 354 | 12:57:27 | Error: Link 'common_link' in job 'consul_agent' from instance group 'ping-app-front' consumes from deployment 'consul', but the deployment does not exist.

Task 354 Started  Tue Mar 17 12:57:27 UTC 2020
Task 354 Finished Tue Mar 17 12:57:27 UTC 2020
Task 354 Duration 00:00:00
Task 354 error

Non-converging action failed:
  Expected task '354' to succeed but state is 'error'

Exit code 1
```

Debug task log
```
E, [2020-03-17T12:57:27.676617 #23194] [task:354] ERROR -- DirectorJobRunner: Link 'common_link' in job 'consul_agent' from instance group 'ping-app-front' consumes from deployment 'consul', but the deployment does not exist.
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/link_consumers_parser.rb:42:in `parse_consumers_from_job'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/links/links_parser.rb:25:in `parse_consumers_from_job'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/addon/addon.rb:95:in `block (2 levels) in add_addon_jobs_to_instance_groups'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/addon/addon.rb:80:in `each'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/addon/addon.rb:80:in `block in add_addon_jobs_to_instance_groups'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/addon/addon.rb:73:in `each'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/addon/addon.rb:73:in `add_addon_jobs_to_instance_groups'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/addon/addon.rb:49:in `add_to_deployment'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/planner_factory.rb:108:in `block in parse_from_manifest'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/planner_factory.rb:107:in `each'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/planner_factory.rb:107:in `parse_from_manifest'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/planner_factory.rb:46:in `create_from_manifest'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/planner_factory.rb:40:in `create_from_model'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_instance.rb:27:in `block in perform'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `block in with_deployment_lock'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/lock.rb:79:in `lock'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `with_deployment_lock'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_instance.rb:21:in `perform'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:50:in `with_thread_name'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:9:in `perform'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:98:in `block (3 levels) in run'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
/var/vcap/data/packages/director/a2026fc29c49cefc8f1ace58f61c3d46684adc6b/gem_home/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Versions (please complete the following information):**
 - Infrastructure: bosh-lite
 - BOSH version 270.12.0
 - BOSH CLI version 6.2.1-a28042ac-2020-02-10T18:41:00Z
 - Stemcell version ubuntu-xenial/621.59
 - ... other versions of releases being used bosh-deployment 670b442

**Additional context**
* https://github.com/cloudfoundry/bosh/issues/1723
* 
* https://github.com/cloudfoundry/bosh-cli/issues/456

**Comment by h4xnoodle** [comment]
Thanks for filing the issue @voelzmo I'll hopefully be able to take a look soon.

**Comment by voelzmo** [comment]
So sorry, I missed this somehow completely.

> What do you expect to happen if drain needs the link?
That's a nice catch, I didn't think about this too much! I guess my assumption was that links are resolved during rendering of the scripts, not at execution time. Are drain scripts re-rendered on `bosh stop`? Did you encounter any dynamic usage of links like that? Any kind of dynamic addressing should ideally be covered by DNS, I guess.
