### ISSUE TITLE
clean up tasks fails with wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh#2255]
**Describe the bug**
The `clean up tasks` tasks fails every time.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director `270.12.0`
2. Wait until the first scheduled task clean up runs

**Expected behavior**
Don't error but clean up tasks.

**Logs**
```
E, [2020-03-22T00:00:02.054392 #28825] [task:104624] ERROR -- DirectorJobRunner: wrong number of arguments (given 0, expected 1)
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/scheduled_tasks_cleanup.rb:18:in `initialize'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:84:in `new'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:84:in `perform_job'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:50:in `with_thread_name'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:9:in `perform'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:98:in `block (3 levels) in run'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
/var/vcap/data/packages/director/4de68307cefbbb6cbb7e4a39d40adef9bf335e6a/gem_home/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Versions (please complete the following information):**
 - Infrastructure: any
 - `270.12.0`
 - `ubuntu-xenial/621.59`

**Deployment info:**
Defaults are used for `director.tasks_cleanup_schedule`. `max_tasks=10000`.

**Comment by h4xnoodle** [comment]
strange, the `_` should mean the `params` are ignored https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/jobs/scheduled_tasks_cleanup.rb#L18

looks like we could either default to `{}` https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/jobs/scheduled_orphaned_network_cleanup.rb#L24  or remove completely https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/jobs/scheduled_orphaned_vm_cleanup.rb#L14
