### ISSUE TITLE
`attach-disk` fails in multi-CPI envs

### ISSUE THREAD

**Issue by Justin-W** [cloudfoundry/bosh#2303]
**Describe the bug**
It seems that the `bosh attach-disk` command does not support multi-CPI configurations, since it seems to use the "default CPI" when attempting to attach the disk to the VM, resulting in a (CPI-dependent) error if/when the  default CPI cannot successfully attach the disk to the VM.

**To Reproduce**

We encountered this bug when attempting to (re-)attach a persistent disk that we restored from a Bosh-created snapshot. This same process previously worked for us in a single-CPI Bosh environment, but failed this time in an environment here we use 2 different AWS CPIs.

1. Deploy a bosh director on AWS in Region A (CPI-dir)
2. Add a cloud-config and cpi-config for an AWS CPI (CPI-B) for Region B
3. Deploy a VM (VM-1) to Region B using CPI-B
4. Have Bosh take a snapshot (SNAP-1) of VM-1's persistent disk
5. Use AWS to manually restore a snapshot SNAP-1 as disk DISK-RESTORED
6. Run `bosh attach-disk <VM-1> <DISK-RESTORED>` to see the behavior (attach fails; presumably because it uses CPI-dir instead of CPI-B)

Note: Based on previous results, if CPI-dir and CPI-B have similar configuration, such that CPI-dir is able to perform IaaS API operations on VM-1, then Step 6 succeeds without error. But if the 2 CPIs have significantly different configuration, then CPI-dir fails during step 6 when calling the IaaS APIs.

**Expected behavior**

Expected Step 6 (above) to succeed, using the correct CPI (CPI-B) for the VM and disk being targeted.

Per the docs, restoring a restored disk from a snapshot _should_ work:

From: https://bosh.io/docs/persistent-disks/#orphaned-disks:

> `attach-disk` command can also attach available disks found in the IaaS. They don't have to be listed in the orphaned disks list.

From: https://bosh.io/docs/snapshots/:

> Take a disk snapshot of a persistent disk before deploying major updates or for other important events. If the changes corrupt persistent disk, promote a disk snapshot to be a persistent disk and attach it to the VM to restore data prior to your changes.

**Logs**

Attaching the restored disk failed with this log output:

```
D, [2021-06-28T23:31:07.192430 #14517] [task:1015950] DEBUG -- DirectorJobRunner: Using cpi_version 2 for CPI 
I, [2021-06-28T23:31:07.192502 #14517] [task:1015950]  INFO -- DirectorJobRunner: Attaching disk vol-051d7275a48e0b59b
D, [2021-06-28T23:31:07.193190 #14517] [task:1015950] DEBUG -- DirectorJobRunner: (0.000389s) (conn: 47349026785280) SELECT * FROM "vms" WHERE (("instance_id" = 105) AND ("active" IS TRUE)) LIMIT 1
D, [2021-06-28T23:31:07.193660 #14517] [task:1015950] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-841520] request: {"method":"attach_disk","arguments":["i-0ca7fbb0072dd4a28","vol-051d7275a48e0b59b"],"context":{"director_uuid":"43c4f352-34ab-4099-b732-0a62bbf0bd2f","request_id":"cpi-841520","vm":{"stemcell":{"api_version":3}}},"api_version":2} with command: /var/vcap/jobs/aws_cpi/bin/cpi
D, [2021-06-28T23:31:08.959007 #14517] [task:1015950] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-841520] response: {"result":null,"error":{"type":"Unknown","message":"The instance ID 'i-0ca7fbb0072dd4a28' does not exist","ok_to_retry":false},"log":"Rescued Unknown: The instance ID 'i-0ca7fbb0072dd4a28' does not exist. backtrace: /var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.22.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.22.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.22.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.22.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.22.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.22.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.22.0/lib/seahorse/client/request.rb:70:in `send_request'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-ec2-1.36.0/lib/aws-sdk-ec2/client.rb:11097:in `describe_instances'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-ec2-1.36.0/lib/aws-sdk-ec2/instance.rb:306:in `load'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-ec2-1.36.0/lib/aws-sdk-ec2/instance.rb:316:in `data'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/aws-sdk-ec2-1.36.0/lib/aws-sdk-ec2/instance.rb:171:in `block_device_mappings'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/lib/cloud/aws/sdk_helpers/volume_manager.rb:125:in `select_device_name'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/lib/cloud/aws/sdk_helpers/volume_manager.rb:62:in `attach_ebs_volume'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/lib/cloud/aws/cloud_core.rb:134:in `attach_disk'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/lib/cloud/aws/cloud_v2.rb:80:in `block in attach_disk'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/lib/cloud/aws/cloud_v2.rb:78:in `attach_disk'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `public_send'\n/var/vcap/data/packages/bosh_aws_cpi/b8b6bc18942dce7bfa45864039f09ce1cf561f64/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `run'\n/var/vcap/packages/bosh_aws_cpi/bin/aws_cpi:28:in `<top (required)>'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'\n/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ddbd98265d63ae6775f84af08079e722b77bf3fd/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'\n/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `load'\n/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `<main>'"}, err: I, [2021-06-28T23:31:08.851700 #14567]  INFO -- [req_id cpi-841520]: Starting attach_disk...
D, [2021-06-28T23:31:08.950450 #14567] DEBUG -- [req_id cpi-841520]: [Aws::EC2::Client 400 0.074944 0 retries] describe_instances(instance_ids:["i-0ca7fbb0072dd4a28"]) Aws::EC2::Errors::InvalidInstanceIDNotFound The instance ID 'i-0ca7fbb0072dd4a28' does not exist

I, [2021-06-28T23:31:08.950927 #14567]  INFO -- [req_id cpi-841520]: Finished attach_disk in 0.1 seconds
, exit_status: pid 14567 exit 0
```

**Versions (please complete the following information):**
 - Infrastructure: AWS (multi-region, multi-CPI; AWS CPI version: 83)
 - BOSH version: 271.2.0
 - Stemcell version: ubuntu 18.04
 - BPM version: 1.0.4

**Deployment info:**

I don't think the deployment manifest matters, except that the deployment must use a non-default CPI and have a persistent disk.

**Additional context**

Based on our current and past results, we strongly suspect that this is a bug within Bosh itself, and is likely due to some section(s) of code that did not get updated when multi-CPI support was added.

**Related Issues**

* #2117: This sounds similar, and is potentially due to the same root cause (but using different CPIs than I am using, resulting is different IaaS errors in the logs).
* #2119: This also sounds similar, and may potentially be due to the same root cause.
* #1869: I think this is a separate issue, but I suspect that my issue's root cause is also related to the way that bosh persists the CPI for the disk when the disk's Model is created/persisted to the Bosh DB.

**Comment by Justin-W** [comment]
Thanks @rkoster. Any idea on when we can expect a new official Bosh version to get released which contains this fix?

It looks like the latest Bosh version ([v271.8.0](https://github.com/cloudfoundry/bosh/releases/tag/v271.8.0)) was almost 3 months ago, and is currently 25 commits behind master.

**Comment by rkoster** [comment]
This PR has broken ci. Since it does not take into account the case where an instance does not have an active vm. Attach disk to an hard stopped vm is apparently something out integration tests run.

We are currently working on a fix. There is already a story to cut a new director release in the backlog. So expect this to be picked up somewhere in de coming 2 weeks.

**Comment by Justin-W** [comment]
Thanks @rkoster!
