### ISSUE TITLE
Director is missing write access to /var/vcap/store/tmp

### ISSUE THREAD

**Issue by bgandon** [cloudfoundry/bosh#2346]
**Describe the bug**
While deploying with latest BOSH v271.17.0, here is the error reported:
```
Task 20812 | 17:27:17 | Preparing deployment: Preparing deployment (00:00:02)
Task 20812 | 17:27:19 | Preparing deployment: Rendering templates (00:00:03)
Task 20812 | 17:27:22 | Preparing package compilation: Finding packages to compile (00:00:00)
                      L Error: Permission denied @ dir_s_mkdir - /var/vcap/store/tmp
Task 20812 | 17:27:23 | Error: Permission denied @ dir_s_mkdir - /var/vcap/store/tmp
```

**To Reproduce**
1. Update the bosh director on BOSH-Lite from v271.8.0 to v271.17.0
2. Update Concourse (or any deployment)

**Expected behavior**
`bosh deploy` running smoothly.

**Logs**
The debug logs `bosh task 20814 --debug` provide a stacktrace that shows that the blobstore client used by the Director requires write access to `/var/vcap/store/tmp`

```
E, [2022-01-02T17:30:35.510274 #520] [task:20814] ERROR -- DirectorJobRunner: Permission denied @ dir_s_mkdir - /var/vcap/store/tmp
/var/vcap/data/packages/ruby-3.0.2-r0.67.0/5c0fc3495aad7faa66e91de1d5beef92ffe10ca4/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
/var/vcap/data/packages/ruby-3.0.2-r0.67.0/5c0fc3495aad7faa66e91de1d5beef92ffe10ca4/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
/var/vcap/data/packages/ruby-3.0.2-r0.67.0/5c0fc3495aad7faa66e91de1d5beef92ffe10ca4/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
/var/vcap/data/packages/ruby-3.0.2-r0.67.0/5c0fc3495aad7faa66e91de1d5beef92ffe10ca4/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
/var/vcap/data/packages/ruby-3.0.2-r0.67.0/5c0fc3495aad7faa66e91de1d5beef92ffe10ca4/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
/var/vcap/data/packages/ruby-3.0.2-r0.67.0/5c0fc3495aad7faa66e91de1d5beef92ffe10ca4/lib/ruby/3.0.0/fileutils.rb:211:in `each'
/var/vcap/data/packages/ruby-3.0.2-r0.67.0/5c0fc3495aad7faa66e91de1d5beef92ffe10ca4/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/blobstore_client/local_client.rb:9:in `initialize'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/blobstore_client/client.rb:12:in `new'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/blobstore_client/client.rb:12:in `create'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/blobstore_client/client.rb:16:in `safe_create'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/config.rb:375:in `block in compiled_package_cache_blobstore'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/config.rb:371:in `synchronize'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/config.rb:371:in `compiled_package_cache_blobstore'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/blob_util.rb:87:in `compiled_package_cache_blobstore'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/blob_util.rb:43:in `exists_in_global_cache?'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/compiled_package_finder.rb:55:in `fetch_from_global_cache'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/compiled_package_finder.rb:17:in `find_compiled_package'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/compiled_package_requirement_generator.rb:49:in `create_requirement'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/compiled_package_requirement_generator.rb:28:in `generate!'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:204:in `block (4 levels) in prepare_requirements'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:203:in `each'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:203:in `block (3 levels) in prepare_requirements'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:202:in `each'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:202:in `block (2 levels) in prepare_requirements'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:196:in `each'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:196:in `block in prepare_requirements'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:189:in `prepare_requirements'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stages/package_compile_stage.rb:58:in `perform'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:71:in `deploy'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:56:in `block in perform'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `block in with_deployment_lock'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/lock.rb:79:in `lock'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `with_deployment_lock'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:34:in `perform'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:50:in `with_thread_name'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:9:in `perform'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:98:in `block (3 levels) in run'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/eventmachine-1.3.0.dev.1/lib/eventmachine.rb:1078:in `block in spawn_threadpool'
/var/vcap/data/packages/director/5e127fd8c4b0583dc23e984700cb83376b4a6e4e/gem_home/ruby/3.0.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Versions (please complete the following information):**
 - Infrastructure: Bosh-Lite
 - BOSH version 271.17.0
 - BOSH CLI version 6.4.8
 - Stemcell version ubuntu-bionic/1.51

**Steps to quick fix:**
Log in to the Director, and run `vim /var/vcap/jobs/director/config/bpm.yml`
Add this section to the `director` BPM process:
```
  additional_volumes:
  - path: /var/vcap/store/tmp
    writable: true
```
Then `monit restart director` and `bosh deploy` will work again normally.

**Comment by beyhan** [comment]
Hi @bgandon,
this should be actually a stemcell issue because the bosh agent is configuring the permissions of the different locations. Have you upgraded the stemcell version? What are the permission of `/var/vcap/store`? Could be that there is write issue for the persistent volume attached to the Director VM?

**Comment by bgandon** [comment]
I've used the latest `ubuntu-bionic/1.51` and there is no newer Stemcell available yet.

But this issue is not related to the permissions set for `/var/vcap/store/tmp`. This is related to the restrictions enforced by BPM when running the Director's ruby process. BPM runs processes inside namespaces with restrictions. Basically the whole filesystem is mounted as read-only except specifically declared directories. That's why mounting `/var/vcap/store/tmp` as writable solves the issue.

But I think we should question why the blobstore client code tries to access `/var/vcap/store/tmp`. The concept of a directory holding temporary data, _but_ written on a persistent disk, just sounds awkward. Instead, `/tmp` should be used, and if any other directory is used then there should be proper reason for that.

**Comment by rkoster** [comment]
@bgandon are you able to reproduce this issue with the latest version of bosh-deployment?
