### ISSUE TITLE
Could not compile v276.1.0 on air-gaped environment

### ISSUE THREAD

**Issue by psycofdj** [cloudfoundry/bosh#2408]
**Describe the bug**

The bosh release is unable to compile on air-gaped environment since release `v276.1.0`.

**Probable Cause**

The recently added package `director-ruby-3.1-test` fails to compile because bundler tries to fetch a gems from `rubygems.org`. Since the environment has no access to internet,  the compilation ends in error.

From my understanding, the package depends on `src/ruby-test-app` which required the gem `thin`. This gem is not properly vendorized. 

Perhaps the `src/ruby-test-app` should be part of the general `src/Gemfile` and used already vendorized `thin` gem in version `1.8.1`;  or have its own vendorized gems in `src/ruby-test-app/vendor`. Either way, `director-ruby-3.1-test` package should include vendorized gems in its spec file.

**To Reproduce**

1. Upload release `v276.1.0` to bosh director where compilation VMs do not have access to internet
4. Trigger package compilation by exporting the release: `bosh export-release bosh/276.1.0 ubuntu-bionic/1.107` (sames goes for jammy)

**Expected behavior**

Compilation process works and compiled-release tarball is exported.

**Logs**

```
Task 75452 | 08:04:16 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 75452 | 08:04:16 | Compiling packages: director-ruby-3.1-test/758093d02dda065b8e6215fac82c6860062bde66d1df8f9c819daf22e1dfb7b3 (00:03:33)
                      L Error: Action Failed get_task: Task 6e254683-db5e-4bf6-6e3c-386b52074a1c result: Compiling package director-ruby-3.1-test: Running packaging script: Running packaging script: Command exited with 1; Stdout: , Truncated stderr:   /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/compact_index_client/updater.rb:47:in `block in update'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/vendor/tmpdir/lib/tmpdir.rb:96:in `mktmpdir'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/compact_index_client/updater.rb:29:in `update'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/compact_index_client.rb:92:in `update'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/compact_index_client.rb:79:in `update_and_parse_checksums!'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/fetcher/compact_index.rb:70:in `available?'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/fetcher/compact_index.rb:16:in `call'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/fetcher.rb:162:in `use_api'
  /var/vcap/data/packages/director-ruby-3.1/e80bd1573b2914eb0f2cf112e220e6275a9b7de4/lib/ruby/site_ruby/3.1.0/bundler/source/rubygems.rb:429:in `block in api_fetchers'
```

**Versions (please complete the following information):**
 - Infrastructure: clodustack
 - BOSH version `276.1.0`
 - BOSH CLI version `7.0.1-799538d1-2022-06-01T21:53:20Z`
 - Stemcell version `ubuntu-xenial/1.107` / `ubuntu-jammy/1.26`

**Comment by ystros** [comment]
I believe the team was looking into fixing this as part of the `--prefix` / package collision solution for the Ruby release, which would remove the package entirely from the Director.

**Comment by ystros** [comment]
We just released v276.1.1 with this change.

**Comment by psycofdj** [comment]
I confirm `v276.1.1` successfully compiled on my air gaped environment. Thanks a lot.
