### ISSUE TITLE
downgrading bosh from 277.2.0 to 277.1.0 is failing with add_permanent_nats_credentials_to_vms.rb (Sequel::Migrator::Error)

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh#2432]
when trying to downgrade bosh from `277.2.0` to `277.1.0`
we get the following error in
/var/vcap/sys/log/director/director.stderr.log
```
/var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/sequel-5.29.0/lib/sequel/extensions/migration.rb:722:in `get_applied_migrations': Applied migration files not in file system: 20230103143246_add_permanent_nats_credentials_to_vms.rb (Sequel::Migrator::Error)
        from /var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/sequel-5.29.0/lib/sequel/extensions/migration.rb:668:in `initialize'
        from /var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/bosh-director-0.0.0/lib/db_migrator.rb:42:in `new'
        from /var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/bosh-director-0.0.0/lib/db_migrator.rb:42:in `migrator'
        from /var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/bosh-director-0.0.0/lib/db_migrator.rb:59:in `director_migrator'
        from /var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/bosh-director-0.0.0/lib/db_migrator.rb:23:in `call'
        from /var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/bosh-director-0.0.0/lib/db_migrator.rb:23:in `migrate'
        from /var/vcap/data/packages/director/d1cb90e866e4cd227460cc8b7ec6622c858330fe/gem_home/ruby/3.2.0/gems/bosh-director-0.0.0/bin/bosh-director-migrate:33:in `<top (required)>'
        from /var/vcap/packages/director/bin/bosh-director-migrate:27:in `load'
        from /var/vcap/packages/director/bin/bosh-director-migrate:27:in `<main>'
```
this seems to be directly related to this commit https://github.com/cloudfoundry/bosh/commit/dec31de320fcd29a574db8685f6abf697138f788

more investigation needed.

**Comment by beyhan** [comment]
To my knowledge we don't support downgrad of director officially, but this needs to go at least into the release notes of `277.2.0` so that people are informed.

**Comment by rkoster** [comment]
It seems like a `down` step is missing in this migration: https://github.com/cloudfoundry/bosh/commit/dec31de320fcd29a574db8685f6abf697138f788#diff-015764767a0ae38402e4153978fed587e10ee3e21895a6909b4089e2f3cf3d09R2-R6
cc @danielfor
