### ISSUE TITLE
unable to connect Bosh agent for aws when deploying micro bosh

### ISSUE THREAD

**Issue by endwall** [cloudfoundry/bosh#360]
Recenlty I tried to upgrade micro bosh/cloud foundry deployed in aws.
I updated the gem version and they are "1.5.0.pre.805".

I got the following error:
1. running 
$bosh micro deploy <stemcell 0.6.4>
>>>>> error log<<<<<<<
Verifying stemcell...
File exists and readable                                     OK
Using cached manifest...
Stemcell properties                                          OK

Stemcell info
-------------
Name:    micro-bosh-stemcell
Version: 0.6.4

Deploy Micro BOSH
  unpacking stemcell (00:00:14)                                                                     
  uploading stemcell (00:11:39)                                                                     
  creating VM from ami-8ebbf2dc (00:00:32)                                                          
Waiting for the agent               |oooooo                  | 3/11 00:18:42  ETA: 00:26:56Unable to connect to Bosh agent. Check logs for more details.
=============

I checked the micro bosh instance and found the agent log like this:
2013-07-12_00:57:00.73869 #[3206] INFO: Starting agent 0.6.4...
2013-07-12_00:57:00.73880 #[3206] INFO: Configuring agent...
2013-07-12_00:57:00.74581 #[3206] INFO: Configuring instance
2013-07-12_00:57:00.79142 #[3206] INFO: Loaded settings: {"vm"=>{"name"=>"vm-f3759453-cbc3-483f-8649-6a27482b858a"}, "agent_id"=>"bm-e158c654-0b46-4d49-bd20-72ab38eac497", "networks"=>{"bosh"=>{"cloud_properties"=>{}, "netmask"=>nil, "gateway"=>nil, "ip"=>nil, "dns"=>nil, "type"=>"dynamic", "default"=>["dns", "gateway"]}, "vip"=>{"ip"=>"54.251.183.0", "type"=>"vip", "cloud_properties"=>{}}}, "disks"=>{"system"=>"/dev/sda1", "ephemeral"=>"/dev/sdb", "persistent"=>{}}, "env"=>{"bosh"=>{"password"=>nil}}, "ntp"=>[], "blobstore"=>{"provider"=>"local", "options"=>{"blobstore_path"=>"/var/vcap/micro_bosh/data/cache"}}, "mbus"=>"https://vcap:b00tstrap@0.0.0.0:6868"}
2013-07-12_00:57:00.80636 /var/vcap/bosh/agent/lib/agent/bootstrap.rb:135:in `merge!': can't convert nil into Hash (TypeError)
2013-07-12_00:57:00.80660       from /var/vcap/bosh/agent/lib/agent/bootstrap.rb:135:in `update_blobstore'
2013-07-12_00:57:00.80665       from /var/vcap/bosh/agent/lib/agent/bootstrap.rb:44:in `configure'
2013-07-12_00:57:00.80669       from /var/vcap/bosh/agent/lib/agent.rb:93:in `start'
2013-07-12_00:57:00.80674       from /var/vcap/bosh/agent/lib/agent.rb:72:in `run'
2013-07-12_00:57:00.80678       from /var/vcap/bosh/agent/bin/agent:97:in `<main>'
2013-07-12_00:57:03.91276 #[3227] INFO: Starting agent 0.6.4...
2013-07-12_00:57:03.91286 #[3227] INFO: Configuring agent...
2013-07-12_00:57:03.94437 #[3227] INFO: Configuring instance
2013-07-12_00:57:03.99023 /var/vcap/bosh/agent/lib/agent/infrastructure/aws/registry.rb:70:in `rescue in get_json_from_url': Error requesting registry information #<Errno::ECONNREFUSED: Connection refused - connect(2) (http://localhost:25888)> (RuntimeError)
2013-07-12_00:57:03.99028       from /var/vcap/bosh/agent/lib/agent/infrastructure/aws/registry.rb:43:in `get_json_from_url'
2013-07-12_00:57:03.99029       from /var/vcap/bosh/agent/lib/agent/infrastructure/aws/registry.rb:91:in `get_settings'
2013-07-12_00:57:03.99030       from /var/vcap/bosh/agent/lib/agent/infrastructure/aws/settings.rb:33:in `load_settings'
2013-07-12_00:57:03.99030       from /var/vcap/bosh/agent/lib/agent/infrastructure/aws.rb:10:in `load_settings'
2013-07-12_00:57:03.99031       from /var/vcap/bosh/agent/lib/agent/bootstrap.rb:60:in `load_settings'
2013-07-12_00:57:03.99032       from /var/vcap/bosh/agent/lib/agent/bootstrap.rb:34:in `configure'
2013-07-12_00:57:03.99033       from /var/vcap/bosh/agent/lib/agent.rb:93:in `start'
2013-07-12_00:57:03.99033       from /var/vcap/bosh/agent/lib/agent.rb:72:in `run'
2013-07-12_00:57:03.99034       from /var/vcap/bosh/agent/bin/agent:97:in `<main>'

Any idea about the problem?

**Comment by cppforlife** [comment]
Closing in favor of using bosh-init.
