### ISSUE TITLE
S3 Blobstore Client does not follow 301 MOVED PERMANENTLY responses

### ISSUE THREAD

**Issue by xoebus** [cloudfoundry/bosh#463]
Amazon recently moved one of our S3 buckets from _US Standard_ to _Oregon_ without notifying us and just left a lot of 301 redirects in place of the files that were once there. This makes the blob syncing part of creating a release fail now with this error:

```
$ bosh create release --force
/var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/blobstore_client/lib/blobstore_client/simple_blobstore_client.rb:43:in `get_file': Could not fetch object, 301/ (Bosh::Blobstore::BlobstoreError)
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/blobstore_client/lib/blobstore_client/s3_blobstore_client.rb:88:in `get_file'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/blobstore_client/lib/blobstore_client/base.rb:50:in `get'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/blobstore_client/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/blobstore_client/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
    from /var/vcap/store/gems/2.0.0p353/deploy/gems/bosh_common-1.5.0.pre.1244/lib/common/retryable.rb:21:in `block in retryer'
    from /var/vcap/store/gems/2.0.0p353/deploy/gems/bosh_common-1.5.0.pre.1244/lib/common/retryable.rb:19:in `loop'
    from /var/vcap/store/gems/2.0.0p353/deploy/gems/bosh_common-1.5.0.pre.1244/lib/common/retryable.rb:19:in `retryer'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/blobstore_client/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/blob_manager.rb:295:in `download_blob'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/blob_manager.rb:230:in `block in process_index'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/blob_manager.rb:211:in `each_pair'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/blob_manager.rb:211:in `process_index'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/blob_manager.rb:155:in `sync'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/commands/release.rb:350:in `dirty_blob_check'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/commands/release.rb:300:in `create_from_spec'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/commands/release.rb:48:in `create'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/command_handler.rb:57:in `run'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/runner.rb:59:in `run'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/lib/cli/runner.rb:18:in `run'
    from /var/vcap/store/gems/2.0.0p353/deploy/bundler/gems/bosh-1e760331719a/bosh_cli/bin/bosh:7:in `<top (required)>'
    from /var/vcap/store/gems/2.0.0p353/deploy/bin/bosh:23:in `load'
    from /var/vcap/store/gems/2.0.0p353/deploy/bin/bosh:23:in `<main>'
```

We're going to be moving the bucket back to the original region but it would be nice if the BOSH blobstore client understood redirect status codes and handled them with the correct semantics.

**Comment by dpb587-pivotal** [comment]
@cppforlife, is this likely fixed since the s3cli merge in https://github.com/cloudfoundry/bosh/commit/01c6ab0ea96f162ffb82dfb8eb38379b5c8d95fc / since stable-3232?

**Comment by jchesterpivotal** [comment]
Buildpacks team just got bitten by this. We consider it a bug.

If following redirects automatically will not be supported behaviour, it would be _super duper helpful_ to get something other than an inscrutable stacktrace.

For example, something like 

```
Looked for blob name-of-binary in us-east-1, but was redirected to us-west-2. BOSH will not follow redirects. Either update your config/final.yml with your preferred endpoint, or ensure that your blob bucket is in us-east-1.
```

**Comment by dpb587-pivotal** [comment]
Closing - this should no longer be an issue with the go client used by director and new bosh-cli.
