### ISSUE TITLE
Unable to upload final release blobs to s3

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/bosh#494]
While creating a final release for cf-services-contrib to following error occurred:

```
Blobstore error: Failed to create object, underlying error: #<Errno::EPIPE: Broken pipe> /lib/ruby/1.9.1/openssl/buffering.rb:318:in `syswrite'
/lib/ruby/1.9.1/openssl/buffering.rb:318:in `do_write'
/lib/ruby/1.9.1/openssl/buffering.rb:336:in `write'
/lib/ruby/1.9.1/net/protocol.rb:199:in `write0'
/lib/ruby/1.9.1/net/protocol.rb:173:in `block in write'
/lib/ruby/1.9.1/net/protocol.rb:190:in `writing'
/lib/ruby/1.9.1/net/protocol.rb:172:in `write'
/lib/ruby/1.9.1/net/http.rb:1956:in `send_request_with_body_stream'
/lib/ruby/1.9.1/net/http.rb:1922:in `exec'
/lib/ruby/1.9.1/net/http.rb:1318:in `block in transport_request'
/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
/lib/ruby/1.9.1/net/http.rb:1294:in `request'
/gems/aws-sdk-1.8.5/lib/net/http/connection_pool/session.rb:64:in `request'
/gems/aws-sdk-1.8.5/lib/net/http/connection_pool.rb:173:in `block in request'
/gems/aws-sdk-1.8.5/lib/net/http/connection_pool.rb:194:in `session_for'
/gems/aws-sdk-1.8.5/lib/net/http/connection_pool.rb:171:in `request'
/gems/aws-sdk-1.8.5/lib/net/http/connection_pool/connection.rb:173:in `request'
/gems/aws-sdk-1.8.5/lib/aws/core/http/net_http_handler.rb:66:in `handle'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:231:in `block in make_sync_request'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:267:in `retry_server_errors'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:227:in `make_sync_request'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:472:in `block (2 levels) in client_request'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:355:in `log_client_request'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:441:in `block in client_request'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:337:in `return_or_raise'
/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:440:in `client_request'
(eval):3:in `put_object'
/gems/aws-sdk-1.8.5/lib/aws/s3/s3_object.rb:1659:in `write_with_put_object'
/gems/aws-sdk-1.8.5/lib/aws/s3/s3_object.rb:606:in `write'
/gems/blobstore_client-1.1761.0/lib/blobstore_client/s3_blobstore_client.rb:148:in `block in store_in_s3'
/gems/blobstore_client-1.1761.0/lib/blobstore_client/s3_blobstore_client.rb:147:in `open'
/gems/blobstore_client-1.1761.0/lib/blobstore_client/s3_blobstore_client.rb:147:in `store_in_s3'
/gems/blobstore_client-1.1761.0/lib/blobstore_client/s3_blobstore_client.rb:75:in `create_file'
/gems/blobstore_client-1.1761.0/lib/blobstore_client/base.rb:27:in `create'
/lib/ruby/1.9.1/forwardable.rb:201:in `create'
/lib/ruby/1.9.1/forwardable.rb:201:in `create'
/gems/bosh_cli-1.1761.0/lib/cli/packaging_helper.rb:203:in `block in upload_tarball'
/gems/bosh_cli-1.1761.0/lib/cli/packaging_helper.rb:202:in `open'
/gems/bosh_cli-1.1761.0/lib/cli/packaging_helper.rb:202:in `upload_tarball'
/gems/bosh_cli-1.1761.0/lib/cli/packaging_helper.rb:58:in `build'
/gems/bosh_cli-1.1761.0/lib/cli/commands/release.rb:371:in `block in build_packages'
/gems/bosh_cli-1.1761.0/lib/cli/commands/release.rb:369:in `each'
/gems/bosh_cli-1.1761.0/lib/cli/commands/release.rb:369:in `build_packages'
/gems/bosh_cli-1.1761.0/lib/cli/commands/release.rb:314:in `create_from_spec'
/gems/bosh_cli-1.1761.0/lib/cli/commands/release.rb:48:in `create'
/gems/bosh_cli-1.1761.0/lib/cli/command_handler.rb:57:in `run'
/gems/bosh_cli-1.1761.0/lib/cli/runner.rb:56:in `run'
/gems/bosh_cli-1.1761.0/lib/cli/runner.rb:16:in `run'
/gems/bosh_cli-1.1761.0/bin/bosh:7:in `<top (required)>'
/bin/bosh:23:in `load'
/bin/bosh:23:in `<main>'
/bin/ruby_executable_hooks:15:in `eval'
/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by maverickart** [comment]
Anyone had a solution for this?
I seem to be having issues with uploading the blobs to S3as well.
Bosh version 6.2.1-a28042ac-2020-02-10T18:40:57Z

I get the following error:
_Uploading blobs:
  Creating blob for path 'ruxit/Dynatrace-OneAgent-Linux-1.193.159.sh':
    Creating blob in inner blobstore:
      Generating blobstore ID:
        the client operates in read only mode. Change 'credentials_source' parameter value_

My S3 access key in private.yaml below:

**---
blobstore:
  provider: s3
  options:
    access_key_id: <redacted>
    secret_access_key:<redacted>** 

The final.yaml is as below:
---
final_name: <redacted>
_blobstore:
  provider: s3
  options:
    region: ap-southeast-2
    endpoint: https://s3-ap-southeast-2.amazonaws.com
    bucket_name: <redacted>
    s3_endpoint: s3-ap-southeast-2.amazonaws.com_


I tried on a different machine with different set of keys but same issue.
