### ISSUE TITLE
"bosh aws create" failure in RDS create due to mysql version

### ISSUE THREAD

**Issue by davidillsley** [cloudfoundry/bosh#722]
I'm trying to get going with "bosh aws create" but it's failing as below. This is using us-east-1

I can't see a way to override the mysql version. Am I missing something?

```
$ bosh aws create
Executing migration CreateKeyPairs
allocating 1 KeyPair(s)
Executing migration CreateVpc
creating internet gateway
creating security groups: open, bosh, bat, cf, web
creating subnets: bosh1, bosh_rds1, cf_elb1, cf_rds1, services_rds1, cf1, services1, bosh_rds2, cf_elb2, cf_rds2, services_rds2
  Making subnet bosh1 10.10.0.0/24:
  Making subnet bosh_rds1 10.10.1.0/24:
  Making subnet cf_elb1 10.10.2.0/24:
  Making subnet cf_rds1 10.10.3.0/24:
  Making subnet services_rds1 10.10.8.0/21:
  Making subnet cf1 10.10.16.0/20:
  Making subnet services1 10.10.32.0/20:
  Making subnet bosh_rds2 10.10.65.0/24:
  Making subnet cf_elb2 10.10.66.0/24:
  Making subnet cf_rds2 10.10.67.0/24:
  Making subnet services_rds2 10.10.72.0/21:
    Making routing table for bosh1
    Binding default route to igw
    Making routing table for cf_elb1
    Binding default route to igw
    Making routing table for cf1
    Binding default route to cf_nat_box1
    Making routing table for services1
    Binding default route to cf_nat_box1
    Making routing table for cf_elb2
    Binding default route to igw
creating load balancers: cfrouter
adding CNAME record for *.aws1.###########.###
creating DHCP options
details in S3 receipt: aws_vpc_receipt and file: aws_vpc_receipt.yml
Executing migration CreateRoute53Records
allocating 3 elastic IP(s)
adding A record for micro.aws1.###########.###
adding A record for bat.aws1.###########.###
adding A record for bosh.aws1.###########.###
details in S3 receipt: aws_route53_receipt and file: aws_route53_receipt.yml
Executing migration CreateRdsDbs
details in S3 receipt: aws_rds_receipt and file: aws_rds_receipt.yml
/usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/aws-sdk-1.44.0/lib/aws/core/client.rb:375:in `return_or_raise': Cannot find version 5.5.31 for mysql (AWS::RDS::Errors::InvalidParameterCombination)
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/aws-sdk-1.44.0/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `create_db_instance'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh_cli_plugin_aws/rds.rb:38:in `create_database'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh_cli_plugin_aws/migration_helper.rb:46:in `create!'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/migrations/20130412183544_create_rds_dbs.rb:21:in `block in execute'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/migrations/20130412183544_create_rds_dbs.rb:17:in `each'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/migrations/20130412183544_create_rds_dbs.rb:17:in `execute'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh_cli_plugin_aws/migration.rb:21:in `run'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh_cli_plugin_aws/migrator.rb:75:in `block in run_migrations'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh_cli_plugin_aws/migrator.rb:74:in `each'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh_cli_plugin_aws/migrator.rb:74:in `run_migrations'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh_cli_plugin_aws/migrator.rb:13:in `migrate'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli_plugin_aws-1.2798.0/lib/bosh/cli/commands/aws.rb:130:in `create'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2798.0/lib/cli/command_handler.rb:57:in `run'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2798.0/lib/cli/runner.rb:56:in `run'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2798.0/lib/cli/runner.rb:16:in `run'
	from /usr/local/var/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2798.0/bin/bosh:7:in `<top (required)>'
	from /usr/local/var/rbenv/versions/1.9.3-p547/bin/bosh:23:in `load'
	from /usr/local/var/rbenv/versions/1.9.3-p547/bin/bosh:23:in `<main>'
```

**Comment by cppforlife** [comment]
There is no way to override it since `bosh aws create` tool was only meant to be used for quick dev setup. In your AWS account, do you not have default.mysql5.5 parameter group?

**Comment by owaism** [comment]
AWS has stopped support for MySql 5.5. 
I had to change the following code to get it working:
`<gems_location>/gems/ruby-1.9.3-p551/gems/bosh_cli_plugin_aws-1.2824.0/lib/bosh_cli_plugin_aws/rds.rb` to point to 5.6.21. Also had to change code in the same file to point to 5.6 (previously 5.5) Database Option Set.

@cppforlife what do you mean by `bosh aws create` is only meant for quick dev setup?  Followed the documentation provided here http://docs.cloudfoundry.org/deploying/ec2/ to deploy CloudFoundry to AWS. It does not tell that **Bootstrap on AWS VPC** is for dev setup only. 

Can you please elaborate? Also if this is for dev setup only, can you please point me to instructions which will help me deploy a production quality Cloud Foundry.

**Comment by cppforlife** [comment]
Closing. `bosh aws *` commands have been deprecated few months ago.
