### ISSUE TITLE
bosh upload release with insufficient local space

### ISSUE THREAD

**Issue by geokala** [cloudfoundry/bosh#751]
When the local disk has insufficient space and a 'bosh upload release' is run, the error received is a traceback complaining about lack of disk space, but it's not clear which system is out of space.

It would be useful if, instead of a traceback, the error would indicate that the local system was out of space.

The output was as follows:

```
# bosh upload release

Copying packages
----------------
ruby (cd102a7fe440fd9eaeee99c6bc460b06884cbda6) haproxy (917ceeaf9931e5c9e6921f61c5490be20a3051e6) dea_logging_agent (afa74c194ae7030e46961fabdb5c7984adcdb8ac) smoke-tests (e01d9d4046d95f59c66a7a47f8f0650ca6c5d487) postgres (b63fe0176a93609bd4ba44751ea490a3ee0f646c) buildpack_php (7ce5f94b4904cc67d9e5e964ffdab7f1572a7367) acceptance-tests (14abc1069a1941f08c2d4a44b21eaeeae1bf7e61) nats (cc6bda829a77ab2321c0c216aa9107aca92c3b1a) loggregator (63db903b803e215793789f7bdf98b561df37eb18) etcd (0171c102f5b67947021e271601122982607c9d59) sqlite (af44d44e58fffd069459cb63f6fcc37c6326e370) buildpack_ruby (dafbc4b72dfcdf5d19487dbcd5451d8cbe2e8866) login (edf41c9349e3eac12ef8a7a726570c0fecac5d03) golang (aa5f90f06ada376085414bfc0c56c8cd67abba9c) uaa (e95f22b7838e41bde03de3e10ffc5dddbfdfbd9a) nginx_newrelic_plugin (d3b2bdf36a2c5553e9fefcda0a93d0bed04c71c0) debian_nfs_server (aac05f22582b2f9faa6840da056084ed15772594) syslog_aggregator (4d4111ba19a8e7875184462d178fddb44fa87440) hm9000 (9595c4c0e16a261ccbeaea9b8edf6e87c3eaf159) buildpack_nodejs (bb0e4c1bb90effad1ffa50d2aa90e727a55039ff) cli (ec2ffd170251323e6ee11efbd8f5e61603aa6283) buildpack_cache (4ced0bc62f12dcaa79121718ca3525253ede33b5) libyaml (681bb455c35ef17cabbd41344f924cb61c2bb8e7) buildpack_java (08d7aa96c476559aa088a2e1f1c3fd812c36e2aa) cloud_controller_ng (41a73e0d71d88f9f29effdc1c6786425b2313b12) common (51c0a25512aa6e61c321a004e80ece95bf77e145) libpq (49cc7477fcf9a3fef7a1f61e1494b32288587ed8) collector (652024d837cb253df05e75ff0f500e4712bee659) gnatsd (3ade99da461f1744ad392da916afb1da5048b223) nginx (385ce4eca93c53c163ea82204a28e96d851bb65d) warden (5e6d50d31a878ee58e3fbfe397edd50a3877587b) buildpack_java_offline (546631e74a24465152b8553672ef2e30841afeaa) buildpack_python (d568479d7ef2a992f3e78a131e044ffe5a724b7b) metron_agent (e30b369f7640aa0ceedb43ec65d18ae6eb65e076) mysqlclient (8b5d9ce287341048377997a9b3fe4ff3e6a1c68f) gorouter (626050640d8da78ffa2724b34f1322115442e21d) rootfs_lucid64 (053c40914ab425794131d7d2c57943588d1e80be) /usr/lib/ruby/1.9.1/fileutils.rb:1372:in `copy_stream': No space left on device - write (Errno::ENOSPC)
    from /usr/lib/ruby/1.9.1/fileutils.rb:1372:in `block (2 levels) in copy_file'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1371:in `open'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1371:in `block in copy_file'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1370:in `open'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1370:in `copy_file'
    from /usr/lib/ruby/1.9.1/fileutils.rb:477:in `copy_file'
    from /usr/lib/ruby/1.9.1/fileutils.rb:396:in `block in cp'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
    from /usr/lib/ruby/1.9.1/fileutils.rb:395:in `cp'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/release_compiler.rb:58:in `block in compile'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/release_compiler.rb:51:in `each'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/release_compiler.rb:51:in `compile'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/commands/release/upload_release.rb:61:in `upload_manifest'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/commands/release/upload_release.rb:39:in `upload'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/command_handler.rb:57:in `run'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/runner.rb:56:in `run'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/lib/cli/runner.rb:16:in `run'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2839.0/bin/bosh:7:in `<top (required)>'
    from /usr/local/bin/bosh:23:in `load'
    from /usr/local/bin/bosh:23:in `<main>'
```

**Comment by cppforlife** [comment]
Agreed. Good suggestion.

**Comment by cwb124** [comment]
Geokala, when you got this error did you determine if the disk space issues was on the local box or the director?

**Comment by geokala** [comment]
Hi cwb124,
It's been a while now so my memory may be faulty but I think it was the local machine (the one on which the bosh CLI was being run, not the director).

**Comment by dpb587-pivotal** [comment]
Agreed, this error comes from the local system running out of space.

Since this issue, we have released a new version of the BOSH CLI (found in [cloudfoundry/bosh-cli](https://github.com/cloudfoundry/bosh-cli)). It handles error reporting slightly differently (and hopefully better in this situation), so I'm going to close this issue in this repo.

Please feel free to create new issues in the bosh-cli repo, or join us on [cloudfoundry#bosh](http://slack.cloudfoundry.org) slack for more help or guidance when starting to use the new CLI!
