### ISSUE TITLE
fail to stemcell:build_with_local_os_image[openstack,kvm,centos,7,go,/tmp/bosh-centos-7-os-image.tgz]

### ISSUE THREAD

**Issue by guanglinlv** [cloudfoundry/bosh#801]
`bosh-centos-7-os-image.tgz` is got from `https://s3.amazonaws.com/bosh-os-images/bosh-centos-7-os-image.tgz`

build command:
```sh
root@lv:~/workspace/bosh/bosh# bundle exec rake  stemcell:build_with_local_os_image[openstack,kvm,centos,7,go,/tmp/bosh-centos-7-os-image.tgz]
```

failure output:
```sh
sudo: unable to resolve host lv
      should be installed
    Package "zip"
sudo: unable to resolve host lv
      should be installed
  installed by system_grub
    Package "grub2-tools"
sudo: unable to resolve host lv
      should be installed
sudo: unable to resolve host lv

Failures:

  1) CentOS 7 OS image behaves like a CentOS or RHEL based OS image installed by base_ssh disallows insecure HMACs
     Failure/Error: expect(sshd_config).to contain(/^MACs #{macs}$/)
       expected File "/etc/ssh/sshd_config" to contain /^MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160$/
     Shared Example Group: "a CentOS or RHEL based OS image" called from ./spec/os_image/centos_7_spec.rb:5
     # ./spec/support/os_image_centos_rhel_shared_examples.rb:53:in `block (3 levels) in <top (required)>'

Finished in 40.74 seconds (files took 0.67084 seconds to load)
80 examples, 1 failure

Failed examples:

rspec ./spec/support/os_image_centos_rhel_shared_examples.rb:47 # CentOS 7 OS image behaves like a CentOS or RHEL based OS image installed by base_ssh disallows insecure HMACs
rake aborted!
Command failed with status (1): [cd /root/workspace/bosh/bosh/bosh-stemcell...]
/root/workspace/bosh/bosh/bosh-dev/lib/bosh/dev/tasks/stemcell.rake:108:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => stemcell:build_with_local_os_image
(See full trace by running task with --trace)
```

any help ? thanks

**Comment by guanglinlv** [comment]
I update the bosh to latest and try to build stemcell again, i got some new errors :

```sh
Failures:

  1) CentOS OS image behaves like an OS image installed by rsyslog File "/etc/init/rsyslog.conf" should contain "/usr/local/sbin/rsyslogd"
     Failure/Error: it { should contain('/usr/local/sbin/rsyslogd') }
       grep -q -- /usr/local/sbin/rsyslogd /etc/init/rsyslog.conf || grep -qF -- /usr/local/sbin/rsyslogd /etc/init/rsyslog.conf
       grep: /etc/init/rsyslog.conf: No such file or directory

       expected File "/etc/init/rsyslog.conf" to contain "/usr/local/sbin/rsyslogd"
     Shared Example Group: "an OS image" called from ./spec/os_image/centos_spec.rb:4
     # ./spec/support/os_image_shared_examples.rb:31:in `block (4 levels) in <top (required)>'

  2) CentOS OS image behaves like an OS image installed by rsyslog Command "rsyslogd -v" should return stdout /7\.4\.6/
     Failure/Error: it { should return_stdout /7\.4\.6/ }
       rsyslogd -v
       rsyslogd 7.4.7, compiled with:
	FEATURE_REGEXP:				Yes
	FEATURE_LARGEFILE:			No
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes

See http://www.rsyslog.com for more information.

       expected Command "rsyslogd -v" to return stdout /7\.4\.6/
     Shared Example Group: "an OS image" called from ./spec/os_image/centos_spec.rb:4
     # ./spec/support/os_image_shared_examples.rb:53:in `block (4 levels) in <top (required)>'

  3) CentOS OS image behaves like an OS image installed by rsyslog Service "rsyslog" should be enabled
     Failure/Error: it { should be_enabled.with_level(2) }
       systemctl --plain list-dependencies runlevel2.target | grep '^rsyslog.service$'
       expected Service "rsyslog" to be enabled
     Shared Example Group: "an OS image" called from ./spec/os_image/centos_spec.rb:4
     # ./spec/support/os_image_shared_examples.rb:63:in `block (4 levels) in <top (required)>'

  4) CentOS OS image behaves like an OS image installed by rsyslog Service "rsyslog" should be enabled
     Failure/Error: it { should be_enabled.with_level(3) }
       systemctl --plain list-dependencies runlevel3.target | grep '^rsyslog.service$'
       expected Service "rsyslog" to be enabled
     Shared Example Group: "an OS image" called from ./spec/os_image/centos_spec.rb:4
     # ./spec/support/os_image_shared_examples.rb:64:in `block (4 levels) in <top (required)>'

  5) CentOS OS image behaves like an OS image installed by rsyslog Service "rsyslog" should be enabled
     Failure/Error: it { should be_enabled.with_level(4) }
       systemctl --plain list-dependencies runlevel4.target | grep '^rsyslog.service$'
       expected Service "rsyslog" to be enabled
     Shared Example Group: "an OS image" called from ./spec/os_image/centos_spec.rb:4
     # ./spec/support/os_image_shared_examples.rb:65:in `block (4 levels) in <top (required)>'

  6) CentOS OS image behaves like an OS image installed by rsyslog Service "rsyslog" should be enabled
     Failure/Error: it { should be_enabled.with_level(5) }
       systemctl --plain list-dependencies runlevel5.target | grep '^rsyslog.service$'
       expected Service "rsyslog" to be enabled
     Shared Example Group: "an OS image" called from ./spec/os_image/centos_spec.rb:4
     # ./spec/support/os_image_shared_examples.rb:66:in `block (4 levels) in <top (required)>'

  7) CentOS OS image installed by base_centos File "/etc/sysconfig/i18n" should be file
     Failure/Error: it { should be_file }
       test -f /etc/sysconfig/i18n
       expected file? to return true, got false
     # ./spec/os_image/centos_spec.rb:34:in `block (4 levels) in <top (required)>'

  8) CentOS OS image installed by base_centos File "/etc/sysconfig/i18n" should contain "en_US.UTF-8"
     Failure/Error: it { should contain 'en_US.UTF-8' }
       grep -q -- en_US.UTF-8 /etc/sysconfig/i18n || grep -qF -- en_US.UTF-8 /etc/sysconfig/i18n
       grep: /etc/sysconfig/i18n: No such file or directory

       expected File "/etc/sysconfig/i18n" to contain "en_US.UTF-8"
     # ./spec/os_image/centos_spec.rb:35:in `block (4 levels) in <top (required)>'

  9) CentOS OS image installed by base_yum Package "upstart" should be installed
     Failure/Error: it { should be_installed }
       rpm -q upstart
       warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
package upstart is not installed

       expected Package "upstart" to be installed
     # ./spec/os_image/centos_spec.rb:78:in `block (5 levels) in <top (required)>'

  10) CentOS OS image installed by base_yum Package "nc" should be installed
     Failure/Error: it { should be_installed }
       rpm -q nc
       warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
package nc is not installed

       expected Package "nc" to be installed
     # ./spec/os_image/centos_spec.rb:78:in `block (5 levels) in <top (required)>'

  11) CentOS OS image installed by system_grub Package "grub" should be installed
     Failure/Error: it { should be_installed }
       rpm -q grub
       warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
package grub is not installed

       expected Package "grub" to be installed
     # ./spec/os_image/centos_spec.rb:85:in `block (4 levels) in <top (required)>'

  12) CentOS OS image File "/boot/grub/e2fs_stage1_5" should be file
     Failure/Error: it { should be_file }
       test -f /boot/grub/e2fs_stage1_5
       expected file? to return true, got false
     # ./spec/os_image/centos_spec.rb:91:in `block (4 levels) in <top (required)>'

  13) CentOS OS image File "/boot/grub/stage1" should be file
     Failure/Error: it { should be_file }
       test -f /boot/grub/stage1
       expected file? to return true, got false
     # ./spec/os_image/centos_spec.rb:91:in `block (4 levels) in <top (required)>'

  14) CentOS OS image File "/boot/grub/stage2" should be file
     Failure/Error: it { should be_file }
       test -f /boot/grub/stage2
       expected file? to return true, got false
     # ./spec/os_image/centos_spec.rb:91:in `block (4 levels) in <top (required)>'

Finished in 29.81 seconds
71 examples, 14 failures
```

**Comment by cppforlife** [comment]
Our CI shows it as green. Which branch are you using? We did make few changes to centos stemcell building recently. Trying to run it myself...

**Comment by cppforlife** [comment]
I checked out latest master (which is stable; 8ca8c18d4987573eb0a5eb4ce2c3ca69f4f5a060) and ran following commands which succeeded:

```
cd /bosh
bundle exec rake stemcell:build_os_image[centos,7,/tmp/bosh-centos-7-os-image.tgz]
bundle exec rake  stemcell:build_with_local_os_image[openstack,kvm,centos,7,go,/tmp/bosh-centos-7-os-image.tgz]
```

**Comment by cppforlife** [comment]
Closing. Reopen if problem still happens.
