### ISSUE TITLE
build rhel stemcell failed by RHEL 7 stemcell behaves like a CentOS 7 or RHEL 7 stemcell installed by image_vsphere_cdrom stage File "/etc/sysctl.conf" should contain "dev.cdrom.lock=0"

### ISSUE THREAD

**Issue by dwu-pivotal** [cloudfoundry/bosh#809]
Failures:

  1) RHEL 7 stemcell behaves like a CentOS 7 or RHEL 7 stemcell installed by image_vsphere_cdrom stage File "/etc/sysctl.conf" should contain "dev.cdrom.lock=0"
     Failure/Error: it { should contain 'dev.cdrom.lock=0' }
       expected File "/etc/sysctl.conf" to contain "dev.cdrom.lock=0"
     Shared Example Group: "a CentOS 7 or RHEL 7 stemcell" called from ./spec/stemcells/rhel_7_spec.rb:6
     # ./spec/support/stemcell_centos_rhel_7_shared_examples.rb:65:in `block (4 levels) in <top (required)>'
     # ./spec/support/stemcell_image.rb:8:in`block (3 levels) in <top (required)>'
     # ./lib/bosh/stemcell/disk_image.rb:35:in `while_mounted'
     # ./spec/support/stemcell_image.rb:6:in`block (2 levels) in <top (required)>'

**Comment by jfmyers9** [comment]
Closing due to inactivity. If this is still an issue on recent stemcells please open a new issue in https://github.com/cloudfoundry/bosh-linux-stemcell-builder
