### ISSUE TITLE
'bosh validate jobs' fails

### ISSUE THREAD

**Issue by Nopik** [cloudfoundry/bosh#810]
```
Processing deployment manifest
------------------------------
Getting deployment properties from director...
Compiling deployment manifest...

Analyzing release directory...
 - discovering packages
 - discovering jobs
/Users/nopik/.rvm/gems/ruby-2.2.1@bosh/gems/bosh_cli-1.2941.0/lib/cli/commands/deployment.rb:165:in `block in validate_jobs': undefined method `[]' for #<Bosh::Cli::Resources::Package:0x007fb323434378> (NoMethodError)
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/gems/bosh_cli-1.2941.0/lib/cli/commands/deployment.rb:165:in `map'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/gems/bosh_cli-1.2941.0/lib/cli/commands/deployment.rb:165:in `validate_jobs'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/gems/bosh_cli-1.2941.0/lib/cli/command_handler.rb:57:in `run'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/gems/bosh_cli-1.2941.0/lib/cli/runner.rb:56:in `run'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/gems/bosh_cli-1.2941.0/bin/bosh:16:in `<top (required)>'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/bin/bosh:23:in `load'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/bin/bosh:23:in `<main>'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/bin/ruby_executable_hooks:15:in `eval'
    from /Users/nopik/.rvm/gems/ruby-2.2.1@bosh/bin/ruby_executable_hooks:15:in `<main>'
```

Looking at respective part of the code shows:

```
      jobs = Bosh::Cli::Resources::Job.discover(
        work_dir,
        # TODO: be sure this is covered in integration
        packages.map {|package| package['name']}
      )
```

And replacing ['name'] with .name makes the problem go away. I guess it wasn't covered by integration after all.

**Comment by dpb587-pivotal** [comment]
Closing - we're no longer supporting the `validate-jobs` command in the [upcoming go cli](https://github.com/cloudfoundry/bosh-cli). It was conflating deployment processes with release management processes and didn't catch all potential issues anyway.
