### ISSUE TITLE
bosh cck fails for compilation vms

### ISSUE THREAD

**Issue by Nopik** [cloudfoundry/bosh#813]
I've installed fresh bosh-lite from scratch, trying to get concourse installed on it. I'm using bosh-lite.yml concourse manifest provided by concourse repo. On first try deploy failed (http://pastebin.com/uqtbK2eA), but it managed to create some vm. That vm, however, seems to be unresponsive. When I did cck, it failed:

```
38149 10:16:46 NopiLaptop ~/Warsztat/bosh-lite$ bosh deploy

Processing deployment manifest
------------------------------
Getting deployment properties from director...
Compiling deployment manifest...
Please review all changes carefully

Deploying
---------
Deployment name: `bosh-lite.yml'
Director name: `Bosh Lite Director'
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 7
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:00)
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Failed: Timed out sending `get_state' to 5960ff84-768a-4d6d-b965-398fa3d00064 after 45 seconds (00:02:15)

Error 450002: Timed out sending `get_state' to 5960ff84-768a-4d6d-b965-398fa3d00064 after 45 seconds

Task 7 error

For a more detailed error report, run: bosh task 7 --debug
38150 10:20:38 NopiLaptop ~/Warsztat/bosh-lite$ bosh vms
Deployment `concourse'

Director task 8

Task 8 done

+-----------------+--------------------+---------------+-----+
| Job/index       | State              | Resource Pool | IPs |
+-----------------+--------------------+---------------+-----+
| unknown/unknown | unresponsive agent |               |     |
+-----------------+--------------------+---------------+-----+

VMs total: 1
38151 10:21:00 NopiLaptop ~/Warsztat/bosh-lite$ bosh cck
Performing cloud check...

Processing deployment manifest
------------------------------

Director task 9
  Started scanning 1 vms
  Started scanning 1 vms > Checking VM states. Done (00:00:10)
  Started scanning 1 vms > 0 OK, 0 unresponsive, 1 missing, 0 unbound, 0 out of sync. Done (00:00:00)
     Done scanning 1 vms (00:00:10)

  Started scanning 0 persistent disks
  Started scanning 0 persistent disks > Looking for inactive disks. Done (00:00:00)
  Started scanning 0 persistent disks > 0 OK, 0 missing, 0 inactive, 0 mount-info mismatch. Done (00:00:00)
     Done scanning 0 persistent disks (00:00:00)

Task 9 done

Started     2015-04-29 08:21:07 UTC
Finished    2015-04-29 08:21:17 UTC
Duration    00:00:10

Scan is complete, checking if any problems found...

Found 1 problem

Problem 1 of 1: VM with cloud ID `d3b58f1e-03cf-4e13-50a5-879632141a8c' missing.
  1. Ignore problem
  2. Recreate VM using last known apply spec
  3. Delete VM reference (DANGEROUS!)
Please choose a resolution [1 - 3]: 2

Below is the list of resolutions you've provided
Please make sure everything is fine and confirm your changes

  1. VM with cloud ID `d3b58f1e-03cf-4e13-50a5-879632141a8c' missing.
     Recreate VM using last known apply spec

Apply resolutions? (type 'yes' to continue): yes
Applying resolutions...

Director task 10
  Started applying problem resolutions > missing_vm 3: Recreate VM using last known apply spec. Failed: undefined method `fetch' for "package_compiler":String (00:00:00)

Task 10 done

Started     2015-04-29 08:21:34 UTC
Finished    2015-04-29 08:21:34 UTC
Duration    00:00:00
Cloudcheck is finished
38152 10:21:35 NopiLaptop ~/Warsztat/bosh-lite$ bosh task 10 --debug

Director task 10
I, [2015-04-29T08:21:33.360103 #1731] [0x3f92757b3328]  INFO -- TaskHelper: Director Version: 1.2922.0
I, [2015-04-29T08:21:33.360145 #1731] [0x3f92757b3328]  INFO -- TaskHelper: Enqueuing task: 10
I, [2015-04-29 08:21:34 #6192] []  INFO -- DirectorJobRunner: Looking for task with task id 10
D, [2015-04-29 08:21:34 #6192] [] DEBUG -- DirectorJobRunner: (0.000726s) SELECT * FROM "tasks" WHERE "id" = 10
I, [2015-04-29 08:21:34 #6192] []  INFO -- DirectorJobRunner: Starting task: 10
I, [2015-04-29 08:21:34 #6192] [task:10]  INFO -- DirectorJobRunner: Creating job
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000577s) SELECT * FROM "deployments" WHERE ("name" = 'concourse') LIMIT 1
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000438s) SELECT * FROM "tasks" WHERE "id" = 10
I, [2015-04-29 08:21:34 #6192] [task:10]  INFO -- DirectorJobRunner: Performing task: 10
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000299s) BEGIN
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000464s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2015-04-29 08:21:34.611388+0000', "description" = 'apply resolutions', "result" = NULL, "output" = '/var/vcap/store/director/tasks/10', "checkpoint_time" = '2015-04-29 08:21:34.611478+0000', "type" = 'cck_apply', "username" = 'admin' WHERE ("id" = 10)
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.001049s) COMMIT
I, [2015-04-29 08:21:34 #6192] [task:10]  INFO -- DirectorJobRunner: Acquiring deployment lock on concourse
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: Acquiring lock: lock:deployment:concourse
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: Acquired lock: lock:deployment:concourse
D, [2015-04-29 08:21:34 #6192] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:concourse
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000761s) SELECT COUNT(*) AS "count" FROM "deployment_problems" WHERE ("id" IN ('1')) LIMIT 1
I, [2015-04-29 08:21:34 #6192] [task:10]  INFO -- DirectorJobRunner: Applying problem resolutions
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000332s) SELECT * FROM "deployment_problems" WHERE ("id" IN ('1'))
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000928s) SELECT * FROM "vms" WHERE "id" = 3
I, [2015-04-29 08:21:34 #6192] [task:10]  INFO -- DirectorJobRunner: missing_vm 3: Recreate VM using last known apply spec
E, [2015-04-29 08:21:34 #6192] [task:10] ERROR -- DirectorJobRunner: Error resolving problem `1': undefined method `fetch' for "package_compiler":String
E, [2015-04-29 08:21:34 #6192] [task:10] ERROR -- DirectorJobRunner: /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/cloudcheck_helper.rb:95:in `recreate_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_handlers/missing_vm.rb:22:in `block (2 levels) in <class:MissingVM>'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_handlers/base.rb:83:in `instance_eval'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_handlers/base.rb:83:in `apply_resolution'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_resolver.rb:59:in `block in apply_resolution'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_resolver.rb:23:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_resolver.rb:21:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_resolver.rb:58:in `apply_resolution'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_resolver.rb:42:in `block in apply_resolutions'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:152:in `block in each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:525:in `block (2 levels) in fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:720:in `block in yield_hash_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:714:in `times'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:714:in `yield_hash_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:525:in `block in fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:134:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:413:in `_execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:425:in `check_database_errors'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:801:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:525:in `fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:152:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/problem_resolver.rb:33:in `apply_resolutions'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/cloud_check/apply_resolutions.rb:38:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock_helper.rb:21:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock_helper.rb:21:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/cloud_check/apply_resolutions.rb:37:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:108:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.2922.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/bin/bosh-director-worker:75:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:concourse
D, [2015-04-29 08:21:34 #6192] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:concourse
I, [2015-04-29 08:21:34 #6192] [task:10]  INFO -- DirectorJobRunner: Done
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000233s) BEGIN
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000407s) UPDATE "tasks" SET "state" = 'done', "timestamp" = '2015-04-29 08:21:34.621126+0000', "description" = 'apply resolutions', "result" = '0 resolved', "output" = '/var/vcap/store/director/tasks/10', "checkpoint_time" = '2015-04-29 08:21:34.611478+0000', "type" = 'cck_apply', "username" = 'admin' WHERE ("id" = 10)
D, [2015-04-29 08:21:34 #6192] [task:10] DEBUG -- DirectorJobRunner: (0.000557s) COMMIT
I, [2015-04-29 08:21:34 #6192] []  INFO -- DirectorJobRunner: Task took 0.014426424 seconds to process.

Task 10 done
```

**Comment by Nopik** [comment]
FYI, I didn't managed to get that vm in order. I did bosh `delete deployment concourse` and then  `bosh deploy` again and it worked.

**Comment by bosh-ci-push-pull** [comment]
Yeah there is a known bug about `bosh cck` deleting compilation VMs (undefined
method `fetch' for "package_compiler"). Here is the story to fix that:
https://www.pivotaltracker.com/story/show/69672460

**Comment by cppforlife** [comment]
Closing. Fixed few months ago.
