### ISSUE TITLE
"bosh delete release" raises an exception if object is missing from the blobstore.

### ISSUE THREAD

**Issue by aalbanes** [cloudfoundry/bosh#877]
Hi all,
I am working on MicroBosh  recovery scenarios, and right now I am evaluating a recovery approach based on  Director DB backup. 

In the specific, the following scenario is generating an Issue:

<H2>Scenario:</H2>
- Step 1: bosh upload release
- Step 2: backup db
- Step 3: bosh delete release
- Step 4: restore db backup on same server as in Step2

At this point in time we have that release's objects references are present into DB but objects are not existing anymore in the blobstore. 

In order to fix this situation we would like to  run a "bosh delete release" to purge object in DB and get back a clean situation. However running that command I got the following Error:

 
```
Error 30009: Can't delete release: Could not delete object, 404
task log

I, [2015-07-07 13:25:10 #2606] [task:114] INFO -- DirectorJobRunner: Deleting package admin_ui_v2/6d0b30dafde326260ca849f64b4f6b58c1e131da
W, [2015-07-07 13:25:10 #2606] [task:114] WARN -- DirectorJobRunner: Could not delete from blobstore: Could not delete object, 404/<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.2922.0/lib/blobstore_client/dav_blobstore_client.rb:57:in `delete_object'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.2922.0/lib/blobstore_client/base.rb:69:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:207:in `delete_blobstore_id'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:140:in `delete_package'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:56:in `block (2 levels) in delete_release_version'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:48:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:46:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:52:in `block in delete_release_version'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:51:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:51:in `delete_release_version'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:179:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock_helper.rb:47:in `block in with_release_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock_helper.rb:47:in `with_release_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:158:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:108:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.2922.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/bin/bosh-director-worker:75:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
I, [2015-07-07 13:25:10 #2606] [task:114] INFO -- DirectorJobRunner: admin_ui_v2/067b386d7fbf13a710aa13bc7f25802df6a43727
I, [2015-07-07 13:25:10 #2606] [task:114] INFO -- DirectorJobRunner: Template admin_ui_v2/067b386d7fbf13a710aa13bc7f25802df6a43727 is only used by this release version and will be deleted
I, [2015-07-07 13:25:10 #2606] [task:114] INFO -- DirectorJobRunner: Deleting template: admin_ui_v2/067b386d7fbf13a710aa13bc7f25802df6a43727
W, [2015-07-07 13:25:10 #2606] [task:114] WARN -- DirectorJobRunner: Could not delete from blobstore: Could not delete object, 404/<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.2922.0/lib/blobstore_client/dav_blobstore_client.rb:57:in `delete_object'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.2922.0/lib/blobstore_client/base.rb:69:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:207:in `delete_blobstore_id'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:149:in `delete_template'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:72:in `block (2 levels) in delete_release_version'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:48:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:46:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:68:in `block in delete_release_version'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:67:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:67:in `delete_release_version'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:179:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock_helper.rb:47:in `block in with_release_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock.rb:56:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/lock_helper.rb:47:in `with_release_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:158:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:108:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.2922.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/bin/bosh-director-worker:75:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
I, [2015-07-07 13:25:10 #2606] [task:114] INFO -- DirectorJobRunner: Remove all deployments in release version
D, [2015-07-07 13:25:10 #2606] [task:114] DEBUG -- DirectorJobRunner: (0.000767s) DELETE FROM "deployments_release_versions" WHERE ("release_version_id" = 9)
D, [2015-07-07 13:25:10 #2606] [task:114] DEBUG -- DirectorJobRunner: (0.000458s) SELECT * FROM "release_versions" WHERE ("release_versions"."release_id" = 5)
D, [2015-07-07 13:25:10 #2606] [task:114] DEBUG -- DirectorJobRunner: Deleting lock: lock:release:admin-ui
D, [2015-07-07 13:25:10 #2606] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2015-07-07 13:25:10 #2606] [task:114] DEBUG -- DirectorJobRunner: Deleted lock: lock:release:admin-ui
E, [2015-07-07 13:25:10 #2606] [task:114] ERROR -- DirectorJobRunner: Can't delete release: Could not delete object, 404/<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
, Could not delete object, 404/<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/delete_release.rb:198:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:108:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.2922.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/job_runner.rb:31:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/bin/bosh-director-worker:75:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
D, [2015-07-07 13:25:10 #2606] [task:114] DEBUG -- DirectorJobRunner: (0.000343s) BEGIN
D, [2015-07-07 13:25:10 #2606] [task:114] DEBUG -- DirectorJobRunner: (0.000484s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2015-07-07 13:25:10.306961+0000', "description" = 'delete release: admin-ui', "result" = 'Can''t delete release: Could not delete object, 404/<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">...', "output" = '/var/vcap/store/director/tasks/114', "checkpoint_time" = '2015-07-07 13:25:10.271257+0000', "type" = 'delete_release', "username" = 'admin' WHERE ("id" = 114)
D, [2015-07-07 13:25:10 #2606] [task:114] DEBUG -- DirectorJobRunner: (0.000949s) COMMIT
I, [2015-07-07 13:25:10 #2606] [] INFO -- DirectorJobRunner: Task took 0.04023716 seconds to process.

Task 114 error 

```
In my opinion this is a defect. If I'm trying to delete a record in the blobstore that is no more there, it should ignore the exception and go ahead with the deletion

Thx
Angelo

**Comment by cppforlife** [comment]
`bosh delete release` has a --force flag to ignore errors. Ideally new flag would be introduced (--fix) to the bosh upload release so that DB and blobstore objects would be fixed if they do not match/exist expected values.
