### ISSUE TITLE
`bosh scp` cleans ssh artifacts before file is copied

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh#885]
```
Processing deployment manifest
------------------------------
Target deployment is `xxx'

Setting up ssh artifacts

Director task 13

Task 13 done

Cleaning up ssh artifacts

Director task 14

Task 14 done
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-scp-1.1.2/lib/net/scp.rb:359:in `block (3 levels) in start_command': SCP did not finish successfully (1) (Net::SCP::Error)
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:591:in `call'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:591:in `do_close'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:586:in `channel_close'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-scp-1.1.2/lib/net/scp.rb:316:in `download!'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:220:in `block (3 levels) in perform_operation'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:263:in `block in with_ssh'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/net-ssh-2.9.1/lib/net/ssh.rb:210:in `start'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:263:in `with_ssh'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:209:in `block (2 levels) in perform_operation'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:204:in `each'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:204:in `block in perform_operation'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:153:in `setup_ssh'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:203:in `perform_operation'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/commands/ssh.rb:64:in `scp'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/command_handler.rb:57:in `run'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/runner.rb:56:in `run'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/lib/cli/runner.rb:16:in `run'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/bosh_cli-1.2789.0/bin/bosh:7:in `<top (required)>'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/bosh:23:in `load'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/bosh:23:in `<main>'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

`BOSH 1.2789.0`

**Comment by dpb587-pivotal** [comment]
This can error can happen when you try to download a file, but specify a destination file path instead of a destination directory. CLI generates the actual file name in that destination directory based on the job name where the file came from (useful when downloading from multiple instances). When passing a path, scp fails because it ends up trying to do `/tmp/myfile.tgz/sourcefilename.ext.job_index`.

I don't think it is actually cleaning up the ssh artifacts before scp'ing, just that error occurred and it waits to dump out the error until everything is cleaned up.

**Comment by jfmyers9** [comment]
Closing this due to inactivity. The [bosh cli](https://github.com/cloudfoundry/bosh-cli) has been rewritten in golang and has changed the `scp`/`ssh` behavior quite a lot. Feel free to create a new issue on the repository if you are still seeing this issue.
