### ISSUE TITLE
Uninitialized constant Bosh::Registry::AwsError

### ISSUE THREAD

**Issue by gerhard** [cloudfoundry/bosh#889]
This was triggered by an AWS secret key that was ending in `/`. It was generated by IAM, definitely legit. This was happening on bosh-registry-1.2989.0. It might have been fixed since, but just in case it catches someone else out:

```
NameError - uninitialized constant Bosh::Registry::AwsError:
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/lib/bosh/registry/instance_manager/aws.rb:55:in `rescue in instance_ips'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/lib/bosh/registry/instance_manager/aws.rb:48:in `instance_ips'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/lib/bosh/registry/instance_manager.rb:45:in `check_instance_ips'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/lib/bosh/registry/instance_manager.rb:29:in `read_settings'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/lib/bosh/registry/api_controller.rb:22:in `block in <class:ApiController>'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/lib/bosh/registry/runner.rb:34:in `start_http_server'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/lib/bosh/registry/runner.rb:18:in `run'
        /var/vcap/packages/registry/gem_home/ruby/2.1.0/gems/bosh-registry-1.2989.0/bin/bosh-registry:28:in `<top (required)>'
        /var/vcap/packages/registry/bin/bosh-registry:16:in `load'
        /var/vcap/packages/registry/bin/bosh-registry:16:in `<main>'
```

**Comment by cppforlife** [comment]
We have recently made changes to the bosh release to properly escape registry configuration. I believe this error is not fixed.
