### ISSUE TITLE
[openstack] Deleting VM fails when 'boot_from_volume' is true

### ISSUE THREAD

**Issue by msschwartz** [cloudfoundry/bosh#921]
When using the following OpenStack configuration, I keep getting 404s when running a deployment that requires deletion of a VM. This was happening on BOSH v1.3033.0.

```
openstack:
      auth_url: http://openstack.com:5000/v2.0/tokens
      username: bosh
      api_key: bosh
      tenant: bosh
      default_key_name: bosh
      default_security_groups: ["bosh"]
      boot_from_volume: true
```

```
Director task 286
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

  Started preparing deployment
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:01)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started preparing dns > Binding DNS. Done (00:00:00)

  Started preparing configuration > Binding configuration. Done (00:00:02)

  Started updating job hm9000_z1 > hm9000_z1/0 (canary). Failed: Cannot delete settings for 'hm9000_z1/0', got HTTP 404 (00:00:27)

Error 100: Cannot delete settings for 'hm9000_z1/0', got HTTP 404

Task 286 error
```

```
I, [2015-08-11 16:25:59 #13765] [canary_update(hm9000_z1/0)]  INFO -- DirectorJobRunner: Deleting VM
D, [2015-08-11 16:25:59 #13765] [canary_update(hm9000_z1/0)] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"delete_vm","arguments":["57824336-6a83-400e-bd47-4d7c0e7e678c"],"context":{"director_uuid":"99813423-686d-47a8-bb63-a03b7eb315b6"}} with command: /var/vcap/jobs/cpi/bin/cpi
D, [2015-08-11 16:26:24 #13765] [canary_update(hm9000_z1/0)] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Cannot delete settings for 'hm9000_z1/0', got HTTP 404","ok_to_retry":false},"log":"Rescued Bosh::Clouds::CloudError: Cannot delete settings for 'hm9000_z1/0', got HTTP 404. backtrace: /var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh-registry-1.2978.0/lib/bosh/registry/client.rb:121:in `cloud_error'\n/var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh-registry-1.2978.0/lib/bosh/registry/client.rb:112:in `delete_settings'\n/var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.2978.0/lib/cloud/openstack/cloud.rb:334:in `block in delete_vm'\n/var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_common-1.2978.0/lib/common/thread_formatter.rb:49:in `with_thread_name'\n/var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.2978.0/lib/cloud/openstack/cloud.rb:326:in `delete_vm'\n/var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_cpi-1.2978.0/lib/bosh/cpi/cli.rb:70:in `public_send'\n/var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_cpi-1.2978.0/lib/bosh/cpi/cli.rb:70:in `run'\n/var/vcap/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.2978.0/bin/openstack_cpi:20:in `<top (required)>'\n/var/vcap/packages/bosh_openstack_cpi/bin/openstack_cpi:16:in `load'\n/var/vcap/packages/bosh_openstack_cpi/bin/openstack_cpi:16:in `<main>'"}, err: D, [2015-08-11T16:26:01.865193 #14103] DEBUG -- : excon.request {:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.27.0 fog-core/1.30.0", "Content-Type"=>"application/json", "Host"=>"openstack.com:5000"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.3 (x86_64-linux) ruby/1.9.3", :write_timeout=>60, :host=>"openstack.com", :hostname=>"openstack.com", :path=>"/v2.0/tokens", :port=>5000, :query=>nil, :scheme=>"http", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor, :expects=>[200, 204], :body=>"{\"auth\":{\"passwordCredentials\":{\"username\":\"bosh\",\"password\":\"bosh\"},\"tenantName\":\"bosh\"}}", :method=>"POST", :retries_remaining=>4, :connection=>#<Excon::Connection:35b8ee0 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.27.0 fog-core/1.30.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.3 (x86_64-linux) ruby/1.9.3", :write_timeout=>60, :host=>"openstack.com", :hostname=>"openstack.com", :path=>"/v2.0/tokens", :port=>5000, :query=>nil, :scheme=>"http", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="http://10.89.20.12:5000">, :stack=>#<Excon::Middleware::ResponseParser:0x0000000372bdb8 @stack=#<Excon::Middleware::Expects:0x0000000372bde0 @stack=#<Excon::Middleware::Idempotent:0x0000000372bf70 @stack=#<Excon::Middleware::Instrumentor:0x0000000372bf98 @stack=#<Excon::Middleware::Mock:0x0000000372c060 @stack=#<Excon::Connection:35b8ee0 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.27.0 fog-core/1.30.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.3 (x86_64-linux) ruby/1.9.3", :write_timeout=>60, :host=>"openstack.com", :hostname=>"openstack.com", :path=>"/v2.0/tokens", :port=>5000, :query=>nil, :scheme=>"http", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="http://openstack.com:5000">>>>>>}
```

**Comment by msschwartz** [comment]
The error was happening because the VM was renamed. _boot_from_volume_ value was irrelevant.

**Comment by cppforlife** [comment]
Seems like CPI should be resilient to this failure and ignore it. We will fix it: https://www.pivotaltracker.com/story/show/101130258
