### ISSUE TITLE
Error on running errand

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry/bosh#993]
Encountered following error when running errand using bosh v216.
```
$ bosh run errand diego-acceptance-tests
Acting as user 'admin' on deployment 'diego-openstack' on 'bosh'

Director task 3910
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

  Started preparing deployment
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started preparing dns > Binding DNS. Done (00:00:00)

Error 100: undefined method `cid' for nil:NilClass

Task 3910 error

Errand `diego-acceptance-tests' did not complete

For a more detailed error report, run: bosh task 3910 --debug
```

Following more detailed logs.
```
D, [2015-10-23 04:15:33 #5093] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: undefined method `cid' for nil:NilClass - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3112.0/lib/bosh/director/instance_deleter.rb:31:in `delete_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3112.0/lib/bosh/director/instance_deleter.rb:21:in `block (3 levels) in delete_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3112.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3112.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3112.0/lib/c
```

**Comment by cppforlife** [comment]
We found that bug earlier and decided we will fix it as part of our work on global-net branch. I expect the fix will be available when we get to the following marker: https://www.pivotaltracker.com/story/show/100170490

**Comment by eLobeto** [comment]
I see the same issue and running debug shows me the following:

```
D, [2015-12-03 19:08:36 #28459] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: undefined method `cid' for nil:NilClass - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3126.0/lib/bosh/director/instance_deleter.rb:31:in `delete_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3126.0/lib/bosh/director/instance_deleter.rb:21:in `block (3 levels) in delete_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3126.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3126.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3126.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3126.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2015-12-03 19:08:36 #28459] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
```

Not sure if this is the same problem.

**Comment by dpb587-pivotal** [comment]
Closing - the VM-management work was released in v241 and this should be fixed now. Feel free to open a new issue with new stacktrace/details if you see it on newer versions of bosh.
